OpenTreeMap/otm-core

.travis.yml
ci/local_settings.py
circle.yml
package.json

I got significantly faster results from CircleCI than we're currently seeing from Travis CI, which I think is mostly from the caching of dependencies.
Average results for running the full test suite (without UI tests) seem to be around 5-7 minutes.  For comparison, Travis CI builds seem to take around 8-12 minutes.
Adding in UI tests makes the build time go up to about ~~12 minutes.~~ We can run the UI tests in parallel with the normal unit tests, which takes around 9:30

Run the unit tests on Circle CI

---

opentreemap/importer/errors.py
opentreemap/importer/templates/importer/partials/species_resolve_popover.html

Update species error message and correction instructions

---

opentreemap/importer/templates/importer/partials/imports.html

Add links to importer guids and templates

---

opentreemap/importer/views.py

Fix issue on importer with pagination links switching tabs

---

opentreemap/importer/models/trees.py

Only check the current instance when validating opentreemap id number

---

opentreemap/importer/errors.py
opentreemap/importer/templates/importer/partials/resolve_popover.html
opentreemap/importer/templates/importer/partials/species_resolve_popover.html
opentreemap/importer/views.py
opentreemap/treemap/css/sass/partials/pages/_importer.scss
opentreemap/treemap/templates/treemap/partials/popover.html

Importer error updates

---

opentreemap/importer/templates/importer/partials/imports.html

Fix species import guide link

---

opentreemap/treemap/css/sass/partials/pages/_profile.scss
opentreemap/treemap/lib/map_feature.py
opentreemap/treemap/models.py
opentreemap/treemap/templates/treemap/partials/user_favorite.html
opentreemap/treemap/templates/treemap/user.html
opentreemap/treemap/views/user.py

* Clicking the "star" on a map feature detail page adds an item to your favorites list.
* Hovering over an item on the favorites tab adds a light grey highlight
* Clicking anywhere on an item on the favorites tab links to the map feature detail page.

Add favorites list to profile page

---

opentreemap/treemap/lib/user.py

Trying to view user profiles other than your own with a large database was triggering a 500 response. The root cause was the fact that the ORM was generating a 2.2MB SQL statement, causing Postgres to choke with a stack error.
The audit query code in lib/user.py builds up the final QuerySet by gluing together several small parts. I discovered that the same instance was being fed into the filter multiple times, causing the ORM to generate a lot of duplicate clauses, bloating the query. Adding a ``distinct`` took care of that.
The fast majority of users will only edit a single instance, and our audit table is optimized for filtering by instance ID, so I added an additional query to fetch the ids of a users edited instances and use that to limit the scope of the query, rather than limiting …

Update user audit query to be more efficient

---

opentreemap/treemap/instance.py

addresses part of #1910
For presentation purposes

Add `itree_regions` method to instance

---

opentreemap/treemap/models.py

Change label for last updated search.

---

opentreemap/treemap/js/src/diameterCalculator.js

Previously, clearing a field would change it's value to 0.  Thus, if you
accidentally saved a diameter for a tree when you were unsure of the
diameter, there was no way to undo your action.  This change allows empty
values to pass through, so the backend can clear the field and set it
back to None.
Fixes #978

Allow resetting of diameter/circumeference fields to undefined.

---

opentreemap/exporter/tasks.py
opentreemap/treemap/instance.py
opentreemap/treemap/udf.py

connects to #2011 on github
@dboyer @jwalgran how does this look, formatting-wise?

Show UDFC values in exports

---

opentreemap/treemap/lib/photo.py

Don't send any url params to photo sharing s3 urls

---

opentreemap/treemap/templates/base.html

Fix styling error causing header to not appear on smaller screen sizes.

---

opentreemap/treemap/js/src/MapManager.js

connects #2038 on github
requires https://github.com/OpenTreeMap/otm-tiler/pull/65 for testing

Send filter strings to polygon layer

---

opentreemap/treemap/css/sass/partials/_header.scss
opentreemap/treemap/css/sass/partials/pages/_modeling.scss
opentreemap/treemap/templates/base.html
opentreemap/treemap/templates/instance_base.html

The new design for the modeling application unifies prioritization and scenarios into a "plan." We no longer need a drop down menu to access the different modeling modes because they we will each be accessible from the same single-page interface.
The design on the modeling application calls for a left-aligned toolbar in the header. The "search" sections of the header are all right-aligned, necessitating the creation of a new "toolbar" block.

New modeling toolbar

---

opentreemap/stormwater/models.py
opentreemap/treemap/ecobenefits.py
opentreemap/treemap/templates/treemap/partials/eco_benefits.html
opentreemap/treemap/views/tree.py

Make Bioswale participate in counts

---

opentreemap/exporter/models.py

@dboyer @maurizi what do you think of this, as a holdover? Looks like it can't hurt.

Clarify empty csv error text

---

opentreemap/treemap/js/src/mapFeature.js
opentreemap/treemap/js/src/plotMover.js
opentreemap/treemap/templates/treemap/map_feature_detail.html

connects #2130 on github
The TODO in here is something of a discussion point. Should this be done? It might involve far-reaching API changes.

Hide point marker on PolygonalMapFeature detail

---

opentreemap/api/README.md

Posting this for early feedback on the format.

Document input parameters for API endpoints

---

opentreemap/treemap/lib/map_feature.py
opentreemap/treemap/models.py
opentreemap/treemap/templates/treemap/field/resource_tree.html
opentreemap/treemap/templates/treemap/resource_detail.html
opentreemap/treemap/views/user.py

Also includes some general cleanups to the resource detail page.
Connects to #2161
Connects to #2122

Show trees in bioswales on detail page

---

opentreemap/stormwater/models.py
opentreemap/treemap/js/src/inlineEditForm.js
opentreemap/treemap/js/src/mapFeature.js
opentreemap/treemap/js/src/plotMover.js
opentreemap/treemap/lib/map_feature.py
opentreemap/treemap/templates/treemap/plot_detail.html
opentreemap/treemap/views/map_feature.py

connects #2123 on github
Also refreshes the page when a plot is moved in or out of a polygonal
map feature.

Hide plot/udf data on trees within pmfs

---

opentreemap/treemap/templates/treemap/map_feature_detail.html

Add comment disclaimer to all resources

---

opentreemap/treemap/templates/treemap/map_feature_detail.html

Fix 'delete' help text to represent correct model

---

opentreemap/treemap/audit.py

connects #2189 on github
before:
after:

Format lists as readable text in audit description

---

opentreemap/treemap/js/src/editableForm.js

Make multiselect widget case-insensitive

---

opentreemap/stormwater/models.py
opentreemap/treemap/audit.py
opentreemap/treemap/migrations/0006_stop_tracking_polygonal_mapfeature_ptr.py

Stop tracking `PolygonalMapFeature` subclass pointer
Change full_name property of `FieldPermission`

Fix a few issues with audits/permissions for Bioswales

---

opentreemap/treemap/js/src/addMapFeature.js
opentreemap/treemap/js/src/stepControls.js

Also, show toast if adding causes an unexpected error (e.g. a 500).
Connects #2188

When adding a feature, clicking "Done" twice no longer adds twice

---

opentreemap/stormwater/models.py

This was introduced in 1625f47b00

Fix regression in viewing and adding Bioswales.

---

opentreemap/treemap/ecobenefits.py

Note: This diff looks messy, but it's really just moving `TreeBenefitsCalculator._compute_currency_and_transform_units` to be a top-level function.

Make ecobenefits aggregator usable by other modules

---

opentreemap/treemap/js/src/addResourceMode.js
opentreemap/treemap/models.py
opentreemap/treemap/templates/treemap/partials/map_add_resource.html

Enable continue editing link when adding Bioswales

---

opentreemap/treemap/udf.py

Setting collection UDFs to read-only would prevent editing a model if
that model already had collection UDF data on it.  The fix is rather
simple - we no longer attempt to save collection UDF data if there have
been no changes.
I also fixed an issue with clean_value for collection UDFs where it would
attempt to parse a datetime object as a formatted string and turn it into
a date.  This was mostly a symptom, not a cause of the underlying issue,
but it is more correct anyways.

Fix saving models when collection UDFs are not writable.

---

opentreemap/treemap/css/sass/partials/pages/_scenarios.scss
opentreemap/treemap/ecobenefits.py
opentreemap/treemap/lib/__init__.py
opentreemap/treemap/tests/test_ecobenefits.py
opentreemap/treemap/units.py
opentreemap/treemap/views/tree.py

Don't show decimal digits in ecobenefit totals

---

opentreemap/treemap/js/src/geometryMover.js
opentreemap/treemap/js/src/mapFeature.js

Disable clicking other objects while moving a geom

---

opentreemap/otm_comments/templates/otm_comments/partials/moderation.html
opentreemap/treemap/css/sass/partials/_layout.scss
opentreemap/treemap/css/sass/partials/_navbar.scss
opentreemap/treemap/templates/instance_base.html

Fixes a styling issue with the header bar on the comment moderation page
as well as a styling issue on the global navbar.

Cleanup styling for small screens.

---

opentreemap/importer/js/src/importsList.js
opentreemap/importer/js/src/status.js
opentreemap/importer/models/base.py
opentreemap/importer/routes.py
opentreemap/importer/templates/importer/partials/import_table.html
opentreemap/importer/templates/importer/partials/import_tables.html
opentreemap/importer/templates/importer/partials/row_status.html
opentreemap/importer/tests.py
opentreemap/importer/urls.py
opentreemap/importer/views.py
opentreemap/opentreemap/settings/default_settings.py
opentreemap/treemap/css/sass/partials/pages/_importer.scss
opentreemap/treemap/templates/treemap/partials/paging_controls.html
requirements.txt

Also fix several small importer issues.
Connects #2259 
Connects #1918
Connects #2264

Add pagination controls for tables on main importer page

---

opentreemap/opentreemap/settings/default_settings.py
opentreemap/treemap/ecobenefits.py
opentreemap/treemap/ecocache.py
opentreemap/treemap/tests/test_ecobenefits.py
opentreemap/treemap/views/tree.py

Cache plot counts

---

opentreemap/treemap/css/sass/partials/pages/_admin.scss

connected to https://github.com/OpenTreeMap/otm-addons/pull/875

clean up the suspend map page

---

opentreemap/treemap/css/vendor/bootstrap.css
opentreemap/treemap/js/shim/bootstrap.js

https://github.com/angular-ui/bootstrap/issues/2970

Upgrade Bootstrap from 3.3.1 to 3.3.5 to fix a bug with modals

---

opentreemap/treemap/models.py

Connects to OpenTreeMap/otm-addons#900

Only show plots from the current instance on the map feature detail page

---

opentreemap/treemap/css/sass/partials/pages/_treedetails.scss

css fix for multiselect box overflowing incorrectly - fixes #2316

---

opentreemap/treemap/css/sass/main.scss
opentreemap/treemap/css/sass/partials/_modals.scss

Changes made for https://github.com/OpenTreeMap/otm-addons/issues/815

new warning and danger state styles for modals.

---

opentreemap/api/instance.py
opentreemap/treemap/audit.py
opentreemap/treemap/instance.py
opentreemap/treemap/udf.py

* Add `Role.DEFAULT_ROLE_NAMES`
* Add helper property `Instance.collection_udfs`

Add helpers

---

opentreemap/treemap/js/src/buttonEnabler.js
opentreemap/treemap/js/src/utility.js
opentreemap/treemap/templates/treemap/partials/form_buttons.html

* `buttonEnabler.js` no longer requires `options.config` argument
* Add JS Utility `modalsFocusOnFirstInputWhenShown`
* Allow adding buttons to `form_buttons.html` partial

Improve helpers

---

.gitignore
opentreemap/otm_comments/templates/otm_comments/partials/moderation.html
opentreemap/treemap/css/sass/_base.scss
opentreemap/treemap/css/sass/partials/pages/_admin.scss
opentreemap/treemap/templates/treemap/field/div.html

First round of admin dashboard cleanup as per Christopher's designs.
Sibling pull request of https://github.com/OpenTreeMap/otm-addons/pull/912

management table styles, management header styles, general cleanup

---

opentreemap/opentreemap/util.py
opentreemap/otm_comments/js/src/moderation.js
opentreemap/otm_comments/templates/otm_comments/partials/moderation.html
opentreemap/otm_comments/templates/otm_comments/partials/moderation_row.html
opentreemap/otm_comments/tests.py
opentreemap/otm_comments/uitests.py
opentreemap/otm_comments/views.py
opentreemap/treemap/js/src/batchModeration.js
opentreemap/treemap/js/src/photoReview.js
opentreemap/treemap/routes.py
opentreemap/treemap/templates/treemap/partials/photo.html
opentreemap/treemap/templates/treemap/partials/photo_review.html
opentreemap/treemap/tests/test_views.py
opentreemap/treemap/urls.py
opentreemap/treemap/views/photo.py

- Adjust text on photo review page and add an "Archived" filter.
- Add batch moderation UI to photo review page.
Connects to OpenTreeMap/otm-addons#926
Connects to OpenTreeMap/otm-addons#542

Photo review updates

---

opentreemap/exporter/tasks.py

This was broken by bf9b9d, which switched to `collection_udf_settings`.
Connects to #2359

Fix search exporting of collection UDFs.

---

opentreemap/treemap/instance.py

Fix regression with empty planting sites display filter

---

opentreemap/treemap/instance.py
opentreemap/treemap/search_fields.py
opentreemap/treemap/tests/test_instance.py

The search field constants and code were unwieldy in `instance.py`.

Create search_fields.py from instance.py

---

opentreemap/opentreemap/settings/default_settings.py
opentreemap/opentreemap/util.py
opentreemap/treemap/ecobackend.py
requirements.txt

Wire in rollbar service and use it to log ecoservice errors

---

opentreemap/treemap/js/src/searchBar.js

Don't highlight 'Advanced' during simple search

---

opentreemap/treemap/css/sass/partials/pages/_admin.scss

fixes https://github.com/OpenTreeMap/otm-addons/issues/934 and is a sibling pull request to https://github.com/OpenTreeMap/otm-addons/pull/1061

fixed spacing between sections in pricing modal

---

opentreemap/importer/tests.py
opentreemap/importer/views.py

Fix 500 when import started with no attachment

---

opentreemap/treemap/css/sass/partials/pages/_map.scss

Fix typo in typeahead bootstrap styling fix

---

opentreemap/treemap/lib/page_of_items.py

Connects OpenTreeMap/otm-addons#1064

Page of items: filter choices now preseve values of other filters

---

opentreemap/treemap/instance.py
opentreemap/treemap/migrations/0022_remove_null_from_eco_rev.py

Make eco_rev non-nullable

---

opentreemap/importer/errors.py
opentreemap/importer/models/trees.py

Fix importer's lat/long validation

---

opentreemap/treemap/css/sass/modules/_buttons.scss
opentreemap/treemap/css/sass/partials/pages/_admin.scss
opentreemap/treemap/js/src/baconUtils.js
opentreemap/treemap/templates/treemap/partials/form_buttons.html
opentreemap/treemap/templates/treemap/partials/paging_controls.html

- Add icons to the edit, save, and cancel buttons
- Add `'unlocalize` to paging controls link
- Add CSS for styling the user management search bar
- Expose a `recordUrl` Bacon utility.
Connects to OpenTreeMap/otm-addons#1089
Connects to OpenTreeMap/otm-addons#556

Make changes for user management page refactor

---

opentreemap/treemap/js/src/inlineEditForm.js

This changeset does two things:
1) makes onSaveBefore return type checking more explicit and throws with a
helpful message.
2) make the default onSaveBefore behavior return the correct type
This was necessary because for versions of the inlineEditForm that do
not override onSaveBefore, the identity function was used. This is not
correct because onSaveBefore must now return a stream, or null.

Confirm onSaveBefore returns correct value

---

opentreemap/importer/models/trees.py
opentreemap/importer/tests.py

Proximity validation can prevent instance admins from correcting the locations previously uploaded trees in bulk.
---
1. Create an instance centered on Reno, NV. Activate it so that exports are available.
1. Import [mgpoints.csv](https://github.com/OpenTreeMap/otm-core/files/164087/mgpoints.csv.zip)
1. Export all the planting sites and delete all the columns from the exported csv except for the `x` , `y`, and `id` columns. Change the column headers to `point x`, `point y`, and `opentreemap plot id`.
1. Shuffle the values in the `opentreemap plot id` column. (I used "Sort" in LibreOffice Calc to reverse them)
1. Import the edited file.
This fails on the `develop` branch, but should succeed on this branch.
---
Connects to https://github.com/OpenTreeMap/otm-clients/issues/183
Connects to …

Skip proximity validation on imports with IDs

---

opentreemap/treemap/css/sass/partials/_modals.scss
opentreemap/treemap/css/sass/partials/pages/_admin.scss
opentreemap/treemap/lib/udf.py
opentreemap/treemap/templates/base.html
opentreemap/treemap/udf.py

Connects to OpenTreeMap/otm-addons#1122

Add styling for modal to add a custom field

---

opentreemap/treemap/js/src/fieldHelpers.js

Previously when hitting "Save" on a detail page we PUT values for all multichoice fields even if those values had not changed.
That caused us to incorrectly create a tree when saving an empty planting site.
Now we correctly detect changes to multichoice fields and only PUT changed values.
Connects #2519
Testing:
1. Create a custom multichoice tree field
2. Open your developer tools network panel
2. On a tree detail page repeatedly Edit, change the value, and Save. Verify in the network panel that the correct
values are sent.
3. Delete the tree
4. Edit and Save. No tree should be created.

Only PUT multichoice field value if it has changed

---

opentreemap/importer/tests.py
opentreemap/treemap/instance.py
opentreemap/treemap/management/commands/create_instance.py
opentreemap/treemap/tests/__init__.py

Add and use helper methods to create instance bounds

---

opentreemap/treemap/templatetags/auth_extras.py

Fix crashes on user page for users whose username is all numbers

---

LICENSE

Depends on https://github.com/OpenTreeMap/otm-cloud/pull/174

Update year in LICENSE file

---

opentreemap/treemap/models.py

Safety code for unexpected case of saving map feature with null geometry

---

opentreemap/treemap/css/sass/partials/_subheader.scss

Connects to OpenTreeMap/otm-clients#211

Fix styling regression in by Chrome version 50

---

opentreemap/treemap/css/sass/partials/pages/_admin.scss

See https://github.com/OpenTreeMap/otm-addons/issues/1149

Finesse multiline treemap titles

---

opentreemap/otm_comments/templates/otm_comments/partials/moderation.html
opentreemap/treemap/css/sass/partials/pages/_admin.scss
opentreemap/treemap/templates/treemap/partials/form_buttons.html
opentreemap/treemap/templates/treemap/partials/photo_review.html

this goes with https://github.com/OpenTreeMap/otm-addons/pull/1164

fixes issue for otm-addon repo with header buttons overflowing

---

opentreemap/treemap/management/util.py

Connects to OpenTreeMap/otm-addons#1158

Only delete map-feature related audits in the 'delete_data' command

---

opentreemap/otm_comments/templates/otm_comments/partials/moderation.html

Fix broken comment moderation UI tests.

---

opentreemap/treemap/js/src/boundarySelect.js
opentreemap/treemap/js/src/layers.js

See discussion in code comments.
Connects #2569

Make tile layers display above boundary polygon

---

opentreemap/treemap/migrations/0028_auto_20160531_1537.py
opentreemap/treemap/models.py

This should be included in the next release after #2605 is released to production.

Make boundary searchable field non-null

---

opentreemap/treemap/js/src/layers.js

Instead of setting the layer URL to `noSearchUrl` after doing a
quick edit, we now update the rev hash on the layer URL to request new
tiles, while also preserving the current advanced search filters.
Test instructions are in #2437.
Connects #2437

Reapply search filters after quick edit

---

Gruntfile.js
opentreemap/treemap/css/sass/main.scss
opentreemap/treemap/css/sass/partials/_slider.scss
opentreemap/treemap/css/sass/partials/pages/_map.scss
opentreemap/treemap/js/shim/ion.rangeSlider.js
opentreemap/treemap/js/src/CanopyFilterControl.js
opentreemap/treemap/js/src/MapManager.js
opentreemap/treemap/js/src/layers.js
opentreemap/treemap/templates/treemap/map.html
opentreemap/treemap/templates/treemap/partials/canopy_filter_control.html
opentreemap/treemap/templates/treemap/settings.js

**Test:**
* Checkout https://github.com/OpenTreeMap/otm-tiler/pull/109 and restart the tiler
* Rebuild static assets `./scripts/grunt.sh`
* Load "PA Tree Map" (or any instance with canopy data)
* Set the canopy category `update treemap_instance set canopy_boundary_category ='Municipality' where url_name='patreemap';`
* Ensure that the "Regional Canopy Percentages" layer exists
* Ensure that the filter control appears when "Regional Canopy Percentages" layer is visible
* Ensure that altering the filter control updates the canopy layer
Connects #2609
Depends on https://github.com/OpenTreeMap/otm-tiler/pull/109

Add canopy percent choropleth layer

---

opentreemap/treemap/css/sass/partials/pages/_modeling.scss

Add CSS for the modeling leaflet loading control.

Add styling for modeling loading spinner

---

opentreemap/treemap/templates/treemap/partials/step_set_location.html

Fix styling on add tree validation div

---

opentreemap/stormwater/benefits.py
opentreemap/stormwater/tests.py
opentreemap/treemap/ecobenefits.py
opentreemap/treemap/tests/test_ecobenefits.py

Unit constants now in treemap.ecobenefits.
connects #2647
connects #2648

Moved general purpose units from private repo to core

---

opentreemap/treemap/lib/map_feature.py
opentreemap/treemap/templatetags/form_extras.py
opentreemap/treemap/tests/test_templatetags.py
opentreemap/treemap/units.py

Revert to displaying unit abbreviations, and fix display of area units

---

opentreemap/stormwater/models.py

Validate drainage area field

---

opentreemap/otm1_migrator/migration_rules/tampa.py

These commits were reviewed and merged to develop (#2742). This PR adds them to the recently created 2.11.0 release branch.
Connects to OpenTreeMap/otm-clients#276

Add meta species lookup table for Tampa migration

---

opentreemap/treemap/js/src/lib/editableForm.js
opentreemap/treemap/js/src/lib/fieldHelpers.js
opentreemap/treemap/js/src/mapFeatureDetail.js

* Make "favorite" click event resilient to reload
* Re-initialize detail form's "active" fields after reload 
Connects #2749 
Connects #2750 
Connects #2751

Fixes to the detail page for Edit / Save / Edit cycle

---

assets/css/sass/partials/_header.scss
assets/css/sass/partials/_layout.scss
assets/css/sass/partials/pages/_admin.scss
opentreemap/opentreemap/context_processors.py
opentreemap/opentreemap/util.py
opentreemap/treemap/decorators.py
opentreemap/treemap/tests/test_urls.py

* Place all radio buttons on the same line
* Only show width x height + Preview when Custom is checked
* Fix the width of the `iframe` input element
* Vertical spacing
* Fix responsive design
* Add `.hidden` class for error messages
--
Connects to OpenTreeMap/otm-addons#1232
Depends on OpenTreeMap/otm-addons#1240

styles for embedded map

---

opentreemap/treemap/js/src/mapFeatureDetail.js
opentreemap/treemap/templates/treemap/partials/map_feature_detail_base.html

* Message is either "Add to Favorites" or "Remove from Favorites"
* Messages stored in data attributes so they can be translated
* Refactor favorite management code so message is shown in all cases
Testing:
Make sure favorite star and hover message appear correctly in all cases, including after an Edit/Save cycle.
Connects #1961

When hovering on "Favorites" star, show message saying what will happen

---

opentreemap/treemap/templates/treemap/map-browse-trees.html
opentreemap/treemap/templates/treemap/partials/map_feature_popup.html

Change tree detail button labels to "More Details" and "Edit"

---

assets/css/sass/partials/pages/_modeling.scss

Connects OpenTreeMap/otm-addons#1268

Fix blank area on right side of modeling map

---

assets/css/sass/partials/_layout.scss

Raise the z-index.
--
Connects to #2735

Fix clipped datepicker

---

opentreemap/treemap/tests/test_udfs.py

The values in a collection field (like Stewardship) are unordered. That was a surprise to me, but we get away with it because the collection fields we've used (Stewardship, Alerts) always have a date member and we can sort by that.
When we reference the values of a collection field, like here:
https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/tests/test_udfs.py#L1087
their order is indeterminate. Here's where we build the list of values:
https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/udf.py#L935
On the other hand, note that the order of `plot.audits()` is deterministic, since we can sort by `created`:
https://github.com/OpenTreeMap/otm-core/blob/develop/opentreemap/treemap/udf.py#L1117
To fix the tests:
* Use sets when comparing values of a …

Fix tests which rely on order of collection field values

---

assets/css/sass/partials/pages/_admin.scss
opentreemap/otm_comments/uitests.py
opentreemap/treemap/instance.py
opentreemap/treemap/lib/udf.py
opentreemap/treemap/migrations/0032_add_udfs_to_web_detail_fields.py
opentreemap/treemap/migrations/0035_merge.py
opentreemap/treemap/search_fields.py
opentreemap/treemap/templates/treemap/field/tree_id_tr.html
opentreemap/treemap/templates/treemap/partials/plot_detail.html
opentreemap/treemap/templates/treemap/partials/plot_section.html
opentreemap/treemap/templates/treemap/partials/tree_section.html
opentreemap/treemap/templatetags/util.py
opentreemap/treemap/tests/test_instance.py
opentreemap/treemap/tests/test_urls.py
opentreemap/treemap/tests/ui/__init__.py
opentreemap/treemap/udf.py
opentreemap/treemap/views/map_feature.py

Required by https://github.com/OpenTreeMap/otm-addons/pull/1297
Connects to OpenTreeMap/otm-addons#1278

Show plot detail page fields based on configurable order

---

assets/css/sass/partials/pages/_scenarios.scss

This adds some missing CSS (and removes obsolete CSS) that was changed when fixing up a PR for the modeling charts.

Add missing modeling styles

---

requirements.txt

Update Python Rollbar client to 13.8.
Test using [#315](https://github.com/OpenTreeMap/otm-cloud/pull/315)

Update rollbar client

---

opentreemap/treemap/templates/treemap/map-browse-trees.html

Check whether the plot is writable, not specific field.
--
Connects to #2870

Fix quick edit move tree

---

opentreemap/treemap/routes.py
opentreemap/treemap/tests/test_views.py
opentreemap/treemap/urls.py
opentreemap/treemap/views/user.py

Intended for implementing OpenTreeMap/otm-core#388
Connects to #2864

Add endpoint for searching for users on a map

---

assets/css/sass/partials/_header.scss
assets/css/sass/partials/pages/_registration.scss
opentreemap/treemap/js/src/lib/browseTreesMode.js
opentreemap/treemap/js/src/lib/searchBar.js
opentreemap/treemap/templates/base.html
opentreemap/treemap/templates/instance_base.html
opentreemap/treemap/templates/treemap/partials/map_add_resource.html
opentreemap/treemap/templates/treemap/partials/map_feature_popup.html

Fixes a variety of small design bugs
Connects to #2859 
Connects to #2902
Connects to #2900
Connects to #2869
Connects to #2901

Style fixes

---

assets/css/sass/partials/pages/_modeling.scss
opentreemap/treemap/js/src/lib/mapPage.js
opentreemap/treemap/js/src/treeMap.js
opentreemap/treemap/templates/treemap/partials/search_location.html

* Make it an option to fill the highlighted area when zooming to a searched boundary
* Make it an option to add the search query to the URL
* Allow overriding the "Search by Location" label

Support modeling location search tuning

---

opentreemap/treemap/js/src/lib/buttonEnabler.js
opentreemap/treemap/js/src/lib/inlineEditForm.js

Go directly to the login page, without entering edit mode.
--
Connects to #2897

Fix quick edit for logged out user

---

assets/css/sass/partials/pages/_scenarios.scss

fixes https://github.com/OpenTreeMap/otm-addons/issues/1382

fixed buttons overlaying in modeling scenario editing

---

assets/css/sass/partials/pages/_modeling.scss

Connects OpenTreeMap/otm-addons#1261

Adjust styles for "top areas"/"all areas" modeling slider

---

opentreemap/treemap/routes.py
opentreemap/treemap/views/tree.py

Use universal_rev to compute ecobenefits etag instead of Audit table

---

opentreemap/treemap/migrations/0042_auto_20170112_1603.py
opentreemap/treemap/models.py

Change Updated By to Last Updated By

---

opentreemap/treemap/instance.py

Testing:
1. Create an instance centered on Pleasanton, CA (or use `/alamedacounty` if you have it)
1. Change the instance bounds by uploading `users/rmohr/data/changeBounds/alameda.geojson` from the fileshare (which contains MultiPolygons).
1. Verify that you can only add a tree in places matching:

Allow multipolygons in map boundary GeoJSON

---

assets/css/sass/_base.scss
assets/css/sass/partials/_header.scss

-  Fix reset button styling on mobile
-  Prevent active search icon from overlapping search box
Connects to #2948
Connects to #2947

Fix Mobile search styling bugs

---

opentreemap/treemap/js/src/lib/otmTypeahead.js
opentreemap/treemap/templates/treemap/partials/autocomplete.html
opentreemap/treemap/templatetags/form_extras.py
opentreemap/treemap/views/misc.py

Server and Client parts.
Could not get Bloodhound prepopulation to work with a literal,
but Last Updated By now shows the currect display value.

Correct display value in last updated by search

---

opentreemap/treemap/lib/photo.py

The query strings present on S3 URLs allow for temporary access to private
buckets, but this isn't required for tree photos, which are stored in
a public S3 bucket.
For some reason having the query string present was preventing recent
versions of the Android app from downloading photos. In order to support
these older versions we're stripping the query string from the URL in the
backend, as the Android app can download photos without the query string.
NOTE there is supposed to be support in Boto for turning off signed URLs,
but this appears to be broken when using IAM roles instead of an access key
and secret key for authentication with AWS.
Connects to OpenTreeMap/otm-android#307

Strip query strings from tree photo URLs

---

opentreemap/treemap/instance.py
opentreemap/treemap/migrations/0043_works_management_access.py

Add instance permission and associated data migration
--
Connects to OpenTreeMap/otm-addons#1444
Depends on OpenTreeMap/otm-addons#1450

Works Management Permissions

---

assets/css/sass/partials/_header.scss
assets/css/sass/partials/_layout.scss
opentreemap/treemap/js/src/mapPage/adHocPolygon.js
opentreemap/treemap/js/src/mapPage/drawAreaMode.js
opentreemap/treemap/js/src/mapPage/editAreaMode.js
opentreemap/treemap/js/src/mapPage/modes.js
opentreemap/treemap/js/src/treeMap.js
opentreemap/treemap/templates/treemap/partials/search_location_polygon_editing.html
opentreemap/treemap/templates/treemap/settings.js

Refactor
* `drawAreaMode.js` manages all activate/deactivate details for drawing
* `adHocPolygon.js` just manages the "Search by Location" area and the polygon
Add `editAreaMode.js` to manage activate/deactivate details for editing
Testing (includes all tests from #3001):
* Clicking "pencil" icon in "Search by Location":
* Shows "Draw area on map" in "Search by Location"
* Lets you draw a polygon
* If a tree was selected, closes the popup and hides the marker. (Does not clear the sidebar -- see #3000)
* If you were adding a tree or editing a tree, shows "Are you sure?" alert
* Clicking "Cancel" allows you to continue adding or editing the tree
* Click "OK" cancels the add or edit and lets you draw a polygon
* While drawing a polygon:
* You see our custom tooltips
* Clicking on a tree dot …

Edit "custom area" polygons

---

opentreemap/opentreemap/settings/default_settings.py
opentreemap/works_management/migrations/0001_initial.py
opentreemap/works_management/models.py
opentreemap/works_management/tests.py
opentreemap/works_management/urls.py
opentreemap/works_management/views.py

Create Django app, models, migrations, and unit tests for
works_management feature.
Connects #2996

Create works_management app

---

opentreemap/importer/tasks.py
opentreemap/importer/tests.py

Testing:
* Without and with these changes, import `//fileshare/users/rmohr/data/importer/blankRows.csv`
* Without these changes you get 3 rows (2 with "missing required field" errors)
* With these chages you get 1 row
Connects #3040

Importer ignores blank rows in CSV

---

assets/css/sass/partials/pages/_admin.scss
opentreemap/treemap/instance.py
opentreemap/treemap/lib/udf.py
opentreemap/treemap/tests/test_udfs.py
opentreemap/treemap/udf.py
opentreemap/treemap/util.py
opentreemap/works_management/models.py
opentreemap/works_management/tests.py

Implement changes necessary to create and modify Works Management custom fields from the cloud management admin.
```
./scripts/manage.sh test treemap.tests.test_udfs
```

Implement Works Management Custom Fields admin page

---

assets/css/sass/partials/pages/_admin.scss
opentreemap/treemap/js/src/lib/inlineEditForm.js
opentreemap/treemap/udf.py

Remove a now unused udf property.
Add option to inlineEditForm.js to allow override of the
function to get data to send to the server.
Styling.
--
Connects to OpenTreeMap/otm-addons#1121
Depends on OpenTreeMap/otm-addons#1478

Custom Fields management page rework

---

opentreemap/manage_treemap/js/src/benefits.js
opentreemap/manage_treemap/js/src/lib/adminPage.js
opentreemap/manage_treemap/routes.py
opentreemap/manage_treemap/templates/manage_treemap/benefits.html
opentreemap/manage_treemap/templates/manage_treemap/management_base.html
opentreemap/manage_treemap/templates/manage_treemap/partials/admin_icon_link.html
opentreemap/manage_treemap/templates/manage_treemap/partials/admin_link.html
opentreemap/manage_treemap/templates/manage_treemap/partials/admin_notification.html
opentreemap/manage_treemap/templates/manage_treemap/partials/benefits_warning.html
opentreemap/manage_treemap/templates/manage_treemap/partials/nested_link.html
opentreemap/manage_treemap/tests/test_ecobenefits.py
opentreemap/manage_treemap/tests/test_urls.py
opentreemap/manage_treemap/urls.py
opentreemap/manage_treemap/views.py

Required by OpenTreeMap/otm-addons#1486

Move the "Ecosystem Benefits" management page

---

assets/css/sass/partials/pages/_admin.scss

Styling for additional error message.
--
Connects to OpenTreeMap/otm-addons#1482
Is required by OpenTreeMap/otm-addons#1494

Defer choice delete until Save

---

opentreemap/treemap/js/test/urlState.js
opentreemap/treemap/templates/instance_base.html

Connects OpenTreeMap/otm-addons#1505
Required by OpenTreeMap/otm-addons#1514

Remove modeling module

---

opentreemap/otm_comments/templates/otm_comments/partials/moderation.html

from "Export All" to just "Export"
--
Connects to OpenTreeMap/otm-addons#1152

Change comment export button text

---

opentreemap/importer/js/src/lib/status.js
opentreemap/manage_treemap/js/src/udfs.js
opentreemap/otm_comments/js/src/lib/comments.js
opentreemap/treemap/js/src/lib/MapManager.js
opentreemap/treemap/js/src/lib/baconUtils.js
opentreemap/treemap/js/src/lib/editableForm.js
opentreemap/treemap/js/src/lib/export.js
opentreemap/treemap/js/src/lib/inlineEditForm.js
opentreemap/treemap/js/src/lib/mapFeatureUdf.js
opentreemap/treemap/js/src/lib/plotAddTree.js
opentreemap/treemap/js/src/lib/plotDetail.js
opentreemap/treemap/js/src/lib/popover.js
opentreemap/treemap/js/src/lib/search.js
opentreemap/treemap/js/src/lib/searchBar.js
opentreemap/treemap/js/src/lib/udfcSearch.js
opentreemap/treemap/js/src/lib/urlState.js
opentreemap/treemap/js/src/lib/utility.js
opentreemap/treemap/js/src/mapFeatureDetail.js
opentreemap/treemap/js/src/mapPage/locationSearchUI.js
opentreemap/treemap/js/src/treeMap.js
opentreemap/treemap/js/test/urlState.js
package.json
yarn.lock

I attempted updating Bacon.js as well, but had to revert those changes, as it caused significant regressions with no simple fixes. See https://github.com/OpenTreeMap/otm-core/issues/3129 for more details.
Connects to #3115

Update lodash and ramda to latest versions.

---

opentreemap/exporter/tasks.py
opentreemap/importer/fields.py
opentreemap/importer/models/base.py
opentreemap/importer/models/species.py
opentreemap/importer/models/trees.py
opentreemap/importer/tasks.py

Also ignore these fields in the Bulk Uploader
Connects to #3146

Add Updated At and Updated By fields to the export

---

opentreemap/manage_treemap/js/src/users.js
opentreemap/manage_treemap/routes.py
opentreemap/manage_treemap/templates/manage_treemap/partials/user_role.html
opentreemap/manage_treemap/templates/manage_treemap/partials/user_roles.html
opentreemap/manage_treemap/templates/manage_treemap/user_roles.html
opentreemap/manage_treemap/urls.py
opentreemap/manage_treemap/views/user_roles.py

Add ability to remove user invitations to the Users management page

---

assets/css/sass/partials/pages/_registration.scss
opentreemap/manage_treemap/tests/test_instance_invitations.py
opentreemap/opentreemap/settings/default_settings.py
opentreemap/opentreemap/urls.py
opentreemap/registration_backend/urls.py
opentreemap/registration_backend/views.py
opentreemap/treemap/routes.py
opentreemap/treemap/templates/registration/login.html
opentreemap/treemap/templates/registration/password_reset_form.html
opentreemap/treemap/templates/registration/registration_complete.html
opentreemap/treemap/templates/treemap/forgot_username.html
opentreemap/treemap/templates/treemap/resend_activation_email.html
opentreemap/treemap/templates/treemap/resend_activation_email_done.html
opentreemap/treemap/views/user.py

Registration and authentication workflow enhancements

---

assets/css/sass/partials/pages/_map.scss
opentreemap/treemap/js/src/mapPage/browseTreesMode.js
opentreemap/treemap/models.py
opentreemap/treemap/templates/treemap/partials/map_feature_popup.html
opentreemap/treemap/views/map_feature.py

Uses the same distance calculation used in the "Nearby Trees" sidebar
on the plot detail page (but also includes non-Plot map features)
Connects to #3145

Disambiguate in map popup for multiple features at the same location

---

assets/css/sass/partials/pages/_modeling.scss
opentreemap/modeling/templates/modeling/modeling.html

Fix styling of link to prioritization demo on Firefox

---

opentreemap/treemap/views/misc.py

Connects to OpenTreeMap/otm-addons#1541

Fix adding green infrastructure for public users

---

assets/css/sass/partials/pages/_registration.scss
opentreemap/treemap/templates/registration/registration_form.html

Fix styling issues for registration page on small screens

---

opentreemap/treemap/js/src/lib/otmTypeahead.js

In a previous commit we made the search system more user friendly by automatically triggering an autocomplete when pressing the enter key in a typeahead or clicking the "Search" button. In the case where the user selects an item from the dropdown list rather than typing Enter, clicking "Search" would trigger the autocomplete action which would select the first item in the dropdown list instead of acknowledging the already selected item.
This commit addresses that problem by keeping track of the last selected item and skipping the autocomplete action if the current value of the text field matches.
---
- Select an item from the species dropdown and click "Search." The selected species should not change.
- All other autocomplete behavior remains unchanged.
---
Connects to #3080

Update otmTypeahead track last menu selection / skip autocomplete

---

opentreemap/manage_treemap/js/src/lib/adminPage.js

Connects to OpenTreeMap/otm-addons#569

Add navigation confirmation dialog to management pages

---

opentreemap/treemap/js/src/lib/diameterCalculator.js

Prevent negative diameters from saving as positive, and instead show error

---

opentreemap/treemap/instance.py
opentreemap/treemap/tests/test_instance.py

Connects to OpenTreeMap/otm-addons#1436

Validate instance bounds when creating them from geojson

---

opentreemap/stormwater/models.py
opentreemap/treemap/audit.py

Calculate area in edits sidebar more accurately and use instance units

---

opentreemap/treemap/js/src/lib/otmTypeahead.js

Fix bug where invalid species could result in species not changing

---

opentreemap/treemap/search.py
opentreemap/treemap/tests/test_search.py

Prior to this commit filters did not take instance unit preferences into account. I have added a "preprocessing" method that we can pass the filter object through which converts any values before the filter object is passed off to be converted into a query.
I have decided to implement this conversion on the server side to prevent having to change both mobile apps and the web client.
Connects https://github.com/OpenTreeMap/otm-clients/issues/399
Depends on https://github.com/OpenTreeMap/otm-tiler/pull/118
* Create a new instance with the url name `unit-convert-test` and select the green infrastructure addon http://localhost:6060/create/
* Edit the green infrastructure settings. Enable rain barrels. Save. http://localhost:6060/unit-convert-test/management/green-infrastructure/
* Add 4 trees …

Add filter unit conversion

---

opentreemap/exporter/tasks.py
opentreemap/treemap/search.py
opentreemap/treemap/tests/test_search.py

**NOTE**: This PR is built on top of #3222. Only commit 7d66d4f is new
Prior to this PR exported data was always in the default English units.
I took advantage of the custom serializer support in django-queryset-csv to do
the conversions.
Connects https://github.com/OpenTreeMap/otm-clients/issues/399
* Create a new instance with the url name `unit-export-test` http://localhost:6060/create/
* Add a tree with a diameter of 1 and choose the "Continue editing this tree" at the end of the add tree wizard http://localhost:6060/unit-export-test/map/?m=addTree
* Set Tree Height, Canopy Height, Planting Site Width, and Planting Site Height to 1. Save.
* Enable exports by adding credit card info to the billing management page http://localhost:6060/unit-export-test/management/billing/
* Name on …

Export values in the units specified on the units management page

---

opentreemap/manage_treemap/js/src/lib/errors.js
opentreemap/treemap/js/src/lib/otmTypeahead.js
package.json

* mustache from ~0.7.2 to ~2.2.1
* moment from ~2.2.1 to ~2.11.2 
Connects #3230 
* Create an instance via http://localhost:6060/create
* Add a tree and choose the "continue editing" option to move to the detail edit page
* Enter a "Date Planted" value
* Advanced Search for a date planted range and verify that the tree is matched.
* Edit and safe the Date Planted and verify that the value is correct after a refresh.
* Focus the "Search by location" field and verify that zip codes are loaded as suggestions
* Add a tree and choose the "continue editing" option to move to the detail edit page
* Set the diameter to "foo" and attempt to save the tree. Verify that an error is correctly displayed.

Upgrade JS dependencies

---

opentreemap/treemap/templates/registration/password_change_done.html
opentreemap/treemap/templates/registration/password_change_form.html
opentreemap/treemap/templates/treemap/user.html

Added option to change password from user profile

---

opentreemap/treemap/templates/registration/password_change_form.html

Connects to #1672
Related to #3235

Small updates to password reset form

---

opentreemap/treemap/js/src/lib/MapManager.js

connect to #832. Using local storage API

Store current base map in local storage

---

package.json
yarn.lock

Incorporates bug fixes.
Connects https://github.com/OpenTreeMap/otm-cloud/issues/432
* `vagrant provision app` to install the updated dependency.
* Create an instance via http://localhost:6060/create
* Add a tree and choose the "continue editing" option to move to the detail edit page
* Enter a "Date Planted" value and save the tree
* Advanced Search for a date planted range and verify that the tree is matched.
* Edit and safe the Date Planted and verify that the value is correct after a refresh.

Update moment to 2.19.3
