OpenTreeMap/otm-core

- Vagrantfile
Use `rsync` for top level of shared folder so that symbolic links can be created in the `node_modules` folder.
Use a true shared folder for `opentreemap`, for convenience and so migrations made on the VM won't be clobbered.
> In Vagrantfile, on Windows, use rsync for top level of shared folder

- opentreemap/importer/fields.py
- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
- opentreemap/importer/views.py
The backend does not yet support read only tree enforcement so, to avoid confusion, we are removing it from the importer as an available field.
I used the same "TODO: READONLY" comment everywhere I removed code so all the blocks can be easily found and restored when the feature is implemented.
Fixes #1890
> Comment out importer support for read only trees

- opentreemap/importer/templates/importer/partials/import_table.html
The import event id is an internal primary key shared across all instances. It is confusing for the first import created by the map owner to be labeled 17, and the next labeled 21.
The upload date is not only less confusing, but provides additional, useful information.
Fixes #1891
> Show import upload date rather than PK

- opentreemap/importer/templates/importer/partials/imports.html
fixes #1898 on github
* this has decent but not complete support on popular browsers. It's
supposed to be included in the version of firefox that ships in April,
and it's already supported in Chrome and IE11.
> Limit* importer uploads to csv and update text

- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
Meaning of "Tree Present" values:
* False: don't create a tree even if tree data is present
* True: do create a tree even if no tree data is present
* blank value or column absent: create a tree only if tree data is present
> Fix "Tree Present" handling

- opentreemap/treemap/migrations/0091_remove_gender_permissions.py
The gender field was removed from the Species model in 8fe1d9ff, but lingering FieldPermission rows that reference this deleted column cause CSV exports to crash.
> Remove FieldPermission rows for Species.gender

- opentreemap/otm1_migrator/migration_rules/standard_otm1.py
- opentreemap/otm1_migrator/model_processors.py
- opentreemap/treemap/js/src/mapFeature.js
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/migrations/0091_auto__add_field_treefavorite_map_feature__chg_field_treefavorite_tree.py
- opentreemap/treemap/migrations/0092_add_map_feature_to_tree_favorite.py
- opentreemap/treemap/migrations/0093_auto__del_field_treefavorite_tree__chg_field_treefavorite_map_feature_.py
- opentreemap/treemap/migrations/0094_auto__rename_treefavorite_favorite.py
- opentreemap/treemap/models.py
- opentreemap/treemap/routes.py
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/urls.py
- opentreemap/treemap/views/map_feature.py
Builds on top of #1948
Adds a UI for favoriting trees, and converts the existing `TreeFavorite` model into a map feature based `Favorite` model.
> Add tree favorites

- opentreemap/treemap/views/user.py
My initial implementation of getting thumbnails for the favorites list had two flaws:
1. I was manually constructing a photo URL, rather than using the
``url`` property of the photo instance. This broke when running in AWS
where photos are in S3 rather than the media directory.
2. When the map feature is a plot, the photo to be displayed is attached
to the current tree, not the plot itself.
> Fix favorite list image URL construction

- opentreemap/treemap/lib/user.py
There are two optimizations in this change set that reduce the query time of the instance edits page on my dev vm by 5x
```
Before: 10,700.12 ms (153 queries)
After:   2,741.48 ms (152 queries)
```
When the edits page was created as part of 369749a, an additional sort by id was added to the queryset. This technically produces more correct output, since the audits will be displayed in the exact order they were written to the table, but it causes a 5x slowdown in query execution time.
On my development wm with  5 million row audit table the filtered count query was taking 2 seconds to execute. I was able to remove the call to ``.count()`` entirely because a slice operator is applied to the queryset  earlier in the function, which realizes the quersets and allows us to use len()
> Speed up instance edits page

- opentreemap/treemap/templates/treemap/user.html
- opentreemap/treemap/views/user.py
My profile page says "You" while other people's pages say "This person"
Fixes #1958
> Show different messages on empty favorites list

- opentreemap/api/tests.py
- opentreemap/api/views.py
The species list API endpoint was failing with a strange "Can't adapt type 'Instance'" error. It turns out this was caused by a refactor in
0eb39f023 which resulted in the species list endpoint being wrapped with the ``instance_request`` decorator twice.
Fixes #1964
> Fix species list API double decoration error

- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/tests/test_audit.py
- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/udf.py
Adds validation that prevents UDFs from being created if their name contains
any problematic characters.  I tried every special character on a US keyboard
and only found issues with '%', '_', and '.'
'%' and '__' both cause issues for the Django ORM, preventing us from querying
for those UDFs by name.
'.' causes issues when attempting to render the Plot Detail
Also loosens restrictions on UDF names used by the form_extras template tags,
to allow any characters.
Fixes #1765
> Fix issues with invalid UDF names.

- opentreemap/treemap/audit.py
- opentreemap/treemap/lib/__init__.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/management/commands/set_mapfeature_updated_at.py
- opentreemap/treemap/migrations/0095_auto__add_field_mapfeature_updated_at.py
- opentreemap/treemap/migrations/0096_set_mapfeature_updated_at.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/test_map_feature.py
- opentreemap/treemap/tests/test_updated_at.py
- opentreemap/treemap/tests/test_views.py
We have decided to keep a denormalized copy of the time each MapFeature was last updated to facilitate simple querying. This commit adds a new updated_at field and functionality to keep it maintained.
Managing updates to this new field when only a child object changes (Tree, Photo, etc.) is tricky. I opted to target the easily findable save methods and add a call to a new function that updates the parent MapFeature row directly, rather than depend on save_with_user being called on the MapFeature instance when none of the properties of that object have changed.
Adding updated_at created an interesting field permission wrinkle. I did not want to have to create explicit permission objects to control this "special" field. Adding a tree photo will require permission to edit updated_at, even if …
> Add updated_at to MapFeature

- opentreemap/treemap/audit.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/models.py
Builds on top of #1969
Showing the "always writeable" `updated_at` field required changing a bit more of the mechanics of `Authorizable`, but nothing too significant.
> Add Last updated at to advanced search

- test-requirements.txt
CircleCI recently updated their installed version of Firefox, which broke
our UI tests. Updating Selenium should fix them again.
> Update to latest Selenium version to support newer Firefox versions.

- opentreemap/otm_comments/js/src/comments.js
- opentreemap/treemap/templates/treemap/map_feature_detail.html
Attempting to post an empty comment would lead to incorrect behaviour
like redirecting to an unstyled page.
This commit fixes the issue by disabling the submit button when the
textbox is empty, and enabling when text has been entered.
Fixes #1596
> Prevent submitting empty comments.

- opentreemap/exporter/models.py
- opentreemap/exporter/tasks.py
fixes #1370 on github
This changeset wraps the logic of async export jobs to mark the job as
failed in the case of an uncaught exception. Jobs will be marked failed
and then the exception will reraise, for logging or further handling in
the future.
If celery is not running, jobs will still poll forever, and once celery
is started, they will be picked up and finished.
> Mark export jobs as failed on async exception

- opentreemap/exporter/__init__.py
- opentreemap/exporter/decorators.py
- opentreemap/exporter/lib.py
- opentreemap/exporter/templatetags/exports.py
- opentreemap/exporter/tests.py
- opentreemap/exporter/views.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/migrations/0097_auto__add_field_instance_non_admins_can_export.py
- opentreemap/treemap/plugin.py
- opentreemap/treemap/templates/instance_base.html
This commit adds a boolean attribute to the instance model for controlling whether or not non-administrators can download data as CSV.
The flag is checked by a helper method both at the template level, to hide the export button, and at the task level to prevent a template bug or manually crafted request from "leaking" the data when the admins have disallowed it.
The new helper extends the existing check of whether the export feature is enabled at all and, as a result, applies that check in more places than it was being applied previously.
Fixes #1359
> Allow map admins to disable exports

- opentreemap/importer/models/base.py
The CANCELED status code was overlapping with the LOADING status code.
> Make importer event statuses unique

- opentreemap/importer/models/base.py
- opentreemap/importer/tasks.py
Import jobs were appearing to be "hung" in the validation step of a tree import for two reasons:
1. The process of chunking up a large import file into tasks takes some time. Rows are not being processed during this setup phase, so the counter appeared to be stuck at zero.
2. An error during the verification setup would cause the task to fail silently without updating the import event status, which remained stuck at "Verifying."
I added two additional import event states to cover these two cases, PREPARING_VERIFICATION and VERIFICATION_ERROR.
Fixes #1979
I tested the PREPARING_VERIFICATION state by importing a 100,000 tree CSV and watching the management page change status
I tested the VERIFICATION_ERROR status by inserting a ``raise`` into the try block and then importing a tree file.
> Add states to import validation

- opentreemap/treemap/DotDict.py
- opentreemap/treemap/lib/object_caches.py
Also adds support for deepcopy to `DotDict`, which should fix issues with
pickling it.
Fixes #1764
> Prevent inadvertent modification of cached objects by returning copies

- opentreemap/importer/tasks.py
- opentreemap/importer/util.py
Using ``csv.Sniffer`` provides us with alternate line ending detection, and we get things like tab separated file detection and support for free.
Files I used to test the imports:
http://cl.ly/1B3b1I0X2Z11/1998_csv_import_test_files.zip
Connects to #1998
> Update importer to handle CR terminated CSV files

- opentreemap/treemap/search.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_search.py
We were using `contained`, which determines if the geometry is within
the bounding box of a boundary.  The more appropriate filter to use is
`within`, which will only match when the geometry is entirely within
the boundary.
Connects to #2010
> Fix boundary filter on ecobenefits/counts.

- opentreemap/treemap/js/src/treeMapModes.js
Ensures that adding a tree or changing diameter or species is reflected
in tree counts and ecobenefits results.
Connects to #1991 
To test:
1. Ensure that adding a tree to an existing plot via "Quick Edit" will increment the plot/tree counts and update the ecobenefits.
> Update the ecobenefits and plot/tree counts when saving via quick edit.

- opentreemap/treemap/js/shim/leaflet.google.js
- opentreemap/treemap/js/src/MapManager.js
Originally, turning the zoom level up to 21 caused bugs on the satellite
layer when zooming in on areas that don't support such high
levels. Fixes in the google plugin for leaflet made it possible to go up
to 21 universally and it will disallow levels that aren't supported.
> Increase maxZoom to 21

- opentreemap/importer/tasks.py
- opentreemap/importer/views.py
I'm not sure how this ever worked. Notes:
* `Chord` returns an `AsyncResult` (not documented)
* Use `AsyncResult.parent` to get a `GroupResult`
* Use `save()` and `restore()` on the `GroupResult` as suggested in http://stackoverflow.com/questions/13685344/retrieving-groupresult-from-taskset-id-in-celery
Connects #2030
> Restore ability to cancel imports

- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/otmTypeahead.js
- opentreemap/treemap/js/src/treeMapModes.js
- opentreemap/treemap/migrations/0099_auto__add_field_species_updated_at__add_field_boundary_updated_at.py
- opentreemap/treemap/migrations/0100_auto__chg_field_species_updated_at__chg_field_boundary_updated_at.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/field/species_typeahead.html
- opentreemap/treemap/templates/treemap/partials/search_location.html
- opentreemap/treemap/templates/treemap/partials/search_species.html
- opentreemap/treemap/templates/treemap/plot_detail.html
- opentreemap/treemap/templatetags/species_thumbprint.py
- opentreemap/treemap/tests/test_instance.py
See https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md
for a description of cache parameters discussed here.
We were re-fetching an instance's species and boundary data on every page load
because we were using `ttl` ("time to live") of 0.
Fix is to use a default `ttl` of one day, and a `thumbprint` (cache buster) based on
the latest update time of the appropriate table (Species or Boundary).
Also, visiting too many instances was causing a "quota exceeded" error for browser local storage.
Fix is to use an instance-independent `cacheKey` ("species" or "boundary").
That means switching instances invalidates the cache, but that's rare compared to
visiting many consecutive pages on the same instance.
Connects #1857
Connects #2019
Connects #199
To test:
0) Clear your browser …
> Cache species and boundary autocomplete data

- opentreemap/treemap/migrations/0099_auto__add_field_species_updated_at__add_field_boundary_updated_at.py
- opentreemap/treemap/models.py
Currently nullable for backwards compatibility.
In the next release they will be non-nullable and support caching of autocomplete data.
> Add `updated_at` field to `Boundary` and `Species` models.

- opentreemap/treemap/js/src/MapManager.js
- opentreemap/treemap/templates/treemap/map.html
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/views/map_feature.py
- opentreemap/treemap/views/misc.py
Show layer only if
* instance has polygonal map feature types, and
* zoom is 15 or higher
And while we're at it, likewise show boundary layer only if
* instance has boundaries, and
* zoom is 15 or higher
Communicate `has_polygons` and `has_boundaries` via data attributes on the map DOM element, for both the main map and detail map.
To test:
0) Get OpenTreeMap/otm-tiler#63 and restart the tiler
1) Add the `Bioswale` map feature type to an instance
2) Create a bioswale -- its polygon should be displayed
3) Open network tab and zoom out to level 14. There should be no tile requests for the boundary or polygonal map feature
layers.
4) Go to an instance that doesn't have the `Bioswale` map feature type.
5) Zoom in to level 15. There should be no tile requests for the polygonal map feature …
> Show layer for polygonal map features

- opentreemap/treemap/audit.py
When finding the latest audit of a particular model type and ID there's no need to filter by instance. Model IDs are already unique in their table.
It makes the query 30% faster. Here's a query filtering by instance:
```
otm=# explain analyze select id from treemap_audit where instance_id=20 and model='Plot' and model_id=202165 order by
updated desc;
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=24.96..24.97 rows=7 width=16) (actual time=0.211..0.226 rows=5 loops=1)
Sort Key: updated
Sort Method: quicksort  Memory: 25kB
->  Index Scan using treemap_audit_model_id on treemap_audit  (cost=0.00..24.86 rows=7 width=16) (actual
time=0.034..0.072 rows=5 loops=1)
Index Cond: …
```
> Ignore instance when creating a model hash

- opentreemap/treemap/instance.py
- opentreemap/treemap/udf.py
We were accidentally mutating the DEFAULT_MOBILE_API_FIELDS module-level
variable when handling UDF deletion.
Depending on the order the unit tests were run in, this could cause a
test to fail, and almost certainly could have occurred in production
as well.
> Fix accidental mutation of default api fields.

- opentreemap/treemap/js/src/inlineEditForm.js
We were correctly writing non-field errorss to a global error message
section, but then accidentally overwriting those global errors when
attempting to show inline field errors.
Excluding the global error section when clearing the field errors fixes
this bug.
> Fix issue preventing global errors from being shown.

- opentreemap/api/README.md
Building comprehensive documentation of an API is a large task. This
initial README is not complete, but does mention all of the endpoints used
by the mobile applications. There are some endpoints in api/urls.py that
are not covered in this README that are either broken or out of date and
not used.
The most glaring omission in this initial pass is the lack of a table
describing the datatypes and allowable values for all of the input
parameters and output data.
The Markdown is structured in a format that is compatible with
https://github.com/tripit/slate, which produces output similar to the Stripe
documentation, which I feel is some of the best API documentation
available. https://stripe.com/docs/api
I do not know if adding the Ruby dependencies of tripit/slate is good
for the project. We …
> Initial first draft of public API documentation

- opentreemap/treemap/css/sass/partials/_navbar.scss
- opentreemap/treemap/css/sass/partials/_subheader.scss
- opentreemap/treemap/js/src/buttonEnabler.js
connects #2020 on github
Title (help) text is not shown for disabled buttons. However, we want to
explain why buttons are disabled so the user can take action to enable
them.
The recommended fix for twitter bootstrap tooltips is to wrap disabled
buttons in a div or label. In this case, we are using this technique,
but not activating the bootstrap tooltip. This gives us native title
text instead of tooltip windows. This is advantageous because running
$container.tooltip() is expensive, and with how our code is currently structured,
would have to be done on each map_feature click. The downside is that
bootstrap tooltips look prettier than native title text. This change
could me made easily at a later time.
This commit breaks styling in at least two known places:
* The counts/export/add …
> Wrap disabled buttons in a titled label element

- opentreemap/treemap/js/src/MapManager.js
There is a known Leaflet issue which causes an "afterimage" when going one
zoom level beyond a layer's min/max zoom level.
(https://github.com/Leaflet/Leaflet/issues/1905)
This fix works around the issue.  We should be able to remove this once
we upgrade to Leaflet 1.0, once it is out.
Connects to #2089
> Work around Leaflet afterimage issue.

- opentreemap/treemap/routes.py
- opentreemap/treemap/views/misc.py
I investigated changing our explicit error responses from API views to be JSON instead of plain text strings, but since the existing mobile apps use the textual responses in several places to report errors to the user, I opted to leave them as is.
To test, you will have to change your settings in Django settings to set `DEBUG=False` and `ALLOWED_HOSTS=['localhost']`.
You should see that any URL starting with `/api/` should return JSON for an unhandled error like a 404 or a 500 error, and that other URLs continue to return our custom error pages.
Connects to #2069
> Return JSON for unhandled errors to API views.

- package.json
This version include a fix to a dependency issue that was breaking the bundling of our javascript assets.
https://github.com/bevacqua/dragula/commit/d7342ace10b65dbe45be109139f1d7162e7e3efe
> Upgrade dragula JS dependency

- opentreemap/treemap/js/src/udfcSearch.js
connects #2129 on github
They dynamically generated udfFieldDefId for the given modelName is
enough to build the name.
> Don't require more data attributes than necessary

- test-requirements.txt
Our UI tests suddenly were taking twice as long to run.
The solution was rebooting Jenkins slave OTM01.
But along the way i upgraded Firefox (30 -> 39) and selenium (2.45 -> 2.46)
because of others' experience of slowness
(https://code.google.com/p/selenium/issues/detail?id=8551)
Since the tests work fine I'm committing the change to selenium 2.46.
Connects OpenTreeMap/cloudbuild#174
> Upgrade to latest selenium

- opentreemap/treemap/lib/map_feature.py
connects #2073 on github
the share context was using the same url used to produce the feature,
which is incorrect for the API. Here we explicitly use the url to the
map_feature_detail page in the webapp.
> Fix share link

- opentreemap/opentreemap/urls.py
- opentreemap/stormwater/routes.py
- opentreemap/stormwater/urls.py
- opentreemap/stormwater/views.py
- opentreemap/treemap/js/src/MapManager.js
- opentreemap/treemap/templates/treemap/settings.js
I explored using multiple UTF grids but ran into several issues:
- clicks do not "fall through" to the lower UTF grid
- max/min zoom properties are not respected
Instead, I implemented a WMS-style server backend for determining if a
polygon is present at a given lat/lng.  UTF grids are still used for point
based map features, and no network requests are made if the map does not
support polygonal map features.
Connects to #2114
> Make bioswale polygons on map pages clickable

- opentreemap/treemap/audit.py
Since bulk_create does not send signals, the object_caches for roles
were not invalidated when creating a new role, and the roles page would
incorrectly appear blank.
Connects to #2165
> Fix object_caches issue with creating new FieldPermissions

- opentreemap/treemap/migrations/0001_initial.py
- opentreemap/treemap/migrations/0004_auto_20150720_1523.py
There were two backwards incompatible changes to the Django Abstract User
model, which were not properly captured when recreating initial
migrations for Django 1.8.
Because OTM uses a custom user model, we have to handle the migrations
for this change ourselves.
Connects to #2162
> Fix incorrect initial Django Migrations

- opentreemap/importer/js/src/importsList.js
- opentreemap/treemap/templates/base.html
- Modals in the `endbody` block need to come before the `scripts` block
in order for JS to set up event handlers.
- Fixed importer polling
> Fix a few bugs

- opentreemap/treemap/audit.py
- opentreemap/treemap/css/sass/partials/pages/_admin.scss
- opentreemap/treemap/js/src/editableForm.js
- opentreemap/treemap/js/src/fieldHelpers.js
- opentreemap/treemap/js/src/inlineEditForm.js
- opentreemap/treemap/js/src/simpleEditForm.js
- opentreemap/treemap/udf.py
- Update FieldPermission choices and translate them.
- Split inlineEditForm.js into 2 modules, and add a "simple" version
The simple version is intended to be used for forms that want the
edit/save/cancel behaviour but want to handle form serialization and
error reporting in a custom way.
- Add basic styling for updated roles page
- Fix potential object_caches invalidation issue with field permissions
> Cleanups to Field Permission and Roles

- opentreemap/treemap/lib/perms.py
- opentreemap/treemap/templates/base.html
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templatetags/instance_config.py
- The add resource menu was broken due to using `true` instead of `True`.  Since it should always be enabled, I removed all of the button enabler related attributes.
- Add plot and resource permissions were incorrect for _all_ of the add tree/resource buttons on the site.  I registered the `plot_is_creatable` helper function as a template filter, and switched to using it in several places.
- We were checking plot permissions instead of resource permissions when enabling/disabling buttons for resources.  I added separate helper functions for these, and fixed some typos in other places where they were already being used.
Connects to #2198
> Fix add resource menu

- opentreemap/treemap/templates/treemap/map-browse-trees.html
I have changed the first header on the sidebar of the browse trees mode of the map page to "Details" instead of the overly specific "Tree Details." We are showing the details for green infrastructure features in this same area.
Tree selected 
Stormwater feature selected
The eco benefits being shown are for the entire map, and are always shown. Single-tree benefits are correctly removed from the sidebar when switching from displaying a tree to displaying a stormwater feature.
Connects to #2184
> Genericize the map page browse mode detail header

- opentreemap/treemap/css/sass/partials/pages/_admin.scss
Prevents the content at the bottom of the page from being obscured by
the footer.
> Increase margin on management page content sections.

- opentreemap/treemap/lib/udf.py
- opentreemap/treemap/migrations/0007_auto_20150902_1534.py
- opentreemap/treemap/udf.py
- Validate the choices list for multichoice UDFs
- Allow UDFs with the same name if they are on different models
- Add a uniqueness constraint to UserDefinedFieldDefinition
> Cleanup some cruft with UDFs

- opentreemap/api/decorators.py
- opentreemap/api/instance.py
- opentreemap/api/tests.py
- opentreemap/treemap/udf.py
Our mobile apps do not currently support multichoice fields.
In order to prevent crashes, we need to hide multichoice fields from API
version 3 and below.
When we upgrade the mobile apps to support multichoice fields, we will
switch them from API version 3 to API version 4
Connects to #2235
> Increment API to version 4 and hide multichoice fields from older APIs

- .travis.yml
- circle.yml
We no longer need to do this now that we've switched to using Django
migrations.
> Stop running syncdb for Travis and Circle CI.

- dev-requirements.txt
- requirements.txt
Gunicorn got the reload option in version 19, which is handy.
The Django Debug Toolbar got Django 1.8 support in 1.3, and it wouldn't
work until I upgraded it.
It _looks_ like Gunicorn got a big version increase, but I think what happened is they decided to drop the leading `0.`
> Update gunicorn and django debug toolbar

- opentreemap/treemap/instance.py
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templates/treemap/partials/eco_benefits.html
- opentreemap/treemap/views/tree.py
Determining if an instance has resources is now a poor fit for
determining support for resources because it imposes an inception
problem. An instance must support resources for a resource to be added,
but a resource must be added for an instance to support
resources. Renaming this function will make it semantically clearer to
use other criteria for testing resource support.
> Rename 'supports_resource' -> 'has_resources'

- opentreemap/otm_comments/js/src/moderation.js
Because the Bacon.js stream was change from using onValue to using flatMap
to support further usage, it stopped working when it was *not* used,
due to Bacon's lazy evaluation.
Adding a noop onValue fixes the issue.
Connects to #2247
> Fix comment moderation UI tests.

- .travis.yml
- Gruntfile.js
- package.json
- testem.json
The `before_tests` script specified in our testem config was failing
since Grunt needs to run in the virtualenv in order to run collectstatic.
When this script fails, testem just hangs forever for some reason.
I fixed the issue by adding a new Grunt task which just runs the `js` and
`css` tasks (which used to be the default Grunt task).
> Fix running JS tests via testem CI.

- opentreemap/treemap/audit.py
connects #2248 on github
As was the case with bb11caad41f9b2feb1da8c387f9ddef6be5f90aa, unit
field lookup was failing for case-sensitivity reasons on multi-word
models. This is because we were calling `.lower()` on a camel-case
string. In this case, we were producing 'rainbarrel' when we wanted 'rainBarrel'.
> Fix audit unit format for multi-word names

- opentreemap/importer/templates/importer/partials/imports.html
The old links are no longer valid. Using Django static file URLs gives us flexibility on how, and from where, the help documentation and templates are served.
> Link to static importer help files

- opentreemap/importer/models/trees.py
Sorting all the trees by distance from a point gets very processor intensive when an instance has a lot of trees and dramatically slows down the import. Adding a where clause that filters by a small bounding box speeds up the query by up to three orders of magnitude on an instance with 500,000 plots and runs in 1ms on an brand new instance with no plots.
This is an example of the query produced by the Django ORM, and the
EXPLAIN ANALYZE output for a similar query.
```
SELECT "treemap_mapfeature"."id",
"treemap_mapfeature"."udfs",
"treemap_mapfeature"."instance_id",
"treemap_mapfeature"."the_geom_webmercator",
"treemap_mapfeature"."address_street",
"treemap_mapfeature"."address_city",
"treemap_mapfeature"."address_zip",
"treemap_mapfeature"."readonly",
"treemap_mapfeature"."updated_at", …
```
> Use a bbox filter for bulk import proximity checking

- opentreemap/stormwater/models.py
- opentreemap/treemap/ecobenefits.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templatetags/util.py
It was originally planned to dynamically generate plural terminology if
it was absent but it was then decided to be more complex than
necessary. Plural terminology was supposed to be added in when that
decision was made, but fell through for a few models.
> Add missing terminology

- opentreemap/importer/tasks.py
- opentreemap/opentreemap/settings/default_settings.py
Based on the timing information reported in OpenTreeMap/otm-core#2267
we expect a single batch of 250 trees running on a single worker to take
approximately 1 minute per batch, once the distance validation refactor
in that PR is integrated.
Based on this, I reduced the batch size to 85 which should take around 20
seconds, and I added a rate limit of 1 batch per minute.  Since we have
two Celery workers in production, this should provide a combined rate
limit of 2 batches/minute (since rate limits affect workers individually),
with an expected "quiet period" of 20 seconds per minute.
Since our production environment differs significantly from our
development environments, we should obviously test these assumptions
and timings after this change is deployed to production.
Connects to #2258
> Adds rate limiting to importer commit tasks to prevent database overutilization

- requirements.txt
1.8.3 and 1.8.4 include security fixes.
https://docs.djangoproject.com/en/1.8/releases/1.8.3/
https://docs.djangoproject.com/en/1.8/releases/1.8.4/
Connects to #2283
> Upgrade from django 1.8.2 to 1.8.4

- opentreemap/importer/js/src/importsList.js
- opentreemap/importer/views.py
This fixes the bug where a completed import would disappear because the active import table refreshed, but the finished import table did not.
I fixed the issue by keeping track of which tables are linked together, and the current state of the primary tables, and then refreshing the linked table when the primary table transitions out of the refreshing state.
> Refresh finished import table on completion

- opentreemap/opentreemap/settings/default_settings.py
This reverts commit 67a12d361da2631b7162df7d34c0c765bfeadab8.
Some existing deployment environments currently depend on the default value of `django.core.mail.backends.smtp.EmailBackend`
> Revert "Make the default email backend be console-based"

- Gruntfile.js
Django's `collectstatic` command uses file modification time to determine
if it should overwrite a file.  Unfortunately inside VirtualBox shared
folder file modification times are often inconsistent, and this can lead
to newly updated files not being collected, especially when running
`grunt watch`.
Adding `-c` to the command tells Django to always overwrite every file,
which fixes the problem, though it does add a slight amount of overhead.
> Fix collectstatic sometimes missing updated files.

- opentreemap/treemap/ecocache.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/tests/test_ecobenefits.py
- opentreemap/treemap/views/tree.py
Removes the need to pass `compute_value` to get_cached_plot_count and
adds a helper method to Instance to get the total number of plots from the
cache.
> Refactor get_cached_plot_count to make it easier to use.

- opentreemap/treemap/instance.py
- opentreemap/treemap/migrations/0010_eliminate_warnings_fields_w340.py
No need for `null=True` on many-to-many fields `Instance.users` and `Instance.boundaries`
Connects #2142
> Eliminate `fields.W340` warnings

- opentreemap/treemap/css/sass/partials/pages/_admin.scss
- opentreemap/treemap/js/src/inlineEditForm.js
- opentreemap/treemap/templates/treemap/partials/form_buttons.html
* Clicking "Save" disables "Save" and "Cancel" and shows spinner (if present)
* Pages configuring an inline edit form may omit options by following conventions
* New template partial allows DRY buttons
> Improvements to inline edit forms

- opentreemap/importer/js/src/status.js
- opentreemap/importer/models/trees.py
- opentreemap/importer/views.py
There was a "hack" in place to support changing the species values in a
tree import to an existing species. When updating a species, the 'species'
column was updated to reflect the PK of a species in the database, and
then later during validation the species related fields (including the one
which held the PK) would be overwritten with the correct info from the
database if the 'species' field was a number
Because it piggybacked the species id in the species name column of the
ImportRow object, there were conflicts when a number was uploaded as the
value for the species column in the original CSV, and no error would be
reported to the user.
I cleaned up the work-around significantly, by sending the species id in
a different field name, and fetching the species information from the DB
as …
> Fix error validation for species columns with numeric values.

- opentreemap/treemap/js/src/inlineEditForm.js
This allows code outside the context of the inlineEditForm
to serialize the state of the inlineEditForm and push validation errors into the inlineEditForm for display. 
The use case driving this change is wanting to "preview" the results of a change, which could return the same server-side validation errors that the actual save operation would generate.
Another potential use case would be adding client side validations that could make use of the existing error display plumbing.
> Expose inlineEditForm functions

- opentreemap/treemap/templates/treemap/field/species_typeahead.html
- opentreemap/treemap/templates/treemap/partials/collection_udf_row.html
- opentreemap/treemap/templates/treemap/partials/map_feature_accordion.html
- opentreemap/treemap/templates/treemap/partials/photo.html
- opentreemap/treemap/templates/treemap/recent_user_edits.html
- opentreemap/treemap/templates/treemap/resource_detail.html
I went through the source and grepped for `'(id|pk) ?}}'` and added an
`unlocalize` filter to everywhere it seemed appropriate.  I'm sure there
are other places where the template variables are named differently that
I've missed, but this should prevent a slew of bugs waiting to happen.
> Add the unlocalize template filter to PKs used in Django templates.

- opentreemap/treemap/audit.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templatetags/util.py
- opentreemap/treemap/tests/test_templatetags.py
- opentreemap/treemap/units.py
Also adds a helper method to get the singular terminology name more
easily, and improves the display_name template filter to take an
(optional) instance parameter to use to look up the display name.
> Correctly use model display names on the Edits page.

- opentreemap/treemap/views/tree.py
This ensures that changing the map features for the instance invalidates
the browser cached resource counts.
Connects to #2303
> Include the instance map feature types in eco etags.

- opentreemap/treemap/css/sass/partials/pages/_admin.scss
Fixes issue reported on add-ons repo https://github.com/OpenTreeMap/otm-addons/issues/843
Firefox now has correct padding-bottom. Every other browser will have slightly bigger padding-bottom due to this *fix*. It still looks good though
> fixed bottom padding on admin page overflows

- opentreemap/treemap/lib/object_caches.py
Prevents caching issues where related objects were saved before the Instance
object was saved, causing the adjuncts_timestamp to be reverted back to the old
value.
As an example of what this prevents, consider the following code snippet:
```
role = Role.objects.all()[0]  # role.instance.adjuncts_timestamp is 1
role.perm_level = 2
role.save()  # This triggers `increment_adjuncts_timestamp`, increasing it to 2
role.instance.save()  # This reverts the `adjuncts_timestamp` to 1
```
Connects to OpenTreeMap/otm-addons#891
Connects to OpenTreeMap/otm-addons#890
> Refresh Instances after incrementing the adjuncts_timestamp

- opentreemap/treemap/lib/object_caches.py
Commit 6222295e fixed a problem with accidentally saving stale
adjuncts_timestamp values, but @RickMohr pointed out that it could cause
changes to be missed.  Only refreshing the timestamp but keeping other data in
the instance is a bit safer while still preventing the original problem.
> Improve timestamp refreshing in object_caches.

- opentreemap/treemap/js/src/editTreeDetailsMode.js
Also, while creating `dom`, use `dom.form` instead of `formSelector`
Connects #2016
> Hide ecobenefits in quick-edit mode

- opentreemap/opentreemap/util.py
- opentreemap/otm_comments/js/src/moderation.js
- opentreemap/otm_comments/views.py
- opentreemap/treemap/css/sass/partials/pages/_admin.scss
- opentreemap/treemap/js/src/baconUtils.js
- opentreemap/treemap/js/src/photoReview.js
- opentreemap/treemap/routes.py
- opentreemap/treemap/templates/treemap/partials/photo.html
- opentreemap/treemap/templates/treemap/partials/photo_review.html
- opentreemap/treemap/urls.py
- opentreemap/treemap/views/photo.py
~~Based on top of https://github.com/OpenTreeMap/otm-core/pull/2334, so commits  8f6bd7b and 799041d are from that PR.~~
- Redesigns the styling and layout of the photo review page.  The page is now in a table layout instead of a grid layout, matching the comment moderation page.
- Refactors photo review pagination to work similarly to comment moderation
- Fixes a few bugs related to photo review, since the code causing them was refactored
- Records query parameters on comment and photo moderation pages when pagination/filter buttons are clicked.
Connects to OpenTreeMap/otm-addons#541
Connects to OpenTreeMap/otm-addons#828
Connects to #2156
> Implement Photo review redesign

- opentreemap/treemap/js/src/buttonEnabler.js
07c776c introduced an error by making the `config` argument to `buttonEnabler` optional and eliminating the top-level `config` variable. This reverts the first change, but retains the second so the usage of `config` is clearer.
> Require config argument to button enabler once again

- opentreemap/exporter/tasks.py
- opentreemap/treemap/js/src/export.js
- requirements.txt
* Query `Plot` instead of `Tree`
* Adjust CSV headers to remain tree-centric instead of becoming plot-centric
* Use latest version of `django-queryset-csv` for necessary bug fix
Also fixes a longstanding bug where exports ignored "Display Filters"
Connects #1990
> Include empty plots in tree exports

- opentreemap/stormwater/migrations/0005_help_text_to_verbose_name.py
- opentreemap/stormwater/models.py
- opentreemap/treemap/migrations/0012_help_text_to_verbose_name.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/tests/test_templatetags.py
`verbose_name` is the more correct Django-ism to use for a field name.
Also removes a few errant uses of Plot in favor of Planting Site
> Switch from 'help_text' to 'verbose_name' for field name defaults.

- opentreemap/importer/models/species.py
- opentreemap/importer/tasks.py
- opentreemap/importer/views.py
It was slow because:
* It used a large `Species.objects.` query
* `Species` subclasses `Auditable`, so its constructor calls `populate_previous_state`, which fetches UDFs
* That hits the object cache, which requires `instance.adjunct_timestamp`
* So `species.instance` was fetched from the database
* `select_related` and `prefetch_related` didn't help
At @maurizi's suggestion I rewrote it to use a values queryset, which was easy because
* Changing `SpeciesImportRow.SPECIES_MAP` to an `OrderedDict` made it easy to get the right field order
* The header row comes out right because `django-queryset-csv` removes underscores
> Faster species export

- opentreemap/registration_backend/views.py
- opentreemap/treemap/templates/registration/activation_email.txt
Passes the request object into the activation email template, so it can
be used to template the activation link with either HTTP or HTTPS,
depending on whether the signup page was accessed over HTTPS.
Connects to https://github.com/OpenTreeMap/otm-cloud/issues/44
> Include correct protocol in activation email template.

- opentreemap/treemap/instance.py
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/tests/test_models.py
- opentreemap/treemap/util.py
- Removes search_type from the advanced search configuration dict
Instead, the search_type is inferred based on the underlying field type when
displaying fields.
> Make advanced search work with config from DB

- opentreemap/treemap/templates/treemap/user.html
We create a compresseed 85x85 pixel thumbnail for uploaded user photos,
which is intended to be used for the small profile photo in the header.
This is too small and shows compression artifacts when used on the user
profile page in a 195x195 pixel image.
Switching to the full size image for the user profile page fixes the issue.
Connects to OpenTreeMap/otm-addons#876
> Switch from thumbnail to full-size image for user profile photo.

- opentreemap/treemap/lib/hide_at_zoom.py
- opentreemap/treemap/management/commands/recompute_hide_at_zoom.py
- opentreemap/treemap/migrations/0013_mapfeature_hide_at_zoom.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/test_hide_at_zoom.py
- opentreemap/treemap/views/map_feature.py
When viewing a zoomed-out tree map, multiple plots in a local area are rendered on top of one another. We set `MapFeature.hide_at_zoom` so the tiler can render just one plot in such cases, speeding up tile creation for maps with many plots.
The plan is to recompute `hide_at_zoom` nightly. After a large tree import, tiling could be somewhat slower until the next day.
To test:
1. Run migrations
2. Run management command to set `hide_at_zoom` for all plots in a large instance, e.g. `manage.py recompute_hide_at_zoom latreemap`. (It takes several minutes to complete.)
3. Load the tree map (with dev tools open to disable cacheing) and click around
4. To compare performance, do an advanced search of "Last Updated" from 5 years ago to now. (When a filter is passed to the tiler the optimizations …
> Support for tiler to render fewer plots on large maps

- opentreemap/treemap/js/src/layers.js
This change was reverted in otm-tiler to support legacy clients, and
needs to be reflected here as well.
Connects to https://github.com/OpenTreeMap/otm-tiler/issues/96
> Revert change to tile URL in 0c56150.

- opentreemap/treemap/css/sass/partials/pages/_treedetails.scss
- opentreemap/treemap/js/src/addMapFeature.js
- opentreemap/treemap/js/src/streetView.js
I attempted to hide the full screen button but as far as I can tell
there is no option to do so.
There is also no way to minimize the address info box, only hide it or
change its position, so I opted to always hide it.
Connects to #2364
> Hide address and panning controls on street view.

- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
- opentreemap/importer/util.py
- opentreemap/treemap/udf.py
When importing a tree CSV with date and/or multichoice UDF columns, data in an invalid format would trigger the throwing of an `ValueError` which crashed the celery validation task. In this commit I continue the pattern of other UDF validations by catching the `ValueError` and converting it to a `ValidationError`, which is caught and logged by thevalidation task.
I wanted to add some UDF validation tests, but the TreeValidationTest class was already relatively long. I split the setUp and helper function into a base class that could be shared with multiple tree validation test classes.
Connects to #2380
Connects to #2383
> Handle import parsing of UDF dates and multichoice

- opentreemap/treemap/audit.py
Because we were not filtering by both model and field name, but just field
name, `UserDefinedFieldDefinition.clean_value` was being given the
`datatype_dict` of Bioswale.Perennial Plants for an edit on the
Perennial Plants field of a Rain Garden.
Connects to #2366
> Fix bug in formatting edit values for clashing custom field names.

- opentreemap/importer/tests.py
- opentreemap/treemap/tests/__init__.py
`ecoservice_not_running` was always reporting that the eco-service was not running, so tests using it never ran.
* Fix `ecoservice_not_running`
* Fix `ITreeCommitTest._assert_overrides` so that species with merge conflicts are committed
Connects #2395
> Fix species importer i-Tree override tests

- opentreemap/treemap/css/sass/partials/_subheader.scss
- opentreemap/treemap/js/src/searchBar.js
- opentreemap/treemap/templates/instance_base.html
* Highlight advanced search "Tree Care" dropdown when stewardship search active
* Update field disabler now that "empty plot" display filter works again
Connects #2400
> Advanced search tweaks

- opentreemap/otm_comments/uitests.py
- opentreemap/treemap/tests/ui/__init__.py
- test-requirements.txt
Running UI tests with Firefox 43 (the latest version as of this commit) and selenium 2.46.0 generated errors on every test.
~~This resolved the errors on every test, but still results in failing tests.~~
43fce3a fixed the failing tests by making sure elements to be clicked are on screen
Connects to #2397
> Upgrade to selenium 2.48.0

- opentreemap/treemap/css/sass/partials/pages/_admin.scss
Fix for https://github.com/OpenTreeMap/otm-addons/issues/946
> fix add-ons issue 946. highlight background color on new roles

- opentreemap/api/tests.py
- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
- opentreemap/treemap/migrations/0014_change_empty_multichoice_values.py
- opentreemap/treemap/search_fields.py
- opentreemap/treemap/templates/treemap/field/inputs.html
- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/udf.py
* Fields from all models are shown in the "Missing Data" category, so prefix the label with the model name.
* In the `field/inputs.html` template, move the test for checkbox fields to the top. Otherwise the advanced search "Missing" category shows dropdowns for "choice" fields instead of check boxes.
* When creating ID's for advanced search fields, convert spaces to underscores
> Support configurable "Missing Data" advanced search fields

- opentreemap/api/tests.py
- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
- opentreemap/treemap/migrations/0014_change_empty_multichoice_values.py
- opentreemap/treemap/search_fields.py
- opentreemap/treemap/templates/treemap/field/inputs.html
- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/udf.py
* Fields from all models are shown in the "Missing Data" category, so prefix the label with the model name.
* In the `field/inputs.html` template, move the test for checkbox fields to the top. Otherwise the advanced search "Missing" category shows dropdowns for "choice" fields instead of check boxes.
* When creating ID's for advanced search fields, convert spaces to underscores
See #2406 for discussion
> Configure missing data search fields

- opentreemap/treemap/models.py
- opentreemap/treemap/tests/base.py
- opentreemap/treemap/tests/test_models.py
Allowing physically impossible measurement values is bad for data quality, and impossibly large diameter values cause problem with eco benefit calculations.
You should not be able to enter negative values for tree height, tree diameter, tree canopy height, plot width or plot length.
If no species is selected, you should not be able to enter tree height > 800 ft or tree diameter > 200 in. On a map using the metric system, you should not be able to enter a tree height > 243.84 m or a tree diameter > 508 cm.
Adjusting the max allowable height and diameter of a `Species` through the Django console will and assigning that species to a tree should override the maximum values use for validation.
Note: Empty quick edit error messages should be addressed by #2414. There are validation error …
> Validate nullable numeric plot and tree fields

- opentreemap/treemap/js/src/imageUploadPanel.js
There is an open issue in the version of Bootstrap we are using that causes
a 14-17px padding to be added to the body element, in an attempt to hide
the scrollbar of the page when modals are open.
https://github.com/twbs/bootstrap/issues/14040
As a side effect of this, opening a modal while another modal is still
closing (which is documented by Bootstrap as something to avoid) causes
this padding to remain in effect in even when the modal is closed.
I fixed that issue by ensuring that we wait until the upload modal has
closed before attempting to open the social media modal.
We may have to wait for a newer version of Bootstrap to fix the
main issue of unnecessarily adding padding when modals are open, or we may
be able to fix it with CSS rules.
Connects to #2427
> Fix style issues caused when closing social media sharing modal

- opentreemap/importer/templates/importer/partials/import_table.html
- opentreemap/importer/views.py
-  Always set importer status to canceled when calling the cancel endpoint
On some occasions we cannot get the Celery task when attempting to call
`GroupResult.restore()`, which caused attempts to call `.revoke()` to fail,
which caused the change to the Import status to be rolled back.
We explicitly check the return of `.restore()` before attempting to call
`revoke()`, which prevents the transaction rollback from reverting the changed
status.
- Do not show the importer view link until it has started verification …
Connects to OpenTreeMap/otm-addons#990
Connects to OpenTreeMap/otm-addons#991
> Importer bug fixes

- opentreemap/treemap/css/sass/partials/_error.scss
- opentreemap/treemap/templates/treemap/partials/map_feature_accordion.html
- Empty error boxes were appearing - fixed via CSS rule
- Errors due to out of bounds plots were not appearing, fixed by adding
an element to display mapFeature.geom errors.
Connects to #2393
> Fix error handling on the tree details quick edit

- opentreemap/otm_comments/templates/otm_comments/partials/moderation_row.html
- opentreemap/treemap/js/src/batchModeration.js
[This is a new version of #2440 targeted at `develop`]
The single action selector was including the anchor tag for "View Details" on the photo moderation page, which should be a plan request rather than an AJAX request that replaces the content of the page with the response.
The links on the photo moderation page already had a class attribute set correctly. I added `class="action"` to the links on the comment moderation page so that they would still trigger AJAX requests when clicked.
Add a bunch of photos and comments then make sure all the moderation action links work correctly. "View Detail" should be the only anchor that works like a normal link, the rest should make AJAX calls.
----
Connects to OpenTreeMap/otm-addons#1030
> Make batch moderation selector more specific

- opentreemap/treemap/templates/treemap/partials/advanced_search/missing.html
CSS class `field-group-message` has `display: none` because most such messages
are hidden by default. This one is always shown, so override with `display: block`.
Connects #2449
> Restore missing message

- .travis.yml
- dev-requirements.txt
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/images.py
- opentreemap/treemap/tests/test_images.py
- opentreemap/treemap/tests/test_views.py
- requirements.txt
- test-requirements.txt
- travis-requirements.txt
The aim behind doing this is to take advantage of the requires.io service, which has been sending us pull requests whenever a new version of one of our dependencies has been updated.
I opted to defer some updates by using the special `rq.filter` comment recognized by requires.io.
- I left updated Django to the latest 1.8 release, but used a filter to stay on 1.8 instead of the latest, which is 1.9
- I kept us at our current versions of `pep8` and `flake8`, because the latest versions have new linting rules which our codebase does not follow.  We need to fix our code lint at the same time that we update these (see https://github.com/OpenTreeMap/otm-core/issues/2443).
- I left `libsass` using a git version even though the release we are pinned to has been released on PyPi, because we need …
> Update python dependencies to the latest versions

- opentreemap/opentreemap/util.py
- opentreemap/otm_comments/templates/otm_comments/partials/moderation.html
- opentreemap/otm_comments/views.py
- opentreemap/treemap/lib/page_of_items.py
- opentreemap/treemap/templates/treemap/partials/filter_dropdown.html
- opentreemap/treemap/templates/treemap/partials/photo_review.html
- opentreemap/treemap/views/photo.py
* Template `treemap/partials/filter_dropdown.html` creates a filter dropdown
* Helper `treemap/lib/page_of_items/make_filter_context` sets up context for the template
* Enhance `UrlParms.url()` to take optional param overrides, allowing easy creation of a URL for each filter option.
* Change the comment and photo moderation pages to use the new scheme.
> Reusable components for filters on "list of items" pages

- opentreemap/api/instance.py
- opentreemap/api/plots.py
We are adding support to the mobile apps for multichoice fields, but are not
yet adding support for universal_rev_hash, so I am leaving multichoice fields
available in v4 but moving universal_rev_hash to only be supported in v5 and
above.
> Move universal_rev_hash from APIv4 to APIv5

- opentreemap/geocode/views.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/css/sass/partials/pages/_createmap.scss
- opentreemap/treemap/css/sass/partials/pages/_map.scss
- opentreemap/treemap/js/shim/bloodhound.js
- opentreemap/treemap/js/shim/typeahead.jquery.js
- opentreemap/treemap/js/src/addMapFeature.js
- opentreemap/treemap/js/src/geocoder.js
- opentreemap/treemap/js/src/otmTypeahead.js
- opentreemap/treemap/js/src/searchBar.js
- opentreemap/treemap/templates/instance_base.html
- Upgrades to typeahead.js 0.11.1 (the latest).
- Use ESRI suggest endpoint to provide autocomplete of addresses
This removes our client-side geocoder in favor of our (unused) server-side
geocode endpoint using python-omgeo.
Since the suggest endpoint is using the instance's extent as a viewbox, I
was able to remove the viewbox code from the geocode endpoint, as results
will be matched up with the 'magicKey' provided by ESRI suggestion results.
The autocompletion has been wired into both the location search in the
search bar as well as the location search when adding a tree.
The styling also had be fixed up a bit since we now have typeaheads in
places that used to just have a normal input.
Connects to #948
> Use ESRI suggest for autocompleting geocoded addresses

- opentreemap/opentreemap/context_processors.py
- opentreemap/treemap/js/src/editableForm.js
- opentreemap/treemap/migrations/0015_instanceuser_last_seen.py
- opentreemap/treemap/migrations/0018_merge.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/field/readonly.html
- opentreemap/treemap/templatetags/form_extras.py
* Add and maintain `InstanceUser.last_seen` date
* Add template for showing read-only fields in an inline edit form
* Simplify code in `form_extras.py`
* Use "Yes/No" instead of "True/False" for default boolean display value
This matches the server-side display values used in `form_extras.py`
* Make the display value of a choice field the choice's display value
Connects OpenTreeMap/otm-addons#1035
> Support for super admin instance details

- opentreemap/treemap/ecobackend.py
- opentreemap/treemap/ecobenefits.py
- opentreemap/treemap/ecocache.py
- opentreemap/treemap/udf.py
An exception was being thrown when setting the value of a text or choice UDF if the value contained non-ASCII characters. This was caused by indiscriminately using `str()` to coerce values to strings.
Advanced searches that included non-ASCII characters in text or choice fields were also raising exceptions. The changes in this PR ensure that values are always encoded and decoded properly.
Use a test instance with the customization module enabled.
Add a text UDF and a choice UDF to the test instance. Ensure that the choice UDF has choices that contain non-ASCII characters like ≥. Add these fields to the search configuration so that they are available for advanced searching.
Add trees to instance and set UDF values that contain non-ASCII characters. Verify that the non-ASCII characters are …
> Handle non-ASCII characters in text and choice UDF fields

- opentreemap/importer/tasks.py
- opentreemap/opentreemap/settings/default_settings.py
addresses #2451 on github
This changeset introduces rate limiting for validation and provides a coarse starting point for rate limiting values we will want to use in production. These values will be revisited after testing in our staging environment.
> Add coarse values to importer rate limiting

- opentreemap/importer/tasks.py
- opentreemap/opentreemap/settings/default_settings.py
Reverts OpenTreeMap/otm-core#2483
We decided that it would be simpler to leave these new values off master until they've been tested against a production-like deployment stack. We also seek to create a release branch without these new values and reverting these commits makes this simpler.
> Revert "Add coarse values to importer rate limiting"

- opentreemap/treemap/js/src/streetView.js
Using camera location of Street View image along with tree location, set panorama heading so you're looking at the tree.
To test:
* Find a place you're familiar with, that has trees, on some tree map
* Select a tree and "View All Details" -- Street View should be pointing at the tree
* Click another nearby tree -- Street View should point to it
Or:
* Find a place you're familiar with, that has trees, on some tree map
* Click "Add a Tree"
* Place the marker (Street View appears)
* Move the marker to different places on the street -- Street View should point to it
> Make Street View show what you want to see

- opentreemap/treemap/js/src/addMapFeature.js
- opentreemap/treemap/js/src/addTreeMode.js
- opentreemap/treemap/js/src/otmTypeahead.js
- opentreemap/treemap/js/src/treeMapModes.js
Fixes an issue where when selecting a species or address after having
already added a tree, the only results shown would be for the tree
previously added.
By explicitly clearing the typeahead when deactivating add tree mode or
clearing edit controls, the problem is fixed.
Connects to #1025
> Clear typeaheads when switching out of add tree mode

- opentreemap/opentreemap/celery.py
- opentreemap/opentreemap/settings/default_settings.py
- requirements.txt
Piggybacking on the existing Celery support, start emitting a variety of metrics for the following lifecycle events by registering with their signals:
- `on_task_sent` (counter)
- `on_task_prerun` (counter, timer)
- `on_task_postrun` (counter, timer)
- `on_task_failure` (counter)
See also: https://github.com/django-statsd/django-statsd/blob/0.3.16/django_statsd/celery.py
---
**Testing**
Provision the `app` virtual machine and then set the following two settings in `/etc/statsite/statsite.cfg`:
```
flush_interval = 10
stream_cmd = /usr/bin/logger
```
Finally, restart the `statsite` service and tail `syslog` for relevant metrics when performing some operation that exercises Celery:
```bash
vagrant@app:~$ sudo restart statsite
vagrant@app:~$ sudo tail -f /var/log/syslog | grep logger
Feb 10 …
```
> Add support for emitting Celery metrics via signals

- opentreemap/opentreemap/util.py
- opentreemap/treemap/ecobackend.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/templates/treemap/partials/plot_eco.html
Failing to calculate the ecobenefits for a tree for reasons like the species not having a i-Tree code defined for a given i-Tree region is a regular occurrence in production. This commit attempts to makes it easier for a log aggregator to combine similar failures and reduces the severity level of commonplace failures to "info" so they do not drown out more concerning warning and error messages.
Unexpected failures not related to the species and region configuration are now logged as errors because we want to see and address those issues quickly.
When looking at Rollbar, make sure you turn on all event types and sources so that info messages from the development environment appear in the list
Because this feature is all about how the text messages returned from the ecoservice are converted …
> Revise eco error message logging

- opentreemap/treemap/js/src/udfcSearch.js
The advanced search UI was allowing the selection of a date range for stewardship/alerts without selecting a type of either stewardship or alert. We don't support searching across collection UDF types, so this resulted in the code generating invalid filter query strings.
This commit addresses the issue by following the existing patterns in `udfcSearch.js` and disabling the date fields until both a model and a CUDF type have been selected.
The date fields at the end of the "Tree Care" section of the advanced search bar should be disabled until values have been selected from the first two dropdowns.
---
Connects to #2497
> Conditionally disable collection UDF date search fields

- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/MapManager.js
- opentreemap/treemap/js/src/boundarySelect.js
- opentreemap/treemap/js/src/layers.js
- opentreemap/treemap/migrations/0022_add_esri_basemap_type_choice.py
- opentreemap/treemap/migrations/0023_merge.py
- package.json
`esri-leaflet` makes it easy.
But note that including `esri-leaflet` increases our JS download by 56K (6%). Once we switch to Leaflet 1.0 we can reduce that greatly using https://github.com/esri/esri-leaflet-bundler to grab just the basemap layer code.
For the default basemap I chose ESRI "Topographic" because i thought it looked better for a treemap than "Streets".
Google:
ESRI Streets:
ESRI Topographic:
Change your favorite instance to use ESRI basemaps via the Django shell:
```
manage.py shell_plus
i = Instance.objects.get(url_name='...')
i.basemap_type = 'esri'
i.save()
```
Connects OpenTreeMap/otm-addons#1079
> Support ESRI basemaps

- opentreemap/importer/models/species.py
Improves all cases in which these values aren't used
> Lazily cache itree codes

- opentreemap/importer/models/species.py
- opentreemap/importer/models/trees.py
- opentreemap/importer/tasks.py
connects #2500 on github
These two features together lead to a large increase in task runtime in
cases where multiple tasks were running in parallel. This is because
each task would hold a transaction with edits to one import_event record
for the entire life of the task. The result is that each task would have
to wait until a sibling task finishes its transaction. We were seeing
queries in excess of ten seconds as a result. By scoping the transaction to just the
length of the row edits, queries from other tasks need only block as long as it takes a
task to edit each row.
Additionally, the heartbeat was being run once per row (85 times per
task) when once per task is perfectly adequate.
It is suspected, but not confirmed, that the heartbeat is the particular
aspect of the row edit that was …
> Reduce transaction scope and heartbeat frequency

- opentreemap/treemap/search_fields.py
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/tests/test_search_fields.py
We now have 3 cases for whether a choice/multichoice field should offer a blank choice:
* Always -- search fields on the web
* Never -- search fields on mobile
* Choice fields but not multichoice fields -- detail page fields
Connects #2506
Testing: verify that the 3 cases above work as expected
> Mobile apps shouldn't show a blank choice for search fields

- opentreemap/opentreemap/settings/default_settings.py
Intended to allow tasks that originate with one stack to be completed by that
stack, to make background tasks more resilient to code changes.
Connects to OpenTreeMap/otm-cloud#177
To test, I applied this diff to the `otm-cloud` Vagrantfile to create separate VMs each with their own celery worker.
```diff
diff --git a/Vagrantfile b/Vagrantfile
index 0b52b75..357cf2e 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -12,7 +12,7 @@ if ["up", "provision", "status"].include?(ARGV.first)
end
ANSIBLE_GROUPS = {
-  "app-servers" => [ "app" ],
+  "app-servers" => [ "app", "appcopy" ],
"services" => [ "services" ],
"modeling" => [ "modeling" ],
"monitoring-servers" => [ "services" ],
@@ -138,6 +138,33 @@ Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
end
end
+  config.vm.define "appcopy" do …
```
> Create celery queues for each stack color

- opentreemap/treemap/js/src/urlState.js
When we updated `urlState.HistoryApi` to use the browser `History` API instead of `native.history.js` the changes were incomplete (https://github.com/OpenTreeMap/otm-core/pull/2435). The latter called its `onStateChange` callback for any change to the URL -- push, replace, or pop. The former has only a hook for pop.
The fix is to call the `onStateChange` callback ourselves when pushing or replacing URL state.
Connects OpenTreeMap/otm-addons#1114
> Push URL state to app when state is pushed or replaced, not just when popped

- opentreemap/exporter/tasks.py
- opentreemap/exporter/tests.py
- opentreemap/importer/fields.py
- opentreemap/importer/migrations/0005_add_import_event_schema_version.py
- opentreemap/importer/models/base.py
- opentreemap/importer/models/species.py
- opentreemap/importer/models/trees.py
- opentreemap/importer/routes.py
- opentreemap/importer/templates/importer/partials/imports.html
- opentreemap/importer/tests.py
- opentreemap/importer/urls.py
- opentreemap/importer/views.py
- opentreemap/treemap/migrations/0024_add_species_verbose_names.py
- opentreemap/treemap/models.py
Connects #2531
If using `debugcelery.sh` you may need https://github.com/OpenTreeMap/otm-cloud/pull/188
Testing:
0. Run migrations
1. Go to your `latreemap` 
1. Go to the "Bulk Uploader" page. Imports with status "Verification Complete" (both tree and species) should:
* be in the "Finished Imports" section
* have no "Export" link
* have no "Add to Tree Map" link when you click "View"
2. Download the template for trees and for species. The CSV column headers should:
* be in a logical order
* be capitalized, with spaces separating words
* contain custom fields (but not Stewardship), prefixed with either "Planting Site:" or "Tree:"
4. Test importing a tree export:
* Export all trees in the "West Whittier-Los Nietos" neighborhood (80 trees, 82 planting sites)
* The CSV column headers should …
> Unify CSV columns

- opentreemap/importer/tasks.py
- opentreemap/importer/views.py
Also strip when reading headers from DB since unstripped ones were saved in the past
Connects #2532
> On import, strip leading and trailing blanks from headers

- opentreemap/importer/models/trees.py
Previously when validating proximity we ignored `plot_ids_from_this_import`.
(That code was added by @maurizi when we first brought in the OTM importer,
https://github.com/OpenTreeMap/otm-core/commit/2665ec61f06803a029983010ff165689de56a154).
I'm guessing we didn't want to reject trees from somebody's inventory which happened to be closer than 10 feet to each other.
But now we distinguish `DUPLICATE_TREE` (closer than 1 mm, an error) and `NEARBY_TREES` (closer than 10 feet, a warning). Trees with warnings will still be added during the "Add to Tree Map" step, so I'm removing the exclusion of `plot_ids_from_this_import`.
Here's how things will now work:
Validation step:
* If within 1 mm of tree in map, Error (`DUPLICATE_TREE`)
* If within 10 feet of tree in map, Warning (`NEARBY_TREE`)
* …
> Prevent importing trees with identical lat/lon

- opentreemap/importer/models/trees.py
- opentreemap/importer/templates/importer/partials/imports.html
- opentreemap/importer/tests.py
- opentreemap/importer/views.py
* Fetch and use instance's units for tree imports
* Refactor nearby code
* Respect unit conversions when validating against species max diameter/height
* Make tests actually test these things
Also tweak units warning:
* Show tree units first
* "Plot" -> "Planting Site"
* Tweak spacing
To test:
1) Make an instance centered on Minneapolis
2) Change units to metric for tree and plot fields (cm for diameter, m for the rest)
3) Import `//fileshare/users/rmohr/notes/otm/importer/minneapolis1.csv`
4) Verify values are correct by looking at tree detail
Connects #189
> Imports respect instance units

- opentreemap/importer/templates/importer/partials/resolve_popover.html
- opentreemap/importer/templates/importer/partials/species_resolve_popover.html
- opentreemap/importer/views.py
We already had a mechanism for this but just hadn't included the current panel and page number when hitting the `update_row` URL
Connects #2526
Testing:
Export a few trees (more than 10) from one instance and import to another instance.
They should all be on the "Errors" panel (lat/lon out of bounds).
Go to page 2 and change X or Y.
It should update and you should remain on page 2.
Extra credit: Fix it with an appropriate lat/lon and see it move to "Ready to Add"
> Preserve error panel's current page when resolving an error

- opentreemap/treemap/css/sass/modules/_checkboxes.scss
Firefox was not respecting the 0 width style, which caused the checkboxes
to have a padding on the left for the "invisible" checkboxes, *unless*
they had text long enough to wrap.
By using fixed positioning to place the inputs off the screen, we get
around browser inconsistencies with width, while still keeping the inputs
functionally invisible, but still enabled.
Connects to #2463
> Fix the styling of long field names in advanced search dropdowns

- opentreemap/treemap/management/commands/delete_data.py
- opentreemap/treemap/management/util.py
The --delete option to random_trees was incorrectly attempting to delete
all trees from all maps, not just the map associated with the command.
I switched the option to delete via SQL for better performance and so that
it could delete audits and other related objects as well.
I also added a delete_data command, which deletes all trees, plots, map
features and other related data from the given map, leaving mainly only
the import history and customizations in place.
Connects to #1139
> Fix random_trees command delete option and add delete_data command

- opentreemap/treemap/models.py
For unknown reasons, sometimes when `MapFeature.cast_to_subtype` is called
on Plot objects, they lack the `plot` attribute pointing from the
MapFeature superclass to the Plot subclass, causing `cast_to_subtype` to
incorrectly trest those objects as `PolygonalMapFeature` classes.
This works around the issue by having `cast_to_subtype` to just return
`self` if not called on the `MapFeature` superclass.
Connects to #2555
> Address issue with incorrect calls to MapFeature.cast_to_subtype

- opentreemap/treemap/js/src/urlState.js
- opentreemap/treemap/js/test/urlState.js
When panning or zooming the map, we store the map state in the URL.
Conversely, when changing the URL, we pan or zoom the map to match the new URL.
Because we used a fixed precision when storing lat/lng in the URL, but did not
do so for the state object that stored the current zoom/lat/lng, it was
possible for changes to the map state to cause an infinite loop, where the URL
and map state would constantly change but never get in sync with each other.
By serializing and deserializing our internal state object whenever we change
the URL, we ensure that when we later compare the current state object to the
new state to try and detect changes we'll never encounter these loops.
Connects to #2558
> Fix infinite loop of browser map state

- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/MapManager.js
- opentreemap/treemap/js/src/layers.js
- opentreemap/treemap/templates/treemap/settings.js
Allows defining per-instance custom layers, toggleable in the layer selector.
Caveat -- layer disappears if you zoom in further than tiles are available. We need to upgrade Leaflet.
Connects #2577
Testing:
1) Start a Django shell, and enter the code below.
2) `patreemap` should now show the canopy layer by default
3) In `phillytreemap` you can toggle the layer on, and see how it looks with trees
```python
import json
i = Instance.objects.get(url_name='patreemap')
layers = [
{
"name": "Tree Canopy",
"type": "tile",
"url": "http://com.azavea.datahub.tms.s3.amazonaws.com/treecanopy-2006-2008-pa/{z}/{x}/{y}.png",
"maxNativeZoom": 17,
"opacity": 0.5,
"showByDefault": True
}
]
i.config.custom_layers = layers
i.save()
i = Instance.objects.get(url_name='phillytreemap')
layers = [
{
"name": "Tree …
```
> Support custom layers

- Gruntfile.js
- opentreemap/treemap/templates/base.html
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templates/treemap/map-add-tree.html
- opentreemap/treemap/templates/treemap/partials/step_controls.html
- opentreemap/treemap/templates/treemap/user.html
- package.json
- Switches from using Google Tag Manager to using `analytics.js` directly
- Uses two trackers with different IDs for tracking events by map and in aggregate
- Removes URLs from instance and user specific page hits to allow for aggregate analysis
- Brings in the `autotrack` analytics plugin, and uses it to enable tracking of some of search and the add tree process.
Connects to #2576
> Update Google Analytics tracking code

- opentreemap/treemap/instance.py
- opentreemap/treemap/migrations/0025_remove_null_from_boundary_updated_at.py
- opentreemap/treemap/migrations/0026_add_canopy_fields.py
- opentreemap/treemap/models.py
Adds the fields required for showing canopy coverage for an instance.
- Instance.canopy_enabled: Whether or not the instance has canopy data
available.
- Instance.canopy_boundary_category: The category of boundaries to use
when showing a choropleth map of canopy coverage.
- Boundary.canopy_percent: The percent of the boundary area covered by
tree canopy.
This PR builds on to of https://github.com/OpenTreeMap/otm-core/pull/2591 which cleans up an old backwards-compatible migration.
---
Connects to https://github.com/OpenTreeMap/otm-core/issues/2589
> Add canopy fields

- opentreemap/treemap/migrations/0025_remove_null_from_boundary_updated_at.py
- opentreemap/treemap/models.py
Removes a TODO from the code. When this field was added it was marked as nullable so that the migration would be backwards compatible. The the current production database does not have any null values in this column.
> Make Boundary.updated_at not nullable

- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/templates/treemap/map_feature_detail.html
Instance admins can set the permissions on the Plot.id field to "Invisible." This is not a useful feature, and we intend to replace it with a better permission system.
For now, referencing `pk` rather than `id` prevents template rendering errors and we can fix the problem of a map feature not showing up as favorited on the detail page by performing the favorite check before the fields are masked.
---
On the `develop` branch, on the roles management page for an instance you own, set Planting Site Id to Invisible on the Administrator role. Attempting to view a tree detail page will raise an exception. Switch to this branch and detail pages should load without error and the favoriting feature should work.
---
Connects to https://github.com/OpenTreeMap/otm-core/issues/2594
> Handle invisible plot ID field

- opentreemap/treemap/migrations/0027_boundary_searchable.py
- opentreemap/treemap/models.py
- opentreemap/treemap/views/misc.py
The purpose of this field is to disable boundaries from appearing in the
frontend "Search by Location" autocomplete popup.
**Test:**
1. Run migrations
```sh
./scripts/manage.sh migrate
```
2. Disable searching on all boundaries (if you dare)
```sh
vagrant ssh services -c 'sudo -u postgres psql otm -c "update treemap_boundary set searchable=false"'
```
3. Verify that no boundaries appear in the "Search by Location" autocomplete
**Note:** You may have to clear localStorage to see this change.
```
localStorage.clear()
```
Connects #2598
> Add searchable field to Bounds model

- requirements.txt
Most of the changes in the `CHANGELOG` are bug fixes. There is one breaking change in the 0.12.x jump, but it pertains to Twisted support.
See also: https://github.com/rollbar/pyrollbar/blob/master/CHANGELOG.md
---
**Testing**
Provision and ensure that 0.12.1 is installed.
> Bump pyrollbar to 0.12.1

- opentreemap/treemap/js/src/mapPage.js
- opentreemap/treemap/js/src/searchBar.js
* Marker is removed when user starts a new search or clicks the "Reset" button.
* Icon uses otherwise-unused `marker.png`.
* Marker displays on top of other layers, but is not clickable.
Connects #2588
> Show a map marker when a location search succeeds

- opentreemap/treemap/instance.py
- opentreemap/treemap/migrations/0027_make_instance_canopy_fields_non_null.py
This cleans up the backwards compatible 0026 migration.
---
Connects to https://github.com/OpenTreeMap/otm-core/issues/2589
> Make instance canopy fields non-null

- opentreemap/treemap/migrations/0029_merge.py
Merging a pull request containing 0027_make_instance_canopy_fields_non_null created a migration conflict. I created the merge migration in this commit with the following command:
```
$ vagrant ssh app -c 'cd /opt/app/core/opentreemap \
&& envdir /etc/otm.d/env ./manage.py makemigrations --merge'
Merging treemap
Branch 0027_make_instance_canopy_fields_non_null
- Alter field canopy_boundary_category on instance
- Alter field canopy_enabled on instance
Branch 0028_auto_20160531_1537
- Add field searchable to boundary
- Alter field searchable on boundary
```
> Add a merge migration

- opentreemap/treemap/js/src/editableForm.js
This reverts a change that was made to set a custom display value in the
super admin. The super admin addon has been updated to use data
attributes to set a custom display value instead of hard-coding them
here.
The value field for checkboxes must always be True or False for parity
with the Django backend. Otherwise, checkbox values will become corrupt after
saving the form multiple times via ajax.
Ref https://github.com/OpenTreeMap/otm-addons/issues/1173
> Ensure checkbox value is always True or False

- opentreemap/treemap/js/src/imageUploadPanel.js
- opentreemap/treemap/templates/treemap/map_feature_detail.html
Prevent image uploads for file sizes equal to or greater than 1MB.
**Test:**
* Rebuild static assets `./scripts/grunt.sh`
* Try to upload a file 1MB or larger
* Ensure you get an error toast if the file is too big
Connects #2525
> Show error message when uploading files larger than 1MB

- opentreemap/treemap/js/src/otmTypeahead.js
- opentreemap/treemap/views/misc.py
* Update boundaries endpoint to order results by sort_order then name
* Ensure client-side results are sorted when displaying "all" results
(Bloodhound orders "all" results by id)
Connects #2608
> Fix boundaries dropdown sort order

- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/js/src/imageUploadPanel.js
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/templates/treemap/partials/upload_image.html
Read `MAXIMUM_IMAGE_SIZE` from an environmental variable and pass that
value to the client-side JS instead of hard-coding it.
Depends on https://github.com/OpenTreeMap/otm-cloud/pull/233
> Increase max upload filesize

- opentreemap/treemap/management/commands/create_instance.py
- opentreemap/treemap/models.py
Sometimes the center of a treemap is not in any i-Tree region, but the treemaps bounds do overlap an i-Tree region.
Depends on OpenTreeMap/otm-addons#1194
> Initialize eco factors from instance bounds, not point

- opentreemap/treemap/css/sass/partials/pages/_map.scss
- opentreemap/treemap/js/src/MapManager.js
- opentreemap/treemap/js/src/controls.js
- opentreemap/treemap/templates/treemap/partials/canopy_filter_control.html
This alters the style of the regional canopy filter control somewhat and adds a legend.
Connects #2629
> Add regional canopy filter legend

- opentreemap/opentreemap/util.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/MapManager.js
- opentreemap/treemap/templates/treemap/map.html
- opentreemap/treemap/templates/treemap/settings.js
We previously always centered the map on the map center point with a fixed
zoom.
With this change, we instead position the map so that all features added
to the map are visible. If a map has no trees yet, we position the map so
that all of the map's bounds are visible.
Connects to OpenTreeMap/otm-addons#1155
> Improve default map extent to be based on feature locations

- webpack.prod.config.js
`django-webpack-loader` defers to `publicPath` if it is available when
creating `<script>` tags, and otherwise constructs the path using the
bundle name and the value of the `BUNDLE_DIR_NAME` setting.
In practice, I was unable to find a value for `BUNDLE_DIR_NAME` that worked
for both locating the bundles on the local filesystem and creating URLs.
Setting `publicPath` explicitly (as we already do for development) works
around the issue.
> Explicitly set publicPath for production webpack configuration

- assets/css/sass/partials/pages/_admin.scss
Addressing https://github.com/OpenTreeMap/otm-addons/issues/1144
There are still some gaps in the click target, to the left of the label. They are minimal, and due to the use of a `table` to do the layout of the sidebar.
> Make management sidebar click targets full height of row

- opentreemap/treemap/lib/map_feature.py
Fixes a bug where plots were being associated with polygonal map
features from other instances.
Test by creating a rain garden on Map A, then adding a tree at the same spot on Map B. The tree on Map B should *not* be associated with a polygonal map feature.
Connects #2599
> Filter polygonal map features by current instance

- opentreemap/treemap/udf.py
Numeric choice values are parsed as numbers on the frontend, which
causes a validation failure on the backend when renaming numeric
fields, because `1 != "1"`.
Fixed by ensuring that the validation logic compares choice values as
strings.
Connects #2557
> Fix renaming numeric UDF field choices

- test-requirements.txt
On several occasions we have run into unit test failures that were resolved by updating the selenium package. Because this package is only installed in dev and test environments loosening the version specification will not jeopardize the repeatability of production builds.
2.53.6 was the latest version at the time of this commit.
> Loosen the selenium package version spec

- opentreemap/treemap/js/src/lib/mapPage.js
- opentreemap/treemap/js/src/lib/searchBar.js
This fixes a bug where advanced search filters would get stuck after
selecting a geocoded address in the locations autocomplete dropdown.
The Bacon stream responsible for triggering map and URL state changes
was only firing for non-geocode searches. I fixed this by merging in the
geocoding event stream so that map and URL state changes happen for both
geocode and non-geocode searches.
One unintended, but appreciated side-effect, is that selecting a
geocoded address will now remove the active boundary polygon from the
map. The previous behavior was a side-effect made possible only because we
were *not* applying search filters after selecting a geocoded address.
**Testing**
1. Verify that switching between a boundary and an address, clears the boundary polygon.
2. Verify that search filters …
> Apply search filter changes when geocoded address is active

- opentreemap/api/views.py
- opentreemap/treemap/audit.py
- opentreemap/treemap/lib/perms.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/templatetags/instance_config.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_audit.py
- opentreemap/treemap/views/map_feature.py
* Declare on models `MapFeature` and `Tree` that users should be able to delete objects they create (via `users_can_delete_own_creations = True`)
* Update `Authorizable.user_can_delete()`, which checks whether a user is allowed to delete an object:
* If user lacks delete permission and model has `users_can_delete_own_creations == True`, check Audit table to see if user created object.
* Change administrator test to check `admin` field rather than role name
Related updates in the 3 places we check delete permissions:
1. Delete from a mobile app (`remove_plot` in `api.views`) -- relies on `user_can_delete()` to raise an exception if user not allowed to delete
* Changed to catch `AuthorizeException` instead of `Exception`, and use its message instead of making a new one
2. Click the "Delete" …
> Let users delete trees and map features they created, regardless of permissions

- opentreemap/stormwater/models.py
- opentreemap/stormwater/tests.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/templates/treemap/partials/map_feature_accordion.html
- opentreemap/treemap/templates/treemap/resource_detail.html
The new `calculate_area` method on `PolygonalMapFeature` executes a query using the accurate anywhere in the world PostGIS geography type.
`PolygonalMapFeature`s are rendered by the tiler like point feature, so we do not have access to the polygon for client-side area calculation. I opted to create a instance method that makes a separate area query rather than try annotating PolygonalMapFeature query sets because we never need the area of more than one feature at a time.
I have temporarily hard coded a square meter label into the templates until we have implemented unit configuration for stormwater map features.
---
Create a map with all three stormwater features and add one of each to the map. The Rain Garden and Bioswale should show a "Area" in square meters on both the map page sidebar …
> Show polygonal feature area

- assets/js/vendor/leaflet.js
We need this limiting when zooming the map to the extent of all features, but we are waiting for the Leaflet 1.0 release to upgrade the entire library.
---
Create an instance. Add a single plot, and refresh the map page. On `develop` the map feature will not be clickable because the map tells the UTF grid plugin that it is showing a zoom level > 1000 and the UTF grid plugin does not make tile requests. On this branch, the feature will be clickable.
---
Connects to #2663
> Patch leaflet to respect maxZoom in Map.fitBounds

- opentreemap/stormwater/benefits.py
- opentreemap/stormwater/models.py
- opentreemap/stormwater/tests.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/models.py
* Add `PolygonalBasinBenefitCalculator` to compute `runoff_reduced` ecobenefit for both `RainGarden` and `Bioswale`
* Don't have to loop over features to calculate runoff reduced -- just sum the areas
* Refactor existing area computation code so it can be used for eco calculations also
* Rename the GSI eco category from `la_eco` to `green_infrastructure_eco`
Note: You must reprovision your app because of a `local_settings.j2` change in `otm-cloud`
Also, in `MapFeature` add `get_config` and `set_config_property` to manage configuration of a map feature type for an instance. For example, the `Bioswale` class declares its default configuration this way:
```py
default_config = {
'should_show_eco': True,
'diversion_rate': 0.95
}
```
Overrides for an instance are stored on …
> Add back end support for green infrastructure ecobenefits

- opentreemap/treemap/js/src/searchBar.js
This was a regression caused from the switch-over to using Webpack.
It was calling `searchBar.init()` when we should have been calling
`searchBar.initDefault()`, as `.init()` is intended for use on the map page.
Connects to #2679
Connects to OpenTreeMap/otm-clients#250
> Fix searchBar.js entry module.

- opentreemap/treemap/tests/base.py
- opentreemap/treemap/tests/ui/__init__.py
- opentreemap/treemap/tests/ui/uitest_map.py
A couple of small changes here:
- A code cleanup to remove a monkey patch that is no longer needed
- Some changes to test setup to fix regressions introduced by the switch to Webpack
- A fix to a UI test that seems to have started failing due to timing issues
Connects to OpenTreeMap/otm-cloud#258
> Fix UI tests

- opentreemap/opentreemap/settings/default_settings.py
Adding green infrastructure fields to the units management page
---
connects to OpenTreeMap/otm-addons#1211
> Add green infrastructure unit default settings

- opentreemap/stormwater/benefits.py
- opentreemap/stormwater/models.py
- opentreemap/stormwater/tests.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/partials/eco_benefits.html
Changes:
stormwater/models.py - default should_show_eco to False
treemap/models.py - save kwarg to determine whether setting a config attr
should save the instance
--
Connects to OpenTreeMap/otm-addons#1209
Depends on OpenTreeMap/otm-cloud#263
> Minor changes in support of FUF

- opentreemap/treemap/templates/treemap/settings.js
In b019bd3e we refactored `settings.js` to be compatible with our new Webpack-based bundling. The `canopyBoundaryCategory` property was [mistakenly omitted](https://github.com/OpenTreeMap/otm-core/commit/b019bd3ebac7208afdf115983b510ee54ffb5b10#diff-954ddbc65ef4c30a2e66f56d24773afcL70).
---
On `develop`, for an instance with canopy percentages configured, the layer will not display. On this branch, it will.
--- 
Connects to #2701
> Restore canopyBoundaryCategory to settings.js

- assets/css/vendor/datepicker.css
- assets/js/shim/bootstrap-datepicker.js
- opentreemap/opentreemap/context_processors.py
- opentreemap/treemap/templates/treemap/partials/udf_edit_field.html
- opentreemap/treemap/udf.py
Prevents invalid datetime UDFs from being saved, by adding extra server-side validation. The client-side datepicker has also been updated to disallow entering dates before `1/1/1900`.
**Note:** This PR *does not* clean up existing invalid UDF data. The `treemap_userdefinedcollectionvalue` and `treemap_audit` tables need to be corrected by hand. The plot detail page will continue to raise a validation error until the data has been fixed.
Connects #2686
> Prevent errors from invalid date UDFs

- opentreemap/otm1_migrator/migration_rules/tampa.py
- opentreemap/otm1_migrator/model_processors.py
I am committing these customer-specific rules to this repository because
similar rule files already exist in
`opentreemap/otm1_migrator/migration_rules`.
I based these Tampa rules on:
* The previous Philadelphia and San Diego rules.
* The fields available on the OTM1 tree detail pages.
* The choices JSON returned from the OTM1 `/choices/` endpoint.
This PR also includes a bug fix to the migrator. If a user of an OTM1 account had created an OTM2 account using the same email address, but had never logged in with that account, an exception would be thrown when attempting to migrate the users. This commit avoids the exception by checking for a `None` value.
Connects to https://github.com/OpenTreeMap/otm-clients/issues/256
> Add Tampa Tree Map migration rules 

- opentreemap/stormwater/migrations/0007_drainage_area_permissions.py
- opentreemap/stormwater/tests.py
- opentreemap/treemap/instance.py
UdfGenericCreateTest.test_non_treemap_model was simply appending 'Bioswale' to
map_feature_types with the += operator, bypassing add_map_feature_types.
Fix it to use add_map_feature_types.
In instance, return deepcopy(default) from the getter of the property returned
by _make_config_property, to prevent any code from changing the default for all
instances by mistake.
Additionally, replace map_feature_types with \_map_feature_types, to signal that
the setter is "private", and provide a get-only map_feature_types property,
with a docstring pointing at add_ & remove_map_feature_types functions.
--
Connects to #2703
Depends on OpenTreeMap/otm-addons#1227
> Fix broken test and make the map_feature_types property safer

- opentreemap/stormwater/benefits.py
- opentreemap/stormwater/migrations/0008_benefits-calc-cache-flush.py
- opentreemap/stormwater/models.py
- opentreemap/stormwater/tests.py
Note: you might still see incorrect aggregate results in your browser due to
OpenTreeMap/otm-core#2707. Going in with the shell and kicking universal_revs a
couple times seems to resolve it.
Added the new calculation to stormwater/benefits.py. Since drainage_area is not
in PolygonalMapFeature, had to change the interface to the internal
_benefits_for_feature_qs and pass in a qs of the original map feature class.
The new calculation also calls for a default constant of 0.85.
Updated tests accordingly.
--
Connected to #2689
> Update stormwater benefit calculation to include drainage area

- opentreemap/stormwater/models.py
- opentreemap/treemap/js/src/lib/addResourceMode.js
- opentreemap/treemap/templates/treemap/partials/map_add_resource.html
Actually, the add resource detail step has always been optional. If you enter a
character, the Next button would be enabled, and remained enabled even if you
then delete the character.
Make the detail page for the polygonal map features come up with the Next
button enabled by adding a data attribute, enable-detail-next, and its
attendant class attribute on PolygonalMapFeature, then making the
addResourceMode js respect the data attribute.
--
Connects to #2708
> Make drainage_area optional

- opentreemap/api/tests.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/stormwater/migrations/0009_drainage_area_imperial_units.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/units.py
Rain Garden and Bioswale area and drainage area default units should
be square feet, not square meters.
Changes:
* Add Rain Garden, Bioswale, and Green Infrastructure to the
STORAGE_UNITS default setting
* Add a conversion from square feet to square meters or feet
to units
* In lib/map_feature, change context_dict_for_resource to
return treemap units conversion for the resource area
--
Connects to #2706
> Default area units should be imperial

- opentreemap/treemap/js/src/lib/MapManager.js
- opentreemap/treemap/js/src/lib/browseTreesMode.js
The map returned by MapManager.js createTreeMap needs to have
utfEvents that merge the plotUtfEventStream with a zip
that combines fields from the emptyUtfEventStream with
the fields returned byt the polygonDataStream.
Using lodash's merge rather than assign to make a deep copy,
because I don't know the potential side effects of different stream
elements sharing descendant objects.
Let me know if you think _.assign would be sufficient.
--
Connects to #2652
> Display polygonal map feature popups

- assets/css/sass/partials/pages/_addtree.scss
- dev-requirements.txt
- opentreemap/api/instance.py
- opentreemap/opentreemap/context_processors.py
- opentreemap/stormwater/templates/stormwater/Bioswale_add.html
- opentreemap/stormwater/templates/stormwater/RainGarden_add.html
- opentreemap/treemap/search_fields.py
- opentreemap/treemap/templates/treemap/field/div.html
- opentreemap/treemap/templates/treemap/resource_detail.html
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/templatetags/util.py
_Note to the reviewer: the rest of the requirements in this issue are
wholly addressed in the addons repository, and are entirely independent
of the core work represented by this PR. I think you can review this PR
without reference to the coming addons PR._
When adding a resource, if the choice is RainGarden or Bioswale,
when it prompts for drainage_area, provide help text below the input.
Also, update the question text.
Changes:
1) `assets/css/sass/partials/pages/_addtree.scss`: style the help text.
2) `stormwater/*_add.html`: update the question text and add
the explanation to the `create` tag for RainGarden and Bioswale,
and direct interpolation of their terminology.
3) `treemap/field/div.html`: add conditional explanation markup.
4) `treemap/templatetags/form_extras.py`: add …
> Explain drainage_area when adding a resource

- opentreemap/stormwater/templates/stormwater/Bioswale_detail.html
- opentreemap/stormwater/templates/stormwater/RainBarrel_detail.html
- opentreemap/stormwater/templates/stormwater/RainGarden_detail.html
- opentreemap/treemap/js/src/lib/inlineEditForm.js
- opentreemap/treemap/js/src/lib/mapFeatureDelete.js
- opentreemap/treemap/js/src/lib/plotAddTree.js
- opentreemap/treemap/js/src/lib/plotDetail.js
- opentreemap/treemap/js/src/lib/resourceDetail.js
- opentreemap/treemap/js/src/mapFeatureDetail.js
- opentreemap/treemap/routes.py
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/templates/treemap/partials/map_feature_detail_base.html
- opentreemap/treemap/templates/treemap/partials/plot_detail.html
- opentreemap/treemap/templates/treemap/partials/resource_detail.html
- opentreemap/treemap/templates/treemap/plot_detail.html
- opentreemap/treemap/templates/treemap/resource_detail.html
- opentreemap/treemap/tests/test_urls.py
- opentreemap/treemap/tests/ui/__init__.py
- opentreemap/treemap/tests/ui/plot_detail/uitest_add.py
- opentreemap/treemap/tests/ui/plot_detail/uitest_delete.py
- opentreemap/treemap/tests/ui/plot_detail/uitest_edit.py
- opentreemap/treemap/urls.py
- opentreemap/treemap/views/map_feature.py
* Refactor templates and JS to allow reloading map feature details as a partial
* The partials (which extend `partials/map_feature_detail_base.html`) include the title area, action buttons, and detail area.
* The partials do not include the mini map and streetview, since that would cause an obvious flash
* Detail page tells inline edit form not to update on successful save (we'll wait for refresh)
* Show spinner on both "Save" and "Delete"
* Simplify code that was directly updating details
NOTE - looking at individual commits will make it easier to review the code, since there were a couple of re-indentation steps
Depends on OpenTreeMap/otm-addons#1230
Connects #2667
Connects #2664
Connects #1719
Connects #975
Testing
* Verify that the above open bugs are fixed
* Verify that these closed …
> Refresh details when hitting "Save" on a plot/resource detail page

- assets/css/sass/partials/pages/_treedetails.scss
A 25px top margin was introduced [here](https://github.com/OpenTreeMap/otm-core/commit/6c90967#diff-bf0bf7f1b303c2fd6c2d997a3726893eR9) as part of fixing spacing in nested comments for #1553.
Removing that margin makes the sidebar bubbles look right again, and nested comments still look fine.
Connects #2692
> Reduce top spacing in detail page sidebar bubbles

- opentreemap/treemap/js/src/simpleForm.js
- opentreemap/treemap/templates/registration/login.html
- opentreemap/treemap/templates/registration/password_reset_confirm.html
- opentreemap/treemap/templates/registration/password_reset_form.html
- opentreemap/treemap/templates/registration/registration_form.html
We missed updating JS on a few pages when we switched to webpack. So:
* Create `simpleForm.js` which just focuses on the first non-hidden `input` element.
* Use it on pages for login, registration, and password reset.
Note that `password_reset_form.html` had been adding the class `form-control` to its input element.
Since that doesn't change its appearance significantly I've taken the simpler route of using the shared `simpleForm.js`.
Connects #2721
> Unify JS on pages containing a simple form (fixing JS errors)

- opentreemap/stormwater/models.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/test_models.py
Changes to `validate_positive_nullable_float_field`:
* Add `zero_ok` argument
* DRY it out
* Add tests
Connects #2732
> Allow 0 as a value for resource drainage area

- opentreemap/otm1_migrator/migration_rules/tampa.py
I added a static lookup table in the Tampa migration code to handle species that do not have an i-Tree code set in the species fixture. I opted to handle these 7 edge case species with a literal lookup rather than make the non-trivial changes to the migrator to properly handle the one-to-many relationship between species rows and resource rows. The migrator is reaching the end of its life and the cost of the changes does not justify the relatively small gain in general
correctness.
I created the table by running this query against the otm-legacy database:
```sql
SELECT lower(scientific_name), meta_species
FROM treemap_species s
JOIN treemap_species_resource sr ON s.id = sr.species_id
JOIN treemap_resource r ON sr.resource_id = r.id
WHERE itree_code = '';
```
---
After running a migration …
> Add meta species lookup table for Tampa migration

- opentreemap/stormwater/migrations/0010_stormwater_blank_true.py
Note: This is targeted at the `release/2.11.0` branch.
Running `./scripts/manage.sh migrate` in development was printing a "Your models have changes that are not yet reflected in a migration..." message.
I ran `./scripts/manage.sh makemigrations` to generate the missing migration. The two fields were added in stormwater migration 0006. The migration is missing the `blank=True` keyword argument, but the changes to `models.py` in c805dc8 include the `blank=True` keyword argument. I am not sure how this mismatch occurred.
---
Migrations should be applied without any warning messages.
---
Connects to #2747
> Add missing stormwater migration

- opentreemap/exporter/tests.py
The object literal confusingly defines keys twice. Based on the content of the `setUp` function and the assert statement
```python
self.assertUserJSON(user2data, ...
```
it is clear that the intention was to assert `user2` values.
Connects to #2761
> Remove duplicate keys from object literal in test

- assets/css/sass/partials/pages/_treedetails.scss
- opentreemap/treemap/js/src/lib/inlineEditForm.js
- opentreemap/treemap/templates/treemap/field/diameter_tr.html
- opentreemap/treemap/templates/treemap/field/species_tr.html
- opentreemap/treemap/templates/treemap/field/tr.html
When there was a tree detail error, it was displayed in a new third table column. This caused the
diameter/circumference edit widget to get so narrow you couldn't see the values.
Changes: 1. Show the message in a new <tr>. 2. Show/hide the <tr>. 3. Show the message in a
colspan="2" <td> in the <tr>,
so it fills the width of the row. 4. Show the message in a div inside the <td colspan="2">
to get the styling right. 5. Style it.
The styling problem is that bootstrap.css orders
.table > tbody > tr > td later than .alert-danger, resulting in a td-looking top border, instead of 
4 alert-danger borders, which looks awful.
The alternative would have been to specify the border-top in the td[colspan="2"] style, but then we
have to copy-paste from bootstrap, which has maintainability problems.
-- …
> Tree detail error message vs. diameter field

- opentreemap/importer/fields.py
- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
- opentreemap/treemap/migrations/0030_add_verbose_name_to_owner_orig_id.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/partials/plot_detail.html
- opentreemap/treemap/templatetags/form_extras.py
Also renamed the `owner_orig_id` field to be "Custom ID", and updates its name in the importer template.
With this change in place, "Custom ID" should be a search field option in the search fields management page under the planting site section, and "Missing Planting Site Custom ID" should be an option under the "Missing Data" section.
Connects to #2734
> Add support for searching on the 'owner_orig_id' field.

- assets/css/sass/partials/_header.scss
- assets/css/sass/partials/_layout.scss
- opentreemap/opentreemap/context_processors.py
- opentreemap/treemap/decorators.py
- opentreemap/treemap/js/src/lib/browseTreesMode.js
- opentreemap/treemap/js/src/lib/mapPage.js
- opentreemap/treemap/js/src/lib/treeMapModes.js
- opentreemap/treemap/js/src/treeMap.js
- opentreemap/treemap/templates/base.html
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templates/treemap/map-browse-trees.html
- opentreemap/treemap/templates/treemap/map.html
- opentreemap/treemap/tests/test_urls.py
- opentreemap/treemap/views/misc.py
On map page:
* Add embed context variable.
* Prune header and footer HTML if embed.
* Add an embed class to wrapper.
* Adjust data for Add a Tree or Resource buttons.
* Fix up button anchors
* For embed, don't include the quick edit button.
Style:
* Style adjustments for .wrapper.embed.
* Eliminated ambiguous "map" css class.
JavaScript:
* Save the embed query string parameter in the mapPage.
* If embed is true, fix up the add button's href,
and let the browser do its thing.
* Change Add to open a new tab or window,
and preserve zoom.
* Change details links to open a new tab or window.
Add a test to make sure we still get the page when
?embed= is in the query string.
--
Connects to #2736
> Honor embed query string parameter

- opentreemap/treemap/audit.py
In treemap.audit, change FieldPermission.display_field_name to
use the field verbose name if it has one.
--
Connects to OpenTreeMap/otm-addons#1239
> Change Owner Orig Id to Custom Id in role management

- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/udf.py
UDF choices were being renamed across instances.
---
If you revert the change to `opentreemap/treemap/udf.py` then run `./scripts/manage.sh test treemap.tests.test_udfs.ScalarUDFInstanceIsolationTest` you should see an assertion fail toward the bottom of the test case.
You can also interactively reproduce the bug after reverting the change to `opentreemap/treemap/udf.py` 
* Create two instances
* Add a single choice field with the same name and same choices to both instances
* Add a tree to both instances and set the same choice value on both trees.
* Rename the choice on one instance, then load the tree detail page on the unchanged instance.
> Isolate UDF choice renaming

- opentreemap/treemap/ecobenefits.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/lib/browseTreesMode.js
- opentreemap/treemap/js/src/lib/search.js
- opentreemap/treemap/js/src/lib/treeMapModes.js
- opentreemap/treemap/js/src/treeMap.js
- opentreemap/treemap/lib/perms.py
- opentreemap/treemap/templates/treemap/partials/eco_benefits.html
- opentreemap/treemap/tests/ui/uitest_map.py
- opentreemap/treemap/views/misc.py
- opentreemap/treemap/views/tree.py
* Show count of empty planting sites rather than total planting sites
* Add helper instance properties `map_feature_classes` and `resource_classes`
* If search returns a single result, select that result
Connects #2772 
Connects #2745
> Select single search result, and show empty planting site count

- dev-requirements.txt
- opentreemap/registration_backend/views.py
- requirements.txt
- test-requirements.txt
Incorporate module updates flagged by `requires.io`. Summary below, and at https://requires.io/github/OpenTreeMap/otm-core/requirements/?branch=develop
Other `requirements.txt` updates:
* Alphabetize (note this is in a separate commit from actual changes)
* Record changelog in comment if not linked by requires.io
Also adjust for breaking change in `django-registration-redux`
Testing as noted below.
Connects #2770
Depends on https://github.com/OpenTreeMap/otm-addons/pull/1241
Module | Old | New | Changes | Comments | Testing
------ | --- | --- | ------- | -------- | -------
boto | 2.38.0 | 2.42.0 | [changes](http://docs.pythonboto.org/en/latest/releasenotes/v2.39.0.html) | Bug fixes and small features | deploy to staging will test
coverage | 4.0.3 | 4.2 | …
> [requires.io] dependency update

- requirements.txt
It looks like requires.io won't pick up its `rq.filter` comment if there is another "comment" after it on that line.
> Update requirements.txt to fix require.io version comment

- assets/css/sass/partials/_header.scss
- assets/css/sass/partials/_layout.scss
- assets/css/sass/partials/_navbar.scss
- assets/css/sass/partials/_subheader.scss
- opentreemap/treemap/js/src/lib/addResourceMode.js
- opentreemap/treemap/js/src/lib/baconUtils.js
- opentreemap/treemap/js/src/lib/treeMapModes.js
- opentreemap/treemap/js/src/lib/urlState.js
- opentreemap/treemap/js/src/treeMap.js
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templates/treemap/partials/add_feature_menu.html
- opentreemap/treemap/templates/treemap/partials/add_plot_btn.html
- opentreemap/treemap/tests/ui/__init__.py
-  Fixes responsive styling issue with gray bar on screens smaller than 990px
-  Combines add tree and add resource buttons into a single button group
With these changes, it should not be possible for items to overlap or get pushed down in the header, no matter the screen size or the length of the "resources" terminology.
Connects to #2737
> Refactor stats bar to be more responsive on small-medium screen sizes

- opentreemap/treemap/js/src/lib/searchBar.js
The "Tree" category wasn't being highlighted because the expression `_.map(search.display, R.toLower)` should have said `R.toLowerCase`, however after making that change it still failed so I wrote it using the native JS `toLowerCase`.
The "General" category wasn't being highlighted because the "Last Updated" filter has a `featureName` of `mapFeature` which wasn't accounted for in the comparison to display filters. (There is no display filter for `maspFeature` since everything is a `mapFeature`). I added a case for that.
Connects #2433
> Fix advanced search category highlighting

- opentreemap/treemap/DotDict.py
- opentreemap/treemap/migrations/0031_add_custom_id_to_default_search_fields.py
- opentreemap/treemap/search_fields.py
Search by Custom ID and by missing Custom ID should be enabled
by default, for all treemap instances.
Changes
=======
Data migration to add the Custom ID internal identifier (`plot.owner_orig_id`) to every instance that already has a `search_config` or `mobile_search_fields` config property, with its reverse.
Add `plot.owner_orig_id` to default search fields, and make default search fields `DotDict`s so that `instance.search_config` and `instance.mobile_search_fields` return the same type whether explicitly configured or not.
Fix `DotDict().setdefault` to work for dotted keys.
--
Connects to #2769
> Enable search by Custom ID & missing Custom ID

- assets/css/sass/partials/pages/_admin.scss
The iframe needs to use content-box because we can't count on the
customer's website styling the border or padding the same as ours.
--
Connects to OpenTreeMap/otm-addons#1270
Depends on OpenTreeMap/otm-addons#1273
> Embed management page iframe sizes

- opentreemap/otm_comments/migrations/0003_auto_20160923_1413.py
New version of django module changed threaded comment metadata.
Update the schema for the subclass of the django model.
Necessary for release 2.12.0.
--
Connects to azavea/trees-team#85
> Threaded comments migration

- opentreemap/treemap/models.py
- opentreemap/treemap/templates/base.html
- opentreemap/treemap/templates/treemap/partials/map_feature_detail_base.html
- opentreemap/treemap/templatetags/auth_extras.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_templatetags.py
- opentreemap/treemap/util.py
The header login link href now specifies the login page,
with the urlencoded current page in the `?next=` query string param.
Also changed the `InstanceUser` `__unicode__` method to do something
sensible when there is no logged in user.
Needed that for the django debug toolbar templates tab,
which was crashing in `InstanceUser.__unicode__`.
--
Connects to #2239
Connects to #2185
> Header login link preserves current page

- assets/css/sass/partials/pages/_modeling.scss
- opentreemap/treemap/js/src/lib/MapManager.js
- opentreemap/treemap/js/src/lib/mapPage.js
- opentreemap/treemap/js/src/lib/urlState.js
- opentreemap/treemap/js/test/urlState.js
As before, calling `createMap` with `options.trackZoomLatLng` causes `MapManager` to save/load zoom/lat/lng to the `urlState`.
Now, specifying `options.zoomLatLngInputStream` as well signals that, instead, the calling page will handle save/load of zoom/lat/lng:
* The calling page provides loaded zoom/lat/lng values via `options.zoomLatLngInputStream`, and `MapManager` updates the map accordingly.
* `createMap` now returns `zoomLatLngOutputStream` (with updated zoom/lat/lng values as the user zooms and pans the map), and the calling page uses it to save zoom/lat/lng values.
(This PR also contains a style update missed in a previous commit.)
Connects #1252
> Allow MapManager clients to handle save/load of zoom/lat/lng

- opentreemap/api/tests.py
We were calling `instances_closest_to_point` with four instances, adding another instance, and calling `instances_closest_to_point` again. The second call was intermittently failing because the distance is 0 to two of the instances, making for an indeterminate ordering when sorting by distance. (The distance is computed to the instance bounds, and it's 0 for two instances because
the point is inside their bounds.)
I removed the second call because it does not appear to test any functionality not covered
by the first call. The results of the first call don't have the indeterminate order problem.
Connects #2698
> Fix intermittently-failing test

- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/audit.py
- opentreemap/treemap/decorators.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/management/commands/create_instance.py
- opentreemap/treemap/management/util.py
- opentreemap/treemap/migrations/0032_rename_to_role_default_permission_level.py
- opentreemap/treemap/migrations/0033_instance_permissions.py
- opentreemap/treemap/migrations/0034_add_permission_view_external_link.py
- opentreemap/treemap/plugin.py
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templatetags/instance_config.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_perms.py
We introduce two categories of permissions, both using the `Permission` model from `django.contrib.auth` and both stored in (the new) `Role.instance_permissions` many-to-many field:
1) Instance permissions, controlling access to features at the instance level
* `get_instance_permission_spec()` defines these permissions (and their default roles).
* Currently we define one such permission, for viewing an "external link" on detail pages.
* `add_instance_permissions()` in `audit.py` handles adding these permissions to a new instance's roles.
2) Add/delete permissions, giving control over adding and deleting particular models
* Thanks to `django.contrib.auth`, add and delete permissions are automatically created for all models. For example, `Permission` objects `add_plot` and `delete_plot` …
> Instance-level permissions

- opentreemap/exporter/tasks.py
- opentreemap/treemap/audit.py
- opentreemap/treemap/lib/object_caches.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/test_audit.py
- opentreemap/treemap/tests/test_object_caches.py
- opentreemap/treemap/tests/test_templatetags.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/udf.py
Leverage `joint_writable` and comment more fully.
It now encompasses all required fields that make no sense
to authorize separately from the new add and delete permission.
Initialize `joint_writable` in `Authorizable` to include `id`.
Update it with MapFeature and Tree fields.
Making required fields not authorizable conflicts with
insertion and deletion pending approval, so disable
relevant pending tests and drop support for
insert and delete pending approval.
Also minor refactoring.
--
Connects to #2825
> Separate authorization from tracking

- dev-requirements.txt
For easy access to ipython,
* enable `django-extensions` in `local_settings.py`
* `manage.py shell_plus`
`ipython-genutils` came with the `ipdb` install. We can ignore it, but it seemed better to make it (and its version) explicit in dev-requirements.txt.
`notebook` is an `ipython` extension for serving documentation. If someone takes the time to add our markdown files to a notebook, we can serve them as html on our localhosts. Could be convenient, especially for previewing changes.
We can also use a notebook to script access to a `shell_plus` kernel, for live, interactive documentation, if we can figure out how.
> Add ipython and ipdb to dev-requirements.txt

- assets/css/sass/_base.scss
- assets/css/sass/partials/_header.scss
- assets/css/sass/partials/_layout.scss
- assets/css/sass/partials/_navbar.scss
- assets/css/sass/partials/_subheader.scss
- opentreemap/treemap/js/src/lib/otmTypeahead.js
- opentreemap/treemap/js/src/lib/searchBar.js
- opentreemap/treemap/js/src/lib/stickyTitles.js
- opentreemap/treemap/templates/base.html
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templates/treemap/partials/advanced_search/tree_care.html
- opentreemap/treemap/templates/treemap/partials/search_location.html
- opentreemap/treemap/templates/treemap/partials/search_species.html
With these changes, all advanced search functionality is now available on small screen sizes.
Map page on page load:
When tapping on the location search box:
After tapping on the "Advanced search" toggle in the header:
Search buttons are sticky when scrolling:
For medium-sized screens we now always show both the species and location search boxes (by hiding the map logo):
Connects to https://github.com/OpenTreeMap/otm-core/issues/1127
> Implement mobile responsive search for small screen sizes

- opentreemap/treemap/js/src/lib/MapManager.js
`MapManager.setCenterAndZoomLL` prevents zooming out (so e.g. if user is choosing a tree location via geolocation but is zoomed in further than ZOOM_PLOT, we won't zoom them out). That's not appropriate when initializing a map from a saved zoom, so just use `map.setView`.
Connects #2833
> Fix initial map zoom when loading from a URL

- opentreemap/importer/templates/importer/partials/clientside_templates.html
- opentreemap/otm_comments/templates/otm_comments/partials/moderation_row.html
- opentreemap/treemap/js/src/lib/urlState.js
- opentreemap/treemap/js/test/urlState.js
- opentreemap/treemap/templates/treemap/partials/export.html
- opentreemap/treemap/templates/treemap/partials/photo_social_media_sharing.html
- opentreemap/treemap/templates/treemap/partials/step_controls.html
- opentreemap/treemap/templates/treemap/partials/upload_image.html
`urlState.js` keeps an object in `window.history.state` and, on history changes, uses it to detect which part of a URL has changed. Things work fine when history changes are initiated by the `urlState` module itself. But clicking a link with `href="#"` without calling `preventDefault()` also causes a history change, and we weren't handling that correctly.
So:
1. Replace occurrences of `href="*"` with `href="javascript:;"`. It's just safer. Adding `#` to the URL is not always innocuous, and we don't want to rely on `preventDefault` being called.
2. Don't assume our history state object exists. On history changes, construct our state object from the URL.
Either of these changes would suffice by itself. Do both -- belt and suspenders.
And it turns out that we don't actually need to store an …
> Prevent urlState crash

- assets/css/sass/partials/pages/_admin.scss
- opentreemap/api/instance.py
- opentreemap/stormwater/models.py
- opentreemap/treemap/audit.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/lib/editableForm.js
- opentreemap/treemap/lib/object_caches.py
- opentreemap/treemap/lib/perms.py
- opentreemap/treemap/migrations/0035_merge.py
- opentreemap/treemap/migrations/0036_assign_role_add_delete_permissions.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_audit.py
- opentreemap/treemap/tests/test_object_caches.py
- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/tests/test_views.py
* Data migration for instance and model level permissions
* Change permission spec to suit roles management.
* Styling for the updated roles management page
* Changes in audit.py to better support the new permission universe,
and corresponding test updates.
* Temporarily move photo READ_ONLY FieldPermission minimum into
default method until #2176 is done.
FieldPermission for photos can be entirely removed during #2176.
* Handle radio inputs in editable form JavaScript.
* Add test utility functions for use in addons.
--
Connects to OpenTreeMap/otm-addons#1287
Depends on OpenTreeMap/otm-addons#1312
> Support new roles management.

- opentreemap/otm1_migrator/migration_rules/treezilla.py
- opentreemap/otm1_migrator/model_processors.py
- The otm-legacy version of Treezilla stores tree diameter and height in the database in meters. OTM2 stores diameters in inches and heights in feet and converts to metric units on the fly.
- The `city` column of the `treemap_neighborhood` table in the otm-legacy database groups regions into different categories, but based on our research [1] [2] different categories do not overlap. I added a presave action to give the regions full category names and gave them the same sort order value, since they do not overlap.
- I set the UDF choice field values based on the the response from the otm-legacy endpoint http://treezilla.org/choices/.
This PR also includes a fix to comment migration handling. The edited line in `model_processors.py` previously raised an exception if the comment was skipped …
> Add migration rules for Treezilla

- requirements.txt
Version 3.1.17 of `django-celery`, which we are installing via `django-celery-with-redis` only has a minimum `celery` version set in its requirements
https://github.com/celery/django-celery/blob/v3.1.17/requirements/default.txt
```
celery>=3.1.15
```
`django-celery` fixed their requirements file on the master branch 19 days ago, but `celery` released version 4.0 before an updated version of `django-celery` was released.
I have copied the celery version restriction into our `requirements.txt` as a temporary fix until either:
- `django-celery` releases an update, and we switch to that new release.
- We remove `django-celery-with-redis` and replace it with explicit individual package references.
---
Using the `develop` branch, destroy your vagrant app VM and recreate it. Provisioning will …
> Explicitly set celery version limits in requirements.txt

- opentreemap/treemap/audit.py
Connects OpenTreeMap/otm-addons#1160
> Allow using non-ASCII characters when hashing for an etag

- opentreemap/api/instance.py
- opentreemap/stormwater/models.py
- opentreemap/stormwater/tests.py
- opentreemap/treemap/audit.py
- opentreemap/treemap/lib/object_caches.py
- opentreemap/treemap/lib/perms.py
- opentreemap/treemap/migrations/0037_fix_plot_add_delete_permission_labels.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/templates/treemap/partials/photo_carousel.html
- opentreemap/treemap/templatetags/instance_config.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_audit.py
- opentreemap/treemap/tests/test_object_caches.py
- opentreemap/treemap/tests/test_perms.py
- opentreemap/treemap/tests/test_templatetags.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/udf.py
- opentreemap/treemap/util.py
* Create new tests, adapt old tests, add to the cast of users
* Remove tests around provisional creation
* Modify `audit` and `perms` to use model permissions
* Modify `instance_config` and templates that use it
* Minor clean-up along the way
--
Connects to #2176
Connects to #2411 
Connects to #2177 
Depends on OpenTreeMap/otm-addons#1324
> Apply model permissions

- opentreemap/treemap/instance.py
The `SPECIES` list defined in `opentreemap/treemap/__init__.py` is intended to be a constant. The `add_species_to_instance` function was mutating it, adding full `Instance` objects to each species object. This came to our attention when some other code was trying to call `json.dumps` on the species dict and the `Instance` objects are not JSON serializable.
> Do not mutate the static SPECIES list

- opentreemap/otm1_migrator/migration_rules/treezilla.py
The `Tree.tree_owner` field is "removed" in the default migration rules, but over half of the trees in the Treezilla data set have a `tree_owner` value that we should preserve.
--- 
I ran a migration into a new instance on my developer VM using this branch.
OTM1
```sql
tz=# select tree_owner, count(*) from treemap_tree group by tree_owner order by tree_owner;
tree_owner           | count
--------------------------------+-------
0                              |     1
David and Judith Jenkins       |     1
Open University                |   862
RBG Edinburgh                  |     1
Robert and Angela Hull         |     1
Royal Botanic Garden Edinburgh |  2588
Stowupland Parish Council      |   114
Stowupland Parish Council      |     8
Stowupland Parish Councl       |     1
Walsall Council …
```
> Add tree owner to Treezilla migration

- opentreemap/treemap/lib/external_link.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/templates/treemap/partials/detail_external_link.html
- opentreemap/treemap/templates/treemap/partials/map_feature_detail_base.html
- opentreemap/treemap/templatetags/util.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_audit.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/util.py
Ignore all the commits but the last one, subject line __External link__.
This PR is based off another PR, #2847, before the other one is merged,
causing all the commits from the latter PR to appear in this one.
Changes:
* Create a new partial template for external link
and include it in the detail template
* Make template filters for use in the template
* Move stuff into treemap.util to share with addons
--
Connects to #2785
Depends on OpenTreeMap/otm-addons#1332
> External link

- opentreemap/treemap/lib/udf.py
- opentreemap/treemap/tests/test_udfs.py
- Enable new custom field by default
- Use role default field permissions instead of NONE for all the roles
- Fix a test to create stewardship udfs, to be consistent with instance config
Connects to #2871 
Depends on OpenTreeMap/otm-addons#1342
> Display new custom field

- opentreemap/stormwater/models.py
The code was mistakenly removed on August 5 2016, in c805dc8385dfe595be21379b5a8858c24bca8eb3
Connects #2877
> Restore RainBarrel.is_editable

- opentreemap/treemap/migrations/0038_update_delete_perm_labels.py
Users may always delete objects they have created, regardless of their permissions. I have updated the names of the delete permissions to clarify that granting these permissions will give members of the role the ability to delete any object of that type, not only ones that they have created.
---
Create or use an instance that has all green infrastructure types enabled, and use a second instance that has LA infrastructure variants enabled.
Verify that the labels on all "delete" permissions include the word "any."
---
Connects to #2876
> Update delete permission labels

- opentreemap/treemap/audit.py
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/management/commands/set_mapfeature_updated_by.py
- opentreemap/treemap/migrations/0038_updated_by.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/test_cached_audit_info.py
- opentreemap/treemap/tests/test_management.py
- opentreemap/treemap/tests/test_map_feature.py
- opentreemap/treemap/tests/test_util.py
- opentreemap/treemap/tests/test_views.py
Changes:
* Add `updated_by` field, and make it not trackable
* Migration to add the column to the db
* Command in lieu of a migration to populate the column
* `treemap.model` updates `updated_by` along with `updated_at`
* Tests for the population command
* Tests for updating `updated_by`
* Minor refactor from references to `always_writable`
to `bypasses_authorization`
* Minor test changes to facilitate `test --keepdb`
--
Connects to #2863
> Backend for filter by updated-by

- assets/css/sass/partials/pages/_modeling.scss
- assets/css/sass/partials/pages/_scenarios.scss
- updated the label for _all trees_. Now reads _Annual mortality (%) for all trees_
- additionally updated the input-addon label to just a _%_ to mimic the table in the customize by species modal.
- added some spacing between the two Tree Mortality Rate options
- Added a _species_ table heading to the custom species modal.
- Moved the _delete button_ to the last column of the table and styled it.
- added a max-height and scroll to the _add a species dropdown_
- simplified the double row table header into a single row.
- cleaned up the scenarios menu bar a bit.
In order to test, pull down this branch and the branch from this PR https://github.com/OpenTreeMap/otm-addons/pull/1349
> cleanup on the modeling work

- opentreemap/otm1_migrator/migration_rules/standard_otm1.py
- opentreemap/otm1_migrator/model_processors.py
Threaded comments were being migrated incorrectly. The `submit_date` was being set to the date of the migration, not the original comment submit date. The solution is to ensure that the renaming of `date_submitted` (which is the name used in the OTM1 fixtures) to `submit_date` is configured in the standard migration rules for both comments and threadedcomments, and that the mapping old name to new name is correctly defined.
I have opted to swallow a character encoding exception raised when
attempting to print a skipped migration warning message:
- The comment text does not provide extra information
- We do not anticipate using the OTM1 migrator in the future. Properly
debugging the character encoding failure is not a good use of
development time.
---
I tested this by:
- Creating …
> Fix comment handling in migrator

- opentreemap/treemap/decorators.py
Prevents a crash when trying to load an instance you aren't authorized to access.
> Add safety code in requires_permission decorator

- assets/css/sass/partials/_header.scss
- assets/css/sass/partials/_layout.scss
- assets/css/sass/partials/pages/_modeling.scss
- opentreemap/treemap/js/src/lib/baconUtils.js
- opentreemap/treemap/js/src/lib/otmTypeahead.js
- opentreemap/treemap/templates/treemap/partials/search_location.html
- opentreemap/treemap/templates/treemap/partials/search_species.html
* Expose more information from otmTypeahead.js
* Split a utility from BaconUtils.js
* Rename `search-field-group` to `autocomplete-group` and move to `layout.scss` so it can be shared
* Update modeling styles
> Support for boundary autocomplete

- opentreemap/treemap/decorators.py
- opentreemap/treemap/exceptions.py
Replace FeatureNotEnabledException by PermissionDenied,
which django magically translates into a 403 Forbidden,
and returns the 403.html template.
--
Connects to OpenTreeMap/otm-addons#1359
Depends on OpenTreeMap/otm-addons#1371
Depends on OpenTreeMap/otm-website#146
> Support for modeling module

- opentreemap/treemap/js/src/base.js
Add polyfill for `String.startsWith()`, not supported by IE 11.
Note: I verified that search now works on IE 11.
Connects OpenTreeMap/otm-clients#328
> Fix search for IE 11

- opentreemap/treemap/lib/user.py
- opentreemap/treemap/templatetags/util.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/util.py
- opentreemap/treemap/views/misc.py
- opentreemap/treemap/views/user.py
The edits page had exceptionally poor performance when paging beyond the first
few pages, to the point that the requests would time out when attempting to
reach pages past the first dozen or so.
This is primarily caused by the complex query we use to ensure that users only
see edits for fields they have permission to view, but was greatly exacerbated
by the use of `OFFSET` to get pages beyond the first, which requires the
database to retrieve and discard all rows for all previous pages.
By relying on the fact that we show edits in a deterministic order (newest to
oldest), we can switch from passing a page parameter to passing the starting
`Audit.id` and eliminate the `OFFSET`, making performance on each page roughly
equal.
One downside of this is that we need to keep track of the previous …
> Improve performance of instance and user edits pages

- opentreemap/treemap/instance.py
- opentreemap/treemap/js/src/lib/imageUploadPanel.js
- opentreemap/treemap/js/src/user.js
- opentreemap/treemap/templates/treemap/partials/upload_image.html
- opentreemap/treemap/templates/treemap/user.html
Add `InstanceBounds.create_from_geojson()`
* For now, require a `FeatureCollection` containing `Polygon`s
Refactor (slightly) `treemap/js/src/lib/imageUploadPanel.js` and `treemap/partials/upload_image.html`:
* Template's `accept` argument defaults to images but can specify another file type
* Show errors in the modal unless specified otherwise
* Clean up the formatting
Tweak `user.js` image upload to show errors in the modal and remove unused `show` option
> Support for updating instance bounds

- opentreemap/treemap/instance.py
- opentreemap/treemap/tests/test_instance.py
While you can't currently delete a species via the UI, you'll be able to someday. And we sometimes need to delete them behind the scenes. Without this change, the previous species list is not removed from browser-local storage so the deleted species is still shown.
> Change species thumbprint if a species is deleted

- assets/css/sass/partials/pages/_modeling.scss
- fixes https://github.com/OpenTreeMap/otm-addons/issues/1378
- fixes https://github.com/OpenTreeMap/otm-addons/issues/1390
Button now has the border below it consistent with the toolbar:
The sidebar will now span the full height available to it:
Additionally, the scenario summary is no longer hidden below the planting areas legend. I don't believe this has been previously documented as an issue. It was always there, just being covered by the legend. This is also only visible when in a scenario.
> fixes modeling toolbar button height and various sidebar issues

- assets/css/sass/partials/pages/_scenarios.scss
fixes https://github.com/OpenTreeMap/otm-addons/issues/239
I added a min-width to the input and made the padding small on the input-addon. The input will be big enough for both imperial and metric.
> fixed diameter inputs so in vs cm doesnt break layout

- assets/css/sass/partials/pages/_modeling.scss
fixes https://github.com/OpenTreeMap/otm-addons/issues/1388
Added some media queries to fix the overlapping issue. Since modeling is not fully mobile responsive I worried only about small desktop - tablet size screens.
> fixed issue where modeling toolbar elements overlapped less than 992px

- opentreemap/api/instance.py
- opentreemap/api/tests.py
When creating or updating a tree, the iOS app sends only fields known to be writable by the current user. Previously all writable fields had DB `FieldPermission` objects, but after some recent changes that is no longer true for `plot.geom`. So for newly-created treemaps users can't create trees with the iOS app because `plot.geom` is not posted to the back end.
We now have a well-defined category of "always-writable" fields, which includes `plot.geom`. So,including always-writable fields in the data returned by the API "Instance info" endpoint allows the iOS app to once again post `plot.geom` to the back end.
I abstracted the function `add_perms` from the current code (without changes), and call it twice -- once with `FieldPermission` objects from the database (as before) and once with …
> Include always-writable fields in data returned by API "Instance info endpoint"

- opentreemap/api/instance.py
The iOS app still enforces photo permissions using the old-style `treephoto.image` permission, so set that permission.
Testing:
1. Run OTM without these changes
1. Create a new instance
1. For the "Editor" role, turn off the "Can Add Tree Photo" permission
1. Assign a user the "Editor" role
1. From the iOS app, log in as that user and load the instance
1. Click "Add", place a tree, and click "Next". The "Picture" field should incorrectly say "Tree Picture", and allow you to try adding a photo, but the upload should fail.
1. Repeat steps 5-6 with these changes -- the "Picture" field should say "Picture cannot be changed".
1. For the "Editor" role, turn on the "Can Add Tree Photo" permission
1. Repeat steps 5-6 -- you should be able to create a tree with a photo
(Note I discovered …
> In API, set tree photo permission for iOS app versions <= 2.6.0

- opentreemap/treemap/decorators.py
We already have code which fetches a role given an instance and any type of user, so use that rather than relying on `request.instance_user`, which is not always set by `instance_request`.
Connects #2951
> Get role more robustly in requires_permission decorator

- opentreemap/treemap/ecobackend.py
- opentreemap/treemap/ecocache.py
- opentreemap/treemap/species/codes.py
- opentreemap/treemap/tests/test_ecobenefits.py
* Note that the ecoservice caches i-Tree code overrides for all instances, and that invalidating the cache reloads overrides for all instances.
* Store in Redis an `itree_code_override_rev` cache buster for all instances
* When a Django app launches, store the current value of the cache buster in a static variable
* Create signal handlers so that any `ITreeCodeOverride` change increments the cache buster in Redis
* When making any ecoservice call, if the cache buster is stale, invalidate the ecoservice cache
Here's an example of how this works with 2 app servers, A and B:
1. A calls `_init_ecoservice_cache_handling`, setting the Redis rev and `my_itree_code_override_rev` to 1.
1. B calls `_init_ecoservice_cache_handling`, reading the Redis rev and setting `my_itree_code_override_rev` to …
> Invalidate ecoservice cache when an i-Tree code override is created

- opentreemap/treemap/ecocache.py
In the previous implementation, top-level Django app initialization code called Redis. That broke deployment because the Redis server was not available. Refactor to initialize `rev` values lazily.
Testing is the same as in #2953:
1. Restart celery
1. Create or use an instance centered on Seattle
1. Add a tree in downtown Seattle with species Acer rubrum and diameter 11 inches, and note your total ecobenefits
1. Do a bulk import of users/rmohr/data/importer/acerRubrumOverride.csv (note you may need to merge the species before adding it to the treemap)
1. Reload the map page -- the total ecobenefits should have changed
Connects #1975
> Update ecoservice cache invalidation to not call Redis in top-level code

- opentreemap/api/plots.py
- opentreemap/api/tests.py
The android app sends `updated_by`. It doesn't know it's a foreign key,
neither does the api, so it gets set to the `id` rather than the model.
This causes a `ValueError` in auditing.
The api already has a list of attributes to ignore.
`updated_by` can be safely ignored because it is set in auditing.
Same for `updated_at`. Since they are supposed to be set in auditing,
they really should both be ignored.
So ignore them.
--
Connects to https://github.com/OpenTreeMap/otm-android/issues/303
Connects to https://github.com/OpenTreeMap/otm-android/issues/304
> Ignore updated_at and updated_by field values when updating plots via the API.

- opentreemap/api/instance.py
**NOTE**: In my testing, this PR resolves the issue reported in https://github.com/OpenTreeMap/otm-ios/issues/346 without impacting the Android application but I am not sure if this is the best solution to the problem.
Versions of the iOS application use the presence of identifiers in the `fields` dictionary returned from the instance info API to determine whether or not a field in the search configuration should be invisible to the currently logged in user. The identifiers in this commit were not included in fields dictionary for instances created after the transition to model-level permissions, but the identifiers are referenced in the default mobile search configuration. Species and photos are always visible, so we can hard code a non-None value for these identifiers to restore the …
> Restore instance API field identifiers

- opentreemap/exporter/tasks.py
- opentreemap/exporter/tests.py
Use `Model.visible_fields(user)` instead field permissions in
exporter in order to get fields that are always writable.
This also gives us a bunch of fields we don't want, so I added some
more fields to the list to be omitted.
Connects to #2538
Connects to OpenTreeMap/otm-clients#341
> Fix exporting of geometry fields for tree exports.

- opentreemap/treemap/js/src/lib/geometryMover.js
- opentreemap/treemap/js/src/lib/inlineEditForm.js
- opentreemap/treemap/js/src/lib/plotMarker.js
- opentreemap/treemap/js/src/mapFeatureDetail.js
* Remove marker dragging workaround now that we're on Leaflet 1.0
* Remove `InlineEditForm.onSaveAfter` in favor of the existing `InlineEditForm.saveOkStream`
* In `geometryMover.js` rename `onSaveAfter` methods to `onSaveOk`
* In `geometryMover.js` replace `onCancel` with `isCancel` argument to `disable` (this will be important when showing the area of a polygon as it is modified)
* Refactor `geometryMover.js` so that `onSaveOk` is called before `disable`, fixing #2975
Connects #2975
> Show polygon outline correctly after modify + save + modify

- opentreemap/treemap/js/src/lib/addResourceMode.js
- opentreemap/treemap/js/src/lib/geometryMover.js
- opentreemap/treemap/js/src/lib/polylineEditor.js
- opentreemap/treemap/js/src/lib/utility.js
- opentreemap/treemap/js/src/mapFeatureDetail.js
- opentreemap/treemap/lib/map_feature.py
- opentreemap/treemap/templates/treemap/partials/map_add_resource.html
- opentreemap/treemap/templates/treemap/partials/resource_detail.html
- opentreemap/treemap/views/misc.py
* Use `leaflet-draw` "edit vertex" events for notifications when a polygon vertex is moved
* Add `getPolygonDisplayArea` utility function (previously in modeling code)
* `polylineEditor.js` exports `areaStream`, with current area as user modifies polygon
* `polylineEditor.js` retains `initialArea` so display can be restored if polygon editing is canceled
* Use `areaStream` to show area in "Resource Detail" table
* Use `areaStream` to show area in "Add Resource" sidebar
Testing:
* On resource detail page:
* area should update as you edit the polygon
* area should revert when you cancel editing or "Cancel Move Location"
* area should not revert when you save
* multiple edit/save cycles should work correctly
* When adding a resource, area should update as you edit the polygon
Connects #2905
> As GSI polygon is modified, display its area

- opentreemap/treemap/js/src/lib/mapFeatureDelete.js
- opentreemap/treemap/js/src/lib/urlState.js
- opentreemap/treemap/js/src/lib/utility.js
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/views/map_feature.py
- opentreemap/treemap/views/tree.py
Preserve location when clicking "Explore Map" from a detail page
* When loading a detail page, construct `map_query` string and append to "Explore Map" URL.
Preserve location after deleting a map feature
* Extract `U.makeZoomLatLngQuery` from `urlState.js`
* Use it in `mapFeatureDelete.js` to zoom map correctly after deleting a map feature
Connects #2934
> Preserve location when going from plot detail to main map

- opentreemap/treemap/tests/ui/__init__.py
- opentreemap/treemap/tests/ui/uitest_map.py
The failure suggests that when typing "32" for diameter and hitting "Save", the new diameter is sometimes not saved. My only thought is that the "save" event is handled before the diameter calculator's JS code has finished updating everything. So, wait for the circumference value to be displayed before continuing.
Also fixed an unrelated oversight in `browse_to_instance_url`.
Connects #2982
> Attempt to fix intermittent test failure

- opentreemap/opentreemap/urls.py
- opentreemap/treemap/models.py
- opentreemap/treemap/routes.py
- opentreemap/treemap/tests/__init__.py
- opentreemap/treemap/tests/test_ecobenefits.py
- opentreemap/treemap/tests/test_instance.py
- opentreemap/treemap/tests/test_urls.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/views/misc.py
- Encapsulate anonymous boundary logic in the Boundary model
- Anonymous boundary creation view and url
- Can get geojson from an anonymous boundary that is not part
of the instance.boundaries.
- Anonymous boundaries do not affect thumbprint.
--
Depends on OpenTreeMap/otm-addons#1452
Connects to #2992
> Anonymous (formerly ad hoc) boundary endpoint

- assets/css/sass/partials/pages/_map.scss
- opentreemap/treemap/js/src/lib/MapManager.js
- opentreemap/treemap/js/src/lib/polylineEditor.js
Leaflet Draw has different polygon vertex icons for touch screens and non-touch screens, and decides which to use based on Leaflet's `L.Browser.Touch`. But with current browsers and Leaflet 1.0.3, `L.Browser.Touch` is `true` for a browser that supports touch even when you're using a non-touch device. That's why we get giant vertex icons on desktop devices. Since for us polygon editing is unlikely to be done via touch, always use the non-touch icons.
Also change the default 8x8 square into a 10x10 circle (with help from CSS on .leaflet-editing-icon)
Connects #3030
Depends on OpenTreeMap/otm-addons#1459
Testing: 
* Create a Bioswale. When editing the area the vertices should be small circles.
* Go to its detail page, Edit, and Move Location. The vertices should be small circles.
> Change default vertex icons for drawing/editing polygons

- opentreemap/treemap/js/src/lib/utility.js
The `getPolygonDisplayArea` function began returning zero when passed the results of calling `getLatLngs` on a boundary polygon. The `getLatLngs` method was producing a doubly-nested array and the `geodesicArea` function only works on a 1-dimensional array. I fixed `getPolygonDisplayArea` by making it recursively descend through an arbitrary number of nested arrays and sum the results of calling `geodesicArea` on any "leaf" array it finds.
---
- Selecting a modeling distribution area created by loading a boundary should show a popup with the correctly calculated area.
- The area should still be correctly calculated when editing a GSI polygon.
I tested the modeling case on PhillyTreeMap by selecting the city boundary which reports 3,819,786,060 sq/ft
Wikipedia says that the area of …
> Fix polygon area calculation

- opentreemap/treemap/lib/udf.py
- opentreemap/treemap/migrations/0044_userdefinedfielddefinition_is_protected.py
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/udf.py
- opentreemap/works_management/models.py
Adds a new field `is_protected` to the `UserDefinedFieldDefinition` Model which prevents anyone from deleting the UDF. A new property has also been added to the "choice" UDF called `protected_choices` which prevents renaming and deletion of the UDF choice.
The syntax implemented is based on feedback from #3022.
Connects #2996
For this iteration, I decided to disable renaming and deleting protected UDFs & choices for **everyone**. In the future, it might make sense to waive this restriction for admins and superusers.
This *should* work out of the box with collection UDFs (all unit tests pass) but I have not created unit test cases specifically to verify this.
* Run migrations
* Execute UDF test suite
```
./scripts/manage.sh test treemap.tests.test_udfs
```
* Create a protected UDF choice …
> Implement protected UDF definitions and choices

- opentreemap/treemap/js/src/lib/plotMarker.js
- opentreemap/treemap/js/src/mapPage/addMapFeature.js
- opentreemap/treemap/js/src/mapPage/addResourceMode.js
- opentreemap/treemap/js/src/mapPage/addTreeMode.js
- opentreemap/treemap/js/src/mapPage/browseTreesMode.js
- opentreemap/treemap/js/src/mapPage/drawAreaMode.js
- opentreemap/treemap/js/src/mapPage/editAreaMode.js
- opentreemap/treemap/js/src/mapPage/editTreeDetailsMode.js
- opentreemap/treemap/js/src/mapPage/modes.js
- opentreemap/treemap/js/src/treeMap.js
- opentreemap/treemap/templates/treemap/map-browse-trees.html
Functional changes:
* Hide "Details" sidebar when switching out of browse or edit mode
* Don't update URL when adding a tree or resource from the treemap page. The only reason for having `m=addTree` in the URL is so we can initiate adding a tree or resource from another page. There's no value in updating the URL when adding a tree or resource from the treemap page, so don't.
Simplify and clarify `modes.js` and mode modules
* Refactor activation methods to use options instead of named arguments
* Pass `activateBrowseTreesMode` to "add" modes rather than `onClose` function
* Cleaner mode transitions for mobile
* Remove logic to show accordion buttons -- they were never hidden anyway
* Use `dom.` pattern rather than passing selectors in `options`
* Require `plotMarker.js` rather than passing …
> Mode change cleanup

- opentreemap/treemap/tests/ui/__init__.py
- opentreemap/treemap/tests/ui/uitest_map.py
When you're adding a tree we no longer put `m=addTree` in the URL. So check whether the "Add Tree" sidebar is visible.
> Fix UI test

- opentreemap/opentreemap/urls.py
- opentreemap/treemap/templates/instance_base.html
- opentreemap/works_management/js/src/workOrders.js
- opentreemap/works_management/routes.py
- opentreemap/works_management/templates/works_management/work_orders.html
- opentreemap/works_management/urls.py
- opentreemap/works_management/views.py
Testing:
Logged in as a user whose role has "Works Management" permission (e.g. `Administrator`)
* You should see a "Work Orders" menu item
* Clicking it should take you to the (vanilla) Work Orders page
* When the Work Orders page is displayed:
* You should see "I am working" toast (showing that JS code is hooked up right)
* The "Work Orders" menu item should be highlighted
Logged in as a user whose role lacks "Works Management" permission (e.g. `Editor`)
* You should not see a "Work Orders" menu item
* Loading `/work-orders/` should give a "Page Restricted" page
Connects #3052
> Skeletal Work Orders page

- opentreemap/treemap/instance.py
- opentreemap/treemap/migrations/0045_sequence_number.py
- opentreemap/works_management/migrations/0002_reference_number_field.py
- opentreemap/works_management/migrations/0003_reference_number_default.py
- opentreemap/works_management/migrations/0004_reference_number_unique.py
- opentreemap/works_management/migrations/0005_blank_fields.py
- opentreemap/works_management/models.py
- opentreemap/works_management/tests.py
Adds a new reference number field on WorkOrder and Task models, which
is sequential (starting from 1), and is distinct per instance.
Migrations have been split up into 3 parts:
1. Add new fields (nullable)
2. Set default values on null fields
3. Add unique key and non-nullable constraint
Connects #3049
* Run migrations
* Run unit tests
```
> ./scripts/manage.sh test works_management.tests
```
> Create sequential Work Order numbers and Task numbers per instance

- opentreemap/treemap/js/src/lib/baconUtils.js
- opentreemap/treemap/js/src/lib/boundarySelect.js
- opentreemap/treemap/js/src/lib/mapPage.js
- opentreemap/treemap/js/src/lib/otmTypeahead.js
- opentreemap/treemap/js/src/lib/searchBar.js
- opentreemap/treemap/js/src/mapPage/drawAreaMode.js
- opentreemap/treemap/js/src/mapPage/editAreaMode.js
- opentreemap/treemap/js/src/mapPage/locationSearchUI.js
- opentreemap/treemap/js/src/treeMap.js
- opentreemap/treemap/search.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/views/misc.py
Here is what it does.
Polygons are completed by user events:
- `mapPage/drawAreaMode.onDrawComplete`
- `mapPage/editAreaMode.saveArea`
When polygons are completed, `locationSearchUI.completePolygon` POSTs
to the backend `anonymous_boundary` url, and adds the polygon to the map.
The stream created by `anonymous_boundary` tells `drawAreaMode` to
set some state and activate browse-trees mode.
After some mapping, it also gets plugged into a bus, which `mapPage`
feeds into `boundarySelect.init`, after some merges and transformations.
`mapPage` also feeds it into a stream that triggers backend searches.
TODO: ajax errors from `anonymous_boundary` are presently ignored.
When `anonymous_boundary` succeeds, it returns `{"id": <boundary id>}`.
This is processed as follows:
- `onValue`,
* inject the …
> anonymous boundary for custom area

- opentreemap/works_management/migrations/0006_task_priority.py
- opentreemap/works_management/models.py
Connects #3048 
Since WM has not been deployed to production I decided not to make the priority field nullable.
* Run migrations
> Add priority field to WM Task model

- opentreemap/opentreemap/middleware.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/js/src/lib/MapManager.js
- opentreemap/treemap/tests/test_middleware.py
- package.json
* Update browser detection regex
* Include promise polyfill
* Declare IE11 compatibility in HTML header so that `indexOf` is defined (http://stackoverflow.com/a/41830202)
* Require IE 11 even in debug mode
* Update tests
Connects OpenTreeMap/otm-clients#353
> Fix IE11 issues

- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/decorators.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/tests/test_util.py
- opentreemap/treemap/udf.py
- opentreemap/treemap/util.py
- opentreemap/works_management/forms.py
- opentreemap/works_management/migrations/0006_task_fields_null_blank_default.py
- opentreemap/works_management/migrations/0007_merge.py
- opentreemap/works_management/migrations/0008_task_choice_blank_false.py
- opentreemap/works_management/models.py
- opentreemap/works_management/routes.py
- opentreemap/works_management/tests.py
- opentreemap/works_management/urls.py
- opentreemap/works_management/views.py
Migrations:
- Make `required_on` and `closed_on` nullable
- Make `Task.work_order` required
- Give the note fields a default value
- Merge
- Resolve that django forms make choice fields required
even if the model field has a default, no matter what blank is
Other apps:
- Change the 404 decorator to receive additional global errors
along with field errors
- Provide for model names in the form of <app_name>.<ModelName>
in `treemap.util`, `treemap.udf`, and `treemap.instance`
- Safe generic utility to get models by app name
- A new setting to interface `treemap` to other apps in a
more loosely coupled way
- Make UDFs safer by not instantiating the model
- Add `clz` kwarg to `treemap.instance.get_or_create_udf`,
for cases where the caller already has the model class
Works management:
- Move …
> create tasks from search

- assets/css/sass/partials/_header.scss
Easier to add an `!important` than to figure out where `style="display: inline"` is being assigned to the dom element and make it stop doing that.
--
Connects to #3063
> Polygonal search tool not available on xs mobile

- opentreemap/treemap/js/src/lib/searchBar.js
Dereferencing an undefined `options` variable resulted in a
JS stacktrace.
--
Connects to #3083
> Fix search from detail page

- opentreemap/geocode/views.py
OMGEO calls `urllib.urlencode`, which calls `str()` on the address and errors out.
Solution is to encode the address using UTF-8.
Connects #3087
> Support address search with accented characters

- opentreemap/opentreemap/celery.py
In a standalone installation Celery failed to launch, giving the error below. Delaying the import of `register_celery_events` fixes the problem.
```
Traceback (most recent call last):
File "/usr/local/bin/celery", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 30, in main
main()
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 81, in main
cmd.execute_from_commandline(argv)
File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 793, in execute_from_\
commandline
super(CeleryCommand, self).execute_from_commandline(argv)))
File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 309, in execute_from_co\
mmandline
argv = self.setup_app_from_commandline(argv)
File …
```
> Prevent error on Celery launch

- assets/css/sass/partials/_header.scss
- assets/css/sass/partials/_layout.scss
- opentreemap/treemap/js/src/mapPage/editAreaMode.js
- opentreemap/treemap/templates/instance_base.html
* Change "Search" button from `a` to `button` to allow easy disabling
* Disable/enable searching on activate/deactivate of "edit area" mode
* Tweak alignment of top controls
Connects #3092
> Disable search while editing custom area

- assets/css/sass/partials/pages/_admin.scss
Use css classes instead of hard-coded styles to hide and show errors
on the Custom Field management page.
Additionally, when editing a choice custom field, hide the choice trash-can button on the sole remaining
pre-existing choice.
--
Connects to OpenTreeMap/otm-addons#1483
> Custom Field management page styling

- opentreemap/treemap/routes.py
Normally this cookie would already be present from other actions / pages, which have forms that use the `{% csrf_token %}` template tag, but if the Map page is the first page visited in a session it would not be set.
This wasn't noticed before because until polygonal search was added, there were no actions on the map page that required a CSRF token but did not first require login (which would set the cookie).
Adding this decorator to the route forces the cookie to be set, fixing the issue.
Connects to #3093
> Force CSRF cookie to be sent on Map Page

- opentreemap/manage_treemap/routes.py
- opentreemap/manage_treemap/templates/manage_treemap/management_base.html
- opentreemap/manage_treemap/tests.py
- opentreemap/manage_treemap/urls.py
- opentreemap/manage_treemap/views.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/opentreemap/urls.py
- opentreemap/treemap/templates/instance_base.html
Name it `manage_treemap` because `manage` is reserved by Django and `management` invites confusion with the `management` directory containing Django management commands.
Files:
* Base management template. Currently all menu items are added from `otm-addons`, but ultimately most will be configured here.
* First url, route, view, and test
Testing:
* Verify that the "Manage" link in the top menu loads the `/management/site-config` page, and that the Management menu looks right.
Connects OpenTreeMap/otm-addons#1480
> Add manage_treemap app

- opentreemap/treemap/js/src/lib/search.js
- opentreemap/treemap/search.py
- opentreemap/treemap/tests/test_search.py
Changes
------------
Searches that include multiple queries on a single collection UserDefinedFieldDefinition need to be grouped together into a single subquery.
The previous search created a separate subquery for each one, and so incorrectly matched entities that had one UserDefinedCollectionValue that matched the action, another that matched the date, but none that matched both.
This fix necessitated test changes.
Now also includes a JS fix that threw, and prevented the frontend from submitting a search.
Testing Notes
------------------
Note that the fix does not cause the search cache to be flushed, so you will see the same wrong results if you execute the exact same query.
Anonymous boundary search is an easy way to game the cache. Just change the boundary a little each time.
I tried …
> Stewardship with date search fix

- opentreemap/manage_treemap/js/src/basicInfo.js
- opentreemap/manage_treemap/js/src/branding.js
- opentreemap/manage_treemap/js/src/embed.js
- opentreemap/manage_treemap/js/src/greenInfrastructure.js
- opentreemap/manage_treemap/js/src/link.js
- opentreemap/manage_treemap/js/src/units.js
- opentreemap/manage_treemap/routes.py
- opentreemap/manage_treemap/templates/manage_treemap/basic.html
- opentreemap/manage_treemap/templates/manage_treemap/branding.html
- opentreemap/manage_treemap/templates/manage_treemap/embed.html
- opentreemap/manage_treemap/templates/manage_treemap/green_infrastructure.html
- opentreemap/manage_treemap/templates/manage_treemap/link.html
- opentreemap/manage_treemap/templates/manage_treemap/management_base.html
- opentreemap/manage_treemap/templates/manage_treemap/partials/diversion_rate.html
- opentreemap/manage_treemap/templates/manage_treemap/partials/map_feature_type_checkbox.html
- opentreemap/manage_treemap/templates/manage_treemap/partials/should_show_eco.html
- opentreemap/manage_treemap/templates/manage_treemap/partials/units_table.html
- opentreemap/manage_treemap/templates/manage_treemap/units.html
- opentreemap/manage_treemap/tests/test_general.py
- opentreemap/manage_treemap/tests/test_gsi.py
- opentreemap/manage_treemap/tests/test_units.py
- opentreemap/manage_treemap/tests/test_urls.py
- opentreemap/manage_treemap/urls.py
- opentreemap/manage_treemap/views/__init__.py
- opentreemap/manage_treemap/views/green_infrastructure.py
- opentreemap/manage_treemap/views/management.py
* Restore test of `/management` URL now that `site_config` is present
Also add "Units" page.
Only the final two commits are relevant.
Required by OpenTreeMap/otm-addons#1488
> Management pages in "General" category

- opentreemap/manage_treemap/js/src/udfs.js
- opentreemap/manage_treemap/templates/manage_treemap/partials/fields/udf_choice_cell.html
- opentreemap/manage_treemap/templates/manage_treemap/partials/fields/udf_choice_existing.html
- opentreemap/manage_treemap/templates/manage_treemap/partials/fields/udf_choice_item.html
- opentreemap/manage_treemap/templates/manage_treemap/search_fields.html
- opentreemap/manage_treemap/templates/manage_treemap/udfs.html
- opentreemap/manage_treemap/views/udf.py
Changes
-------
- Added docstrings in the endpoint explaining what data is expected
- Removed markup for the delete choice confirmer from the template
- Removed markup that cued the JavaScript to pop up the delete choice
confirmer
- Added markup for a trash div to hold pending deletes
- Removed a JavaScript TODO for the Save Confirmer in favor of an issue,
OpenTreeMap/otm-addons#1493
- Replaced JavaScript code dealing with the confirmer with code
to stage deletions to a trash div
- Related JavaScript changes for the content of the Save Confirmer,
and fixing the dom up after Save or Cancel
--
Connects to OpenTreeMap/otm-addons#1482
> Defer choice delete until Save

- opentreemap/treemap/js/src/mapPage/editTreeDetailsMode.js
We needed to call `map.invalidateSize()` after changing the map height
Connects to #3043
> Fix map height during move tree on mobile

- assets/css/sass/partials/pages/_content.scss
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/partials/About.html
- opentreemap/treemap/templates/treemap/partials/FAQ.html
- opentreemap/treemap/templates/treemap/partials/Resources.html
- opentreemap/treemap/tests/test_views.py
Changes
-------
- Data migration to add default Resources, About, and FAQ pages
to instances that don't have them
- Styling for the `<dl>` in the About page
Testing Notes
-------------
Before running the migration, find both instances that do and
that do not have static pages with these names defined.
After running the migration, make sure that
- instances that did not have these pages now do
- the three pages have the right content
- the three pages are formatted nicely
- instances that already had custom versions of these pages
still have their custom pages
--
Connects to #1386
> Default static pages

- opentreemap/treemap/templates/treemap/field/attrs.html
Added `|force_escape` to `data-value` in `treemap/field/attrs.html`
in order to get the static page editor to send html escaped
tag attributes.
`|escape` had no effect.
`|force_escape` is not double-escaping.
Tested with advanced search, add a tree, tree quick edit,
the tree details page, the units management page, and the
custom fields management page.
--
Connects to OpenTreeMap/otm-addons#1506
> Edit default static page

- opentreemap/otm1_migrator/migration_rules/treezilla.py
The maximum diameter and height in the Treezilla species fixtures is in meters but the canonical units in OTM2 are feet for height and inches for diameter.
The `else` clause was copied from the default migration rules.
---
I tested this by following the migration steps in https://github.com/OpenTreeMap/otm-clients/blob/538bcbc730c386eab3dd6dea69ea3b7de9c84bd0/treezilla/migration/README.md up through "Run The Migration" with the following changes.
- I skipped deleting boundaries.
- I only copied the species fixture JSON file to my VM
- I used this `config.json`
```json
{
"rule_module": "otm1_migrator.migration_rules.treezilla",
"species_fixture": "local/fixtures/species.json"
}
```
On the `develop` branch, the migration produces rows in the species table with unconverted measurements:
``` …
```
> Modify Treezilla species import to convert units

- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/views/misc.py
Fetching every map's tree/plot count was too slow for use in the new marketing site (taking 2-10 seconds).
Since we already cache plot count, I switched to getting the `plot_count` from the cache, and entirely removed the `tree_count`.
Required by https://github.com/OpenTreeMap/otm-website/pull/178
Connects to OpenTreeMap/otm-website#176
> Use cached plot count in public instances GeoJSON view

- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
When `row._validate_proximity` gets called during the commit phase,
exclude previously committed plots in the same csv from
the proximity check.
--
Connects to OpenTreeMap/otm-addons#1519
> Cancel importer proximity check within same csv

- opentreemap/treemap/tests/test_map_feature.py
Have to override `FEATURE_BACKEND_FUNCTION=None`
in order to `add_map_feature_types`.
Fixed this in order to be able to write a test for the real issue
that also needs to use `add_map_feature_types`.
--
Connects to OpenTreeMap/otm-addons#1394
> Fix skipped test

- opentreemap/treemap/ecobenefits.py
- opentreemap/treemap/lib/__init__.py
- opentreemap/treemap/templates/treemap/partials/eco_benefits.html
- opentreemap/treemap/tests/test_ecobenefits.py
- opentreemap/treemap/tests/test_map_feature.py
- opentreemap/treemap/views/tree.py
`treemap.lib.format_benefits` now calculates `'benefits_total_currency'`
correctly, and also adds its formatted results to
`rslt['benefits']['all']['totals']`.
>`format_benefits` now omits non-annual currency from total currency based on a `dict` in `BenefitCategory`. I hope that the code and variable names make this self-explanatory, but if they do not, it's fair to ask for a comment in the code.
`treemap/partials/eco_benefits.html` adjusted accordingly.
Total currency calculation no longer needed in `treemap.views.tree`.
Added a very basic resource ecobenefits test,
and a test for total currency for both plots and resources,
which failed before correcting `format_benefits`.
--
Connects to OpenTreeMap/otm-addons#1394
> ecobenefits totals

- opentreemap/treemap/udf.py
There is some data in the production database where the value of a multichoice field audit is the string "null". Adding a None check to the `clean_value` function prevents an exception where code further down in the function expects the value to be iterable.
---
`/greenprintmaps/features/2081911/`
The production data has an audit that looks like this
```
otm=# select field, previous_value, current_value  from treemap_audit where model = 'Tree' and model_id = 1814485 and previous_value = 'null' order by created;
field         | previous_value | current_value
----------------------+----------------+---------------
udf:Name of Project: | null           | null
```
On the `develop` branch, loading the detail page for this plot crashes. On the PR branch, it loads properly.
---
Connects to #1526
> Handle null multichoice value

- requirements.txt
This release includes a required fix to the ESRI geocoder integration.
---
Connects to https://github.com/OpenTreeMap/otm-cloud/issues/384
> Update to python-omgeo 2.0.0

- opentreemap/geocode/tests.py
The updated ESRI World Geocoding Service returns a slightly different lat/lng for the old Azavea office address.
---
Connects to https://github.com/OpenTreeMap/otm-cloud/issues/384
> Fix geocode test to be compatible with python-omgeo 2.0.0

- opentreemap/treemap/templates/instance_base.html
- opentreemap/treemap/views/misc.py
- webpack.common.config.js
We had mistakenly omitted using the `[chunkhash]` in the Webpack SASS bundle.
Adding it in allows us to use the bundle name as a cache-buster URL parameter for the dynamically computed SASS bundle.
Required by https://github.com/OpenTreeMap/otm-cloud/pull/382
Connects to #3143
> Add checksum to URL for both static and dynamic SASS bundles

- README.md
- opentreemap/opentreemap/celery.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/templates/treemap/partials/paging_controls.html
- opentreemap/treemap/templatetags/urls.py
- opentreemap/treemap/tests/test_templatetags.py
- requirements.txt
See the description of #3156 for a detailed checklist of updates.
---
- django-contrib-comments and django-threadedcomments
- Commenting works on the tree detail page.
- Comment moderation works on the mangement page.
- django-redis
- Ran `redis-cli -d 1 monitor`on the services VM and:
- Verified that eco benefits are written to and read from the cache.
- Verified the addons health check cache test.
- django-js-reverse
- Adding a tree and choosing "continue editing" works. (This action depends on reversing a URL in the client https://github.com/OpenTreeMap/otm-core/blob/28cd298dd5a72c7e4039c86a8275fdb62a51ea49/opentreemap/treemap/js/src/mapPage/addMapFeature.js#L275)
- django-queryset-csv
- Can export from the map page.
- Can export from the users management page.
- Can export from the …
> Update or remove python dependencies to ensure Django 1.11 compatibility

- opentreemap/appevents/models.py
- opentreemap/manage_treemap/tests/test_instance_invitations.py
- opentreemap/modeling/tests.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/otm_comments/__init__.py
- opentreemap/otm_comments/forms.py
- opentreemap/registration_backend/urls.py
- opentreemap/registration_backend/views.py
- opentreemap/treemap/audit.py
- opentreemap/treemap/instance.py
- opentreemap/treemap/json_field.py
- opentreemap/treemap/migrations/0001_initial.py
- opentreemap/treemap/migrations/0044_hstorefield.py
- opentreemap/treemap/models.py
- opentreemap/treemap/templates/treemap/settings.js
- opentreemap/treemap/templates/treemap/user.html
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/templatetags/partial.py
- opentreemap/treemap/tests/test_json_field.py
- opentreemap/treemap/tests/test_search.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/tests/ui/uitest_map.py
- opentreemap/treemap/tests/unit_test_urls.py
- opentreemap/treemap/udf.py
- opentreemap/treemap/units.py
- opentreemap/treemap/urls.py
- opentreemap/treemap/views/map_feature.py
- requirements.txt
Updates Django to 1.11 and fixes a number of issues related to / uncovered by / blocking the upgrade.
Required by https://github.com/OpenTreeMap/otm-addons/pull/1531
Connects to https://github.com/OpenTreeMap/otm-core/issues/3157
> Update Django to 1.11

- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/views/map_feature.py
We previously added code to protect against the iOS app always sending values for all UDF fields. While this protective code does skip over the values, it only runs after the presence of a `tree:` field in the request triggers the instantiation of a `Tree`, which then gets saved.
In this commit I have added a check to skip field value processing entirely and bypass the creation of a new `Tree` in the situation where the `Tree` does not already exist and the field value is empty.
---
The new unit test will fail if run with the `develop` branch and passes on this branch.
On an instance that has a choice custom field on Tree, adding an empty planting site via the iOS app works correctly.
---
Connects to https://github.com/OpenTreeMap/otm-clients/issues/382
> Skip tree creation if tree UDF values are empty

- opentreemap/treemap/templates/treemap/partials/map_feature_detail_base.html
- opentreemap/treemap/templatetags/comment_sequence.py
- opentreemap/treemap/tests/test_templatetags.py
In my analysis of the template tags in both `django-contrib-comments` and `django-threadedcomments` (the older versions we use and also the latest code in Github) I did not see any code that put comments in a parent-then-children sequence.
---
The test procedure in #3084 should produce correct results.
---
Connects to #3084
> Add template tag to sequence comments in thread order

- opentreemap/registration_backend/views.py
The reverse name of the URL to be loaded after a successful password reset request is `auth_password_reset_done`. The base `PasswordResetView` from `django.contrib.auth` hard codes the reverse name `password_reset_done` that we must override.
--- 
After submitting a password reset request you should be successfully redirected to `/accounts/password/reset/done/`
---
Connects to #3178
> Fix password rest done routing error

- assets/css/sass/partials/pages/_modeling.scss
- opentreemap/modeling/js/src/modeling.js
- opentreemap/modeling/templates/modeling/modeling.html
We extracted the modeling prioritization functionality into a separate demo application. In this commit we link to that application, passing the instance center coordinate so that prioritization starts in the same location as the instance.
After some design iteration we decided to move the scenario burger button to the far left of the toolbar to make room for the new prioritization link.
---
- Create an instance and go to the "Plan" page.
- Create a new plan, then click the "Prioritize plantings" link. You should be taken to treeprioritization.geotrellis.io with the map centered on the same location as the instance
---
Connects to https://github.com/OpenTreeMap/otm-addons/issues/1535
> Add link from modeling scenarios to prioritization demo

- opentreemap/geocode/tests.py
- opentreemap/geocode/urls.py
- opentreemap/geocode/views.py
- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/treemap/js/src/lib/geocoder.js
- opentreemap/treemap/js/src/lib/geocoderUi.js
- opentreemap/treemap/js/src/mapPage/addMapFeature.js
- requirements.txt
This is required to be compliant with the ESRI terms of service.
Some of our uses of geocoding are "use and discard" and we don't need to pass the  `forStorage` flag, so I made it an option to `geocodeStream`. All uses of `reverseGeocodeStream` can be stored in a database, so I made it always pass `forStorage`
Required by https://github.com/OpenTreeMap/otm-addons/pull/1540
Depends on https://github.com/OpenTreeMap/otm-cloud/pull/401
Connects to OpenTreeMap/otm-cloud#309
> Use ESRI credentials when geocoding stored points/addresses

- opentreemap/treemap/tests/test_udfs.py
- opentreemap/treemap/udf.py
The authorizable system sets field values to none if the logged in user is not permitted to see the field. In the case of UDFs, setting a field value to None when the key did not exist in the UDF dictionary was raising a KeyError. This commit avoids the error by checking for the existence of the key before trying to remove it.
---
Connects to #3183
> Update UDFDictionary so that setting key to None does not raise

- opentreemap/manage_treemap/tests/test_instance_invitations.py
- opentreemap/manage_treemap/views/user_roles.py
- opentreemap/treemap/plugin.py
We have decided that instead of notifying every user with management access, which could be a long list of people uninterested or confused by the notification we will instead notify only the person who sent the invitation. Additional recipients can be added by implementing a new plugin function.
---
- Tail the syslog so that you can see the emails being sent.
- Create an instance.
- Invite a user and make them an administrator with management access.
- Invite a third user.
- Accept the invitation sent to the fourth user. Verify that the notification email was sent to just the instance owner.
---
Related to https://github.com/OpenTreeMap/otm-addons/pull/1544
Related to https://github.com/OpenTreeMap/otm-cloud/pull/403
Connects to https://github.com/OpenTreeMap/otm-clients/issues/388
> Make email notifications for accepted invitations pluggable

- opentreemap/importer/models/trees.py
- opentreemap/importer/tests.py
The importer bypasses authorization and was also bypassing the updates to the updated_at and updated_by fields.
---
- Create an instance with two management access users, A and B. Ensure the instance is not in trial mode so that exports are enabled.
- Log in as user A.
- Create a tree with a diameter and export it.
- Modify the exported CSV.
- Remove the stewardship columns
- Change the diameter value
- Log in as user B.
- Import the exported and edited CSV.
- Export once more and compare the two CSVs, verifying that the updated_by and updated_at field values change.
---
Connects to #3171
> Set updated_at and updated_by when bulk updating plots/trees

- opentreemap/treemap/js/src/lib/searchBar.js
Calling `locationTypeahead.clear()` ensures that the search UI is in a consistent state when clicking "Reset" directly after geocoding.
---
- Follow the reproduction steps in https://github.com/OpenTreeMap/otm-core/issues/3125
- Ensure that other location search / reset workflows still work.
---
Connects to #3125
> Clear location search box when clicking Reset

- opentreemap/treemap/lib/tree.py
- opentreemap/treemap/views/map_feature.py
Searches results for trees or green infrastructure resources with missing photos were not updating after adding photos. I resolved this by ensuring that we increment the `universal_rev` after adding a photo.
---
- Create an instance with green infrastructure and enable the GI features.
- Add 2 trees and a GI resource.
- Search for missing photos, should match 2 trees and 1 resource.
- In a separate tab, load the detail page for the GI resource and add a photo.
- Refresh the search page. The missing photo count should drop to 2 trees and 0 resources.
- Repeat the process and add a photo to a tree. The count should drop to 1 tree and 0 resources.
- Use a mobile app to add a photo to the remaining tree. After refreshing the map page the count should drop to 0 trees and 0 resources.
--- …
> Fix stale search results by incrementing rev after adding a photo

- assets/css/sass/partials/pages/_admin.scss
- opentreemap/manage_treemap/templates/manage_treemap/management_base.html
- Make management navigation sidebar scrollable
- Fix padding on last link collapsible groups
- Prevent map title from being visible when the sidebar is collapsed
Connects to OpenTreeMap/otm-addons#1460
> Fix styling issues on management pages

- opentreemap/treemap/instance.py
- opentreemap/treemap/models.py
- opentreemap/treemap/tests/test_views.py
- opentreemap/treemap/views/misc.py
To test:
Search for 'Cockspur Hawthorn' on an international map. On the `develop` branch there should two identical entries, and on this branch one entry should include the variety as part of the scientific name.
Connects to #2920
> Add 'other_part_of_name' (Variety) to species scientific name

- opentreemap/treemap/js/src/lib/geocoderUi.js
- opentreemap/treemap/js/src/lib/otmTypeahead.js
- opentreemap/treemap/js/src/lib/search.js
- opentreemap/treemap/js/src/lib/searchBar.js
- opentreemap/treemap/js/src/lib/urlState.js
- opentreemap/treemap/js/src/mapPage/locationSearchUI.js
Adds a new `a` parameter to the URL which is set when there is a
non-boundary value in the location typeahead.
On page load on the map page, if the `a` parameter is present in the URL
and no boundary filter is present, we geocode the address and display a map
pin (which will also recenter the map on the pin).
Connects to #1123
> Store geocoded address in URL when searching and show on page load

- opentreemap/api/plots.py
- opentreemap/api/tests.py
- opentreemap/api/views.py
Previously, validation errors in the plot create and update views were not being
caught, resulting in a 500 error being logged in Rollbar.
Updating these views to properly handle the validation errors required a fix to
the `transform_plot_update_dict` function to check for the existence of a key
before trying to read it from the plot dict.
---
Use a mobile app and attempt to both create and update a tree with zero diameter and verify that the API response has a 400 status code.
---
Connects to https://github.com/OpenTreeMap/otm-ios/issues/353
> Return plot create/update validation errors with a 400 status

- opentreemap/treemap/js/src/lib/searchBar.js
While OpenTreeMap/otm-core@b65bcf94 fixed issues with reloads on the map page, it broke forwarding the address when redirecting to the map page.
Connects to #1123
> Fix search address in redirect

- opentreemap/exporter/__init__.py
- opentreemap/exporter/decorators.py
- opentreemap/exporter/views.py
- opentreemap/manage_treemap/routes.py
- opentreemap/treemap/js/src/lib/export.js
Adds an additional error message, to distinguish between exports being
disabled for non-admins vs. trial maps.
Also ensures that error messages when starting an export are displayed,
in additional to when checking on export status.
Connects to OpenTreeMap/otm-addons#1416
> Add more detail to export error messages

- opentreemap/stormwater/tests.py
- opentreemap/treemap/lib/perms.py
- opentreemap/treemap/tests/test_perms.py
- opentreemap/treemap/views/misc.py
This addresses an edge case where a role has permission to add trees but not add plots.
I made use of a helper function to check tree creatability so I renamed it from `map_feature_is_creatable` to `model_is_creatable`.
---
Testing
- Create a new instance.
- Enable `Can add tree` on the `Public` role.
- Invite a secondary user to the `Public` role.
- As the admin user, create an empty plot.
- Log in as the secondary user and go to the empty plot detail page.
- The `Edit` button should be enabled.
- Clicking `Edit` should show the `Add tree` button, but none of the plot fields should be editable.
- Saving the new tree succeeds.
---
Connects to #2856
> Update map_feature_is_writable to check tree permissions

- opentreemap/treemap/audit.py
- opentreemap/treemap/templates/treemap/field/attrs.html
- opentreemap/treemap/templates/treemap/field/inputs.html
- opentreemap/treemap/templatetags/form_extras.py
- opentreemap/treemap/templatetags/util.py
- opentreemap/treemap/util.py
> Prevent numbers from being formatted in scientific notation in forms

- opentreemap/treemap/js/src/mapFeatureDetail.js
There was existing code to update streeview after a successful save, but that code expected the form data to include `plot.geom`. It does not. `plot.geom` is appended directly to the data PUT back to the server in a before save handler.
To get around this, we just read the location from the plot mover. It is safe to call `panorama.update` even if there is no geometry change. It is effectively a noop.
---
- Add a plot then edit it.
- Move the plot location and save. Verify that the streetview changes.
---
Connects to #2935
> Fix streetview update after saving on the tree detail page

- opentreemap/modeling/run_model/GrowthModelUrbanTreeDatabase.py
- opentreemap/modeling/views.py
- opentreemap/treemap/models.py
Instances that were migrated into the database have species rows that do not have an `otm_code`, which modeling scenarios depend on.
To resolve this we have:
- Added class method to `Species` to try fetching a species and fall back to using an `ITreeCodeOverride`
- Added a validation to prevent loading species into the scenario drop-down lists that cannot be matched to an instance species
PhillyTreeMap before
PhillyTreeMap after
- Modified the scenario run view function to use the new species fetch method.
---
- Create a modeling scenario on PhillyTreeMap and add a single tree for every species in the list. Verify that the "Calculate Scenario" button works.
- Create a modeling scenario on PhillyTreeMap, add a distribution area, and add a distribution for every species in the list. Verify …
> Add lookups to enable modeling scenarios with overridden species

- opentreemap/treemap/js/src/lib/socialMediaSharing.js
- opentreemap/treemap/templates/treemap/map_feature_detail.html
- opentreemap/treemap/templates/treemap/partials/photo_carousel.html
There are three tree photo upload situations where we do not want to show a social media sharing dialog after POSTing the image to the server.
- The instance is private.
- The image file was invalid.
- The image file was too big.
Private instances are not handled by not rendering the dialog markup on the page unless the instance is public.
Invalid images are handled by checking the markup returned from the response for the presence of an error element. This is not ideal, but is easier that changing the way failures are reported vs. loading updated carousel markup.
Large images are intended to be blocked by Nginx before reaching Django. If they reach Django they will trigger a validation error, which will be handled the same way invalid images are handled.
---
- Create 2 instances, 1 …
> Don't show the tree photo sharing dialog if it is not appropriate

- opentreemap/importer/tasks.py
The CSV reader encodes non-ASCII characters as UTF-8, which was causing the header row field validation to fail. Decoding the CSV field names before comparing them to the field names stored in the database resolves the issue.
---
- Create a new instance centered on Los Angeles
- Add a new text custom field to Tree named `Localização`
- Import this CSV that includes a `Tree: Localização` column: [import-with-unicode.csv.zip](https://github.com/OpenTreeMap/otm-core/files/851616/import-with-unicode.csv.zip)
The the file should validate successfully and trees added to the map should have values in the `Localização` field.
---
Connects to https://github.com/OpenTreeMap/otm-addons/issues/1467
> Decode CSV header row field names so that they correctly validate

- opentreemap/importer/tasks.py
- opentreemap/importer/views.py
NOTE: This PR builds on top of #3219. Only the last commit is specific to this PR.
Template downloads were failing for instances with user defined field names
containing non-ASCII characters.
---
- Create a new instance centered on Los Angeles
- Add a new text custom field to Tree named Localização
- Export the tree import CSV template and verify that all the column headers in the template are correct.
---
Connects to #1466
> Encode field names as UTF-8 when generating CSV import templates

- opentreemap/manage_treemap/js/src/units.js
- opentreemap/manage_treemap/views/__init__.py
Calculating ecobenefits for a large number of trees can be expensive, so we cache the results based on query string arguments and the `universal_rev` of the instance. After changing the units of a field, the same query string can produce different results so we must increment the `universal_rev` to bust the cache.
Connects #3224 
* Create a new instance with the URL name `unit-eco-test` via http://localhost:6060/create
* Add three trees with the following diameters
* 3.1in
* 5in
* 7.9in
* Click the "Advanced" button above the "Search" button and in the "Tree" down down enter a range of 3in to 8in.
* Click "Search" and verify that "3 Trees" appears in the search result
* Go to the units management page http://localhost:6060/unit-eco-test/management/units/
* Click "Edit"
* Change the units …
> Update universal rev after changing instance units.

- opentreemap/importer/util.py
When importing a file with multichoice values (i.e. "[""A"", ""B""]") the `csv.Sniffer` was incorrectly identifying the delimiter as '['. Passing a string of allowed delimiters to the `sniff` method avoids this. 
https://docs.python.org/2/library/csv.html#csv.Sniffer.sniff
Connects https://github.com/OpenTreeMap/otm-clients/issues/412
Connects https://github.com/OpenTreeMap/otm-clients/issues/407
* Log in. Use http://localhost:6060/create to create a new instance.
* Set the URL name to `multi-fix`.
* On step "3. Choose tree map location" use the geocoder to set the center to "South El Monte, CA, USA"
* Add a multi-choice field
* Browse http://localhost:6060/multi-fix/management/udfs/
* Click "Add"
* Create a multi-choice field matching this screenshot:
* Download …
> Restrict supported import file delimiters to , and \t

- assets/js/shim/jquery.fileupload.js
- assets/js/shim/jquery.iframe-transport.js
- assets/js/vendor/jquery.js
- assets/js/vendor/jquery.ui.widget.js
- opentreemap/manage_treemap/js/src/branding.js
- opentreemap/manage_treemap/js/src/embed.js
- opentreemap/manage_treemap/js/src/lib/reorderFields.js
- opentreemap/manage_treemap/js/src/udfs.js
- opentreemap/modeling/js/src/lib/modelingParamUI.js
- opentreemap/modeling/js/src/modeling.js
- opentreemap/otm_comments/js/src/lib/comments.js
- opentreemap/treemap/js/src/base.js
- opentreemap/treemap/js/src/lib/buttonEnabler.js
- opentreemap/treemap/js/src/lib/diameterCalculator.js
- opentreemap/treemap/js/src/lib/geometryMover.js
- opentreemap/treemap/js/src/lib/imageLightbox.js
- opentreemap/treemap/js/src/lib/mapFeatureDelete.js
- opentreemap/treemap/js/src/lib/mapFeatureUdf.js
- opentreemap/treemap/js/src/lib/otmTypeahead.js
- opentreemap/treemap/js/src/lib/popover.js
- opentreemap/treemap/js/src/lib/socialMediaSharing.js
- opentreemap/treemap/js/src/lib/uploadPanel.js
- opentreemap/treemap/js/src/lib/utility.js
- opentreemap/treemap/js/src/mapPage/drawAreaMode.js
- opentreemap/treemap/js/src/mapPage/editAreaMode.js
- opentreemap/treemap/js/src/mapPage/locationSearchUI.js
- opentreemap/treemap/js/src/simpleForm.js
- opentreemap/treemap/js/src/treeMap.js
- package.json
Update jQuery to the latest version and jquery.fileupload to a newer version.
Connects #3228
Required by https://github.com/OpenTreeMap/otm-addons/pull/1553
I tried to update jquery.fileupload and its companion libraries to the latest versions, but it caused a webpack error due to a change in AMD require naming.
blueimp/jQuery-File-Upload@a9bfde1
I pulled in the version before this naming change (9.12.4) and it resolved the webpack issue along with eliminating the deprecation warning from jquery-migrate.
Similarly I attempted use the latest [jquery-migrate](https://github.com/jquery/jquery-migrate/)
(3.0.1) but ran into webpack AMD errors. Rolling back to version 3.0.0 as mentioned in Github issue threads resolved the issue.
Some of our dependencies use deprecated methods. Since the …
> Upgrade jQuery to 3.3.1

- opentreemap/treemap/js/src/lib/utility.js
When upgrading our jQuery version I mistakenly updated this call to `click` on a
plain DOM element.
Connects #3231
* Run through the reproduction steps in #3231
> Fix modeling CSV download

- opentreemap/treemap/templates/treemap/field/diameter_div.html
- opentreemap/treemap/templates/treemap/field/diameter_tr.html
- opentreemap/treemap/templates/treemap/field/div.html
- opentreemap/treemap/templates/treemap/partials/diameter_calculator.html
- opentreemap/treemap/templates/treemap/partials/diameter_video.html
connects to #2450. When adding tree error message will be displayed above video link and an error message will display after video link in edit tab.
> Fixed issue diameter value is not showing directly below diameter field.

- opentreemap/treemap/js/src/mapPage/addMapFeature.js
- opentreemap/treemap/templates/treemap/partials/step_set_location.html
This PR is based on #3238 with
* Whitespace fixes.
* A complete `pointInMap` function.
* A change to the `onGeolocateSuccess` handler so that we pass a Leaflet `LatLng` to `pointInMap`. Passing the `onGeolocateSuccess` argument into `pointInMap` was failing because the object was not in the format that `leaflet-pip` expected.
> Fixed current location popping out of bounds

- opentreemap/treemap/js/src/lib/MapManager.js
OTM supports multiple basemap providers, each with different basemap names. When we store the selected basemap, we need to namespace that selection under the provider name.
Connects https://github.com/OpenTreeMap/otm-cloud/issues/438
- Browse the map page of an existing instance
- Change the basemap to satellite
- Refresh the page and verify that the basemap change persists
- Browse `/create` and work through the instance creation wizard
- Verify that the Bing basemap correctly appears on the 3rd page of the create wizard
>  Incorporate the basemap provider into selected basemap storage

- opentreemap/treemap/js/src/lib/udfcSearch.js
Dates on the advanced search toolbar were being set incorrectly because the parsing a short date with the long date format was being interpreted as valid. Enabling "strict mode" makes the date parsing resolves this.
Connects #3245 
Before
After
* Visit production https://www.opentreemap.org/phillytreemap/map/
* Open the advanced search menu, click on Tree Care, and select any values for the first 3 dropdowns
* Select May 1 in the date pickers and verify the bad behavior
* Repeat the process with a local instance and verify that setting May 1 in the date pickers works.
> Use strict mode when using moment.isValid to check date formatting.

- opentreemap/manage_treemap/views/user_roles.py
The registration system uses both the `activated` field in addition to the `User.is_active` fields. Setting `User.is_active` to false after activation lets us disable an account and prevent the user from reactivating it. Because of this we must also update the `activated` field.
Connects #3247
Before this fix, users who accepted invitations were unable to reset their passwords because of this code:
https://github.com/OpenTreeMap/otm-core/blob/2.21.0/opentreemap/registration_backend/views.py#L211-L212
* Run `./scripts/debugserver.sh`
* Browse http://localhost:6060/create and make an instance named `activation-test`
* Browse http://localhost:6060/activation-test/management/user-roles/
* Click "Add User" and submit an email address that does not yet exist in the database.
* An invitation …
> Mark registration profile activated when confirming invited user

- requirements.txt
Replaces use of `urllib` and `urllib2` with Requests library while attempting to maintain backwards compatibility.
Fixes https://github.com/azavea/operations/issues/200
---
**Testing**
Provision the `app` virtual machine with this branch, then ensure that v5.1.0 of Omgeo was installed:
```bash
vagrant@app:~$ pip freeze 2> /dev/null | grep omgeo
python-omgeo==5.1.0
```
In addition, interact with the `/geocode` endpoint to ensure that it continues to function.
```bash
$ http "http://localhost:6060/geocode?address=990%20Spring%20Garden%20St%2C%20Philadelphia%2C%20PA%2C%2019123%2C%20USA&key=dHA9MCNsb2M9MTY2NTMzMSNsbmc9MzMjZmE9NTA0NjI3MiNobj05OTA%3D"
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Language: en
Content-Type: application/json
Date: Wed, 20 Jun 2018 17:34:28 …
```
> Upgrade Omgeo to v5.1.0

- opentreemap/exporter/management/commands/create_photo_csv.py
Adds a command to write out the feature id, tree id, and the URL of all photos for an instance as a CSV. This CSV can then be processed on a developer workstation to export all of the instance photos.
Connects https://github.com/OpenTreeMap/otm-addons/issues/1557
I modified the Jenkins job to deploy this branch to staging.
* Log in and create an instance named `photo-export-test` via https://staging.opentreemap.org/create
* Add a tree to the instance and add a photo to the tree.
* Add a second tree to the instance and add two photos to the tree. Use two different image file types. 
* ssh to a staging app server via the staging bastion
* `cd /opt/app/core`
* `envdir /etc/otm.d/env opentreemap/manage.py create_photo_csv --instance-url-name photo-export-test`
* Verify that 3 lines are …
> Add create_photo_csv management command

- opentreemap/treemap/js/src/lib/MapManager.js
- package.json
Tapping on the layers control in Mobile Safari was not opening the layer selector. I was not able to reproduce this issue in a separate test application, only within OTM.
After much trial and error I discovered that changing this line
```javascript
L.DomEvent.on(el, L.Draggable.START.join(' '), stop);
```
to
```javascript
L.DomEvent.on(container, 'mousedown', stop);
```
in `DomEvent.disableClickPropagation` resolved the issue. Effectively, this prevents the `touchstart` event from being stopped.
I opted to implement this as a runtime patch applied within MapManager instead of a global patch to the Leaflet source because there are no other Leaflet behaviors that are known to be broken in Mobile Safari and I did not want to risk introducing a regression in some other event handling.
I …
> Monkey patch the Leaflet layer selector to work in Mobile Safari

- opentreemap/treemap/js/src/lib/MapManager.js
Avoids an unhandled exception when the `basemap_type` of an instance has changed and a previous layer selection persisted in local storage no longer exists.
Connects #3255 
* Browse an instance with the `google` basemap.
* Select the `Satellite` layer
* Refresh the page and verify that the `Satellite` layer is displayed
* Update the instance `basemap_type` to `bing`.
```
otm=# update treemap_instance set basemap_type = 'google', universal_rev = universal_rev + 1;
```
* Refresh the map page
* Verify that the street layer loads and no error is logged in the JS console.
> Handle basemap preference not available

- opentreemap/manage_treemap/js/src/udfs.js
NOTE:  This is a copy of #3259 targeted at the 2.21.4 hotfix branch.
In the case where choice fields contain numeric values, this helper is called with a number and fails unless we force the value to a string.
Connects https://github.com/OpenTreeMap/otm-clients/issues/441
* Checkout the `develop` branch
* Browse http://localhost:6060/create/ and create an instance called 'numeric-choices'
* Visit http://localhost:6060/numeric-choices/management/udfs/ and click `+ Add Field`
* Create a choice field like this and click `Finish` to save it.
* Refresh the page and click `Edit`. Start typing a new choice value and you will see an exception in the console
* Checkout this branch, reload the page, and click `Edit`.
* Verify that you can successfully add a new choice value and save it.
> Fix UDF choice editing helper function (hotfix)

- assets/css/sass/partials/pages/_admin.scss
- opentreemap/manage_treemap/js/src/udfs.js
- opentreemap/manage_treemap/templates/manage_treemap/partials/fields/udf_choice_item.html
Leading or trailing whitespace cannot be easily seen, but causes problems matching values. This change follows the pattern of other client-side choice validations.
Connects https://github.com/OpenTreeMap/otm-clients/issues/442
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* Visit http://localhost:6060/create and create an instance named `trailing-choice`
* Visit http://localhost:6060/trailing-choice/management/udfs/, click `Edit` and verify that an error message is displayed and the save button is disabled if an existing choice or a new choice has leading or trailing whitespace
* Verify that new and edited choices can still be saved if they do not have excess whitespace.
> Add client-side validation to prevent extra udf choice whitespace

- requirements.txt
Connects https://github.com/OpenTreeMap/otm-cloud/issues/457
Django release notes:
https://docs.djangoproject.com/en/2.1/releases/1.11.5/
https://docs.djangoproject.com/en/2.1/releases/1.11.6/
https://docs.djangoproject.com/en/2.1/releases/1.11.7/
https://docs.djangoproject.com/en/2.1/releases/1.11.8/
https://docs.djangoproject.com/en/2.1/releases/1.11.9/
https://docs.djangoproject.com/en/2.1/releases/1.11.10/
https://docs.djangoproject.com/en/2.1/releases/1.11.11/
https://docs.djangoproject.com/en/2.1/releases/1.11.12/
https://docs.djangoproject.com/en/2.1/releases/1.11.13/
https://docs.djangoproject.com/en/2.1/releases/1.11.14/
https://docs.djangoproject.com/en/2.1/releases/1.11.15/
https://docs.djangoproject.com/en/2.1/releases/1.11.16/
requests release notes: …
> Update Django and requests

- opentreemap/treemap/js/src/lib/plotDetail.js
- opentreemap/treemap/templates/treemap/partials/tree_section.html
Instance managers can hide the tree ID field from view, which was breaking the delete logic.
Connects #3265 
Connects https://github.com/OpenTreeMap/otm-clients/issues/439
Depends on https://github.com/OpenTreeMap/otm-cloud/pull/467
- Create an instance named `delete-without-tree-id-test`
- Browse http://localhost:6060/delete-without-tree-id-test/management/field-configuration/
- Click "Edit"
- Uncheck "ID" in the "Tree" section.
- Click "Save"
- Click "Add a tree." Complete the add tree process, filling in a species and diameter.
- Browse the detail page for the tree
- Click "Delete" and "Confirm Deletion". Verify that the tree is deleted without error.
> Read tree ID from detail page tree section header rather than field

- opentreemap/manage_treemap/views/fields.py
The management page was allowing the Tree ID field to be hidden, but was not rendering the option in the hidden field list so that it could be shown again. We have corrected the `_should_show_field` predicate function and corrected the model argument passed to it so that the Tree ID field is correctly shown in the disabled field list.
Connects #3264 
Depends on https://github.com/OpenTreeMap/otm-cloud/pull/467
- Create an instance named `tree-id-show-and-hide-test`
- Browse http://localhost:6060/tree-id-show-and-hide-test/management/field-configuration/
- Click "Edit"
- Uncheck "ID" in the "Tree" section.
- Click "Save"
- Refresh the page and click "Edit". Verify that "ID" appears in the "Tree" section.
- Check "ID" and click "Save"
- Refresh the page and verify that "ID" appears in the …
> Allow a hidden Tree ID field to be shown

- opentreemap/api/instance.py
- opentreemap/treemap/lib/perms.py
The Android application checks the value of the `can_edit_tree` instance meta permission and does not PUT changes to the API if it has a value of false. This meta permission was incorrectly looking only at plot fields. This resulted in members of a role that could only edit tree fields being prevented from saving any tree changes.
Connects https://github.com/OpenTreeMap/otm-clients/issues/446
The `can_edit_tree` instance meta permission is not used by the web app or the iOS app, so the effect of this change is limited.
* Ensure that you can run the Android application and have it connect to your development OTM environment.
* Ensure that you have 2 separate user accounts set up.
* Log in as "user A," browse http://localhost:6060/create, and create an instance named `sdtest`.
* Browse …
> Fix can_edit_tree instance meta permission

- requirements.txt
Includes bug fixes. A transitive dependency of [requests](http://python-requests.org/).
Connects https://github.com/OpenTreeMap/otm-cloud/issues/466
Searching through the core, cloud, and addons code bases using the regex `import.*requests` returns just 2 usages.
* A geocoding unit test.
* An non-critical add-on utility for POSTing data to Salesforce 
* Reprovision and `pip freeze` to ensure that the updated version is installed.
* Verify that the unit tests pass.
> Update urllib3 from 1.22 to 1.23

- opentreemap/opentreemap/settings/default_settings.py
- opentreemap/registration_backend/views.py
- requirements.txt
We are attempting to prevent spam account registrations by adding a robot test via Google's reCAPTCHA service and the `django-recaptcha` library.
Connects https://github.com/OpenTreeMap/otm-cloud/issues/461
Depends on https://github.com/OpenTreeMap/otm-cloud/pull/469
From https://developers.google.com/recaptcha/docs/faq
>reCAPTCHA v2 is not going away! We will continue to fully support and improve security and usability for v2.
>reCAPTCHA v3 is intended for power users, site owners that want more data about their traffic, and for use cases in which it is not appropriate to show a challenge to the user.
NOTE: This is currently deployed to staging: https://staging.opentreemap.org/accounts/register/
* Log out and visit the registration page at `/accounts/register/`
* Verify that the …
> Add django-recaptca to the user registration page

- package.json
npm complained about this:
$ npm audit fix
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "leaflet.gridlayer.googlemutant ": name cannot contain leading or trailing spaces; name can only contain URL-friendly characters
> Remove trailing space from package name

- opentreemap/treemap/js/src/lib/otmTypeahead.js
Requests with unescaped curly brace characters started returning 400s.
Connects https://github.com/OpenTreeMap/otm-cloud/issues/476
Depends on https://github.com/OpenTreeMap/otm-cloud/pull/477
Depends on https://github.com/OpenTreeMap/otm-website/pull/190
> Encode the searchExtent param when making ESRI geocode request
